# Project Bedrock Blender Import Tools — generated by bedrock-blender
#
# Install: Blender > Edit > Preferences > Add-ons > Install...
# Then enable "Project Bedrock Import Tools"

bl_info = {
    "name": "Project Bedrock Import Tools",
    "author": "Project Bedrock",
    "version": (0, 1, 0),
    "blender": (3, 6, 0),
    "location": "File > Import > Project Bedrock Export (.obj)",
    "description": "Import Project Bedrock OBJ exports with materials, PBR, MCprep compatibility, and organised collections",
    "warning": "",
    "doc_url": "",
    "support": "COMMUNITY",
    "category": "Import-Export",
}

import bpy
import os
from pathlib import Path
from bpy_extras.io_utils import ImportHelper
from bpy.types import Operator
from bpy.props import StringProperty, BoolProperty, EnumProperty

# Swappable block types supported by MCprep 3D library (vegetation, 3D items, containers)
SWAPPABLE_BLOCKS = {
    "dandelion", "poppy", "blue_orchid", "allium", "azure_bluet",
    "red_tulip", "orange_tulip", "white_tulip", "pink_tulip", "oxeye_daisy",
    "cornflower", "lily_of_the_valley", "sunflower", "lilac", "rose_bush",
    "peony", "wheat", "carrots", "potatoes", "beetroots", "torch", "soul_torch",
    "redstone_torch", "lantern", "soul_lantern", "chest", "trapped_chest",
    "ender_chest", "crafting_table", "furnace", "blast_furnace", "smoker",
}

# ---------------------------------------------------------------------------
# Import Operator
# ---------------------------------------------------------------------------

class IMPORT_OT_project_bedrock(Operator, ImportHelper):
    """Import a Project Bedrock OBJ export with materials, MCprep integration, and organisation"""
    bl_idname = "import_scene.project_bedrock"
    bl_label = "Import Project Bedrock Export"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".obj"

    filter_glob: StringProperty(
        default="*.obj",
        options={'HIDDEN'},
    )

    use_pbr: BoolProperty(
        name="Apply PBR Materials",
        description="Apply PBR material presets (roughness, metallic, emissive)",
        default=True,
    )

    use_mcprep_materials: BoolProperty(
        name="Use MCprep Prep Materials",
        description="Automatically run MCprep material prep on imported objects if MCprep addon is active",
        default=True,
    )

    use_mcprep_meshswap: BoolProperty(
        name="Use MCprep MeshSwap",
        description="Automatically swap vegetation, torches, and 3D blocks with MCprep models if MCprep addon is active",
        default=True,
    )

    organise_collections: BoolProperty(
        name="Organise into Collections",
        description="Organise imported objects into collections by chunk and block type",
        default=True,
    )

    collection_scheme: EnumProperty(
        name="Collection Scheme",
        description="How to organise objects into collections",
        items=[
            ('CHUNK_THEN_TYPE', 'Chunk > Block Type', 'Group by chunk, then block type'),
            ('BY_CHUNK', 'By Chunk', 'One collection per chunk'),
            ('BY_TYPE', 'By Block Type', 'One collection per block type'),
            ('FLAT', 'Flat', 'All objects in one collection'),
        ],
        default='CHUNK_THEN_TYPE',
    )

    auto_detect_atlas: BoolProperty(
        name="Auto-detect Atlas",
        description="Automatically find and assign the texture atlas PNG",
        default=True,
    )

    def execute(self, context):
        import time
        t_start = time.time()
        wm = context.window_manager
        wm.progress_begin(0, 100)

        wm.progress_update(10)
        t0 = time.time()
        result = self.import_obj(context)
        t_import = (time.time() - t0) * 1000.0
        if result != {'FINISHED'}:
            wm.progress_end()
            return result

        self.deduplicate_materials(context)

        imported_objs = [obj for obj in context.selected_objects if obj.type == 'MESH']
        if not imported_objs:
            imported_objs = [obj for obj in bpy.data.objects if obj.type == 'MESH']

        # 1. Apply PBR & Atlas texturing FIRST so materials have texture nodes for MCprep
        wm.progress_update(30)
        t0 = time.time()
        if self.use_pbr:
            self.apply_pbr_materials(context)
        t_pbr = (time.time() - t0) * 1000.0

        # 2. Fast O(1) collection organization
        wm.progress_update(50)
        t0 = time.time()
        if self.organise_collections:
            self.organise_objects(context)
        t_collections = (time.time() - t0) * 1000.0

        # 3. Configure MCprep exporter setting & run MCprep operators non-interactively ('EXEC_DEFAULT')
        wm.progress_update(70)
        t_mcprep_materials = 0.0
        t_mcprep_meshswap = 0.0
        if hasattr(bpy.ops, 'mcprep'):
            try:
                if 'MCprep_addon' in bpy.context.preferences.addons:
                    bpy.context.preferences.addons['MCprep_addon'].preferences.MCprep_exporter_type = 'Mineways'
            except Exception:
                pass

            if self.use_mcprep_materials and hasattr(bpy.ops.mcprep, 'prep_materials'):
                t0 = time.time()
                try:
                    bpy.ops.mcprep.prep_materials('EXEC_DEFAULT')
                except Exception as e:
                    self.report({'WARNING'}, f"MCprep prep_materials warning: {e}")
                t_mcprep_materials = (time.time() - t0) * 1000.0

            wm.progress_update(90)
            if self.use_mcprep_meshswap and hasattr(bpy.ops.mcprep, 'meshswap'):
                t0 = time.time()
                swappable = []
                for obj in imported_objs:
                    if obj and obj.name in bpy.data.objects:
                        name_base = obj.name.split('.')[0].lower()
                        mat_base = (obj.active_material.name.split('.')[0].lower() if obj.active_material else "")
                        if name_base in SWAPPABLE_BLOCKS or mat_base in SWAPPABLE_BLOCKS:
                            swappable.append(obj)

                if swappable:
                    bpy.ops.object.select_all(action='DESELECT')
                    for o in swappable:
                        o.select_set(True)
                    context.view_layer.objects.active = swappable[0]

                    try:
                        bpy.ops.mcprep.meshswap('EXEC_DEFAULT')
                    except Exception as e:
                        self.report({'WARNING'}, f"MCprep meshswap warning: {e}")
                t_mcprep_meshswap = (time.time() - t0) * 1000.0

        wm.progress_update(100)
        wm.progress_end()

        t_total = time.time() - t_start
        summary_msg = (
            f"\n=======================================================\n"
            f" Project Bedrock Import Complete in {t_total:.2f}s\n"
            f" -------------------------------------------------------\n"
            f"  - OBJ Import:               {t_import:.1f} ms\n"
            f"  - PBR Setup:                {t_pbr:.1f} ms\n"
            f"  - Collection Organisation:  {t_collections:.1f} ms\n"
            f"  - MCprep Materials:         {t_mcprep_materials:.1f} ms\n"
            f"  - MCprep MeshSwap:          {t_mcprep_meshswap:.1f} ms\n"
            f"  - Objects Processed:        {len(imported_objs)}\n"
            f"=======================================================\n"
        )
        print(summary_msg)
        self.report({'INFO'}, f"Project Bedrock Import complete in {t_total:.2f}s ({len(imported_objs)} objects)")

        return {'FINISHED'}

    def import_obj(self, context):
        """Import the OBJ using Blender's built-in importer with version fallback."""
        res = {'CANCELLED'}
        # Modern C++ importer (Blender 4.0+, 5.x)
        if hasattr(bpy.ops.wm, 'obj_import'):
            try:
                res = bpy.ops.wm.obj_import(
                    filepath=self.filepath,
                    forward_axis='NEGATIVE_Z',
                    up_axis='Y',
                    use_split_objects=True,
                    use_split_groups=True
                )
            except Exception:
                try:
                    res = bpy.ops.wm.obj_import(filepath=self.filepath)
                except Exception as e:
                    self.report({'WARNING'}, f"wm.obj_import failed: {e}")

        # Legacy importer (Blender 3.x)
        elif hasattr(bpy.ops, 'import_scene') and hasattr(bpy.ops.import_scene, 'obj'):
            try:
                res = bpy.ops.import_scene.obj(
                    filepath=self.filepath,
                    use_split_groups=True,
                    use_split_objects=True,
                    axis_forward='-Z',
                    axis_up='Y',
                )
            except Exception as e:
                self.report({'ERROR'}, f"import_scene.obj failed: {e}")
                return {'CANCELLED'}

        # Post-import: ensure each object is named by its active material so MCprep recognises all block types
        for obj in context.selected_objects:
            if obj.type == 'MESH' and obj.active_material:
                clean_name = obj.active_material.name.split('.')[0]
                obj.name = clean_name

        return res

    def organise_objects(self, context):
        """Move imported objects into organised collections fast."""
        imported = [obj for obj in context.selected_objects if obj.type == 'MESH']
        if not imported:
            imported = [o for o in bpy.data.objects if o.type == 'MESH' and len(o.users_collection) <= 1]

        if not imported:
            return

        root_name = "Bedrock Export"
        root_col = (bpy.data.collections.get(root_name)
                    or bpy.data.collections.new(root_name))

        if root_col.name not in context.scene.collection.children:
            context.scene.collection.children.link(root_col)

        cols_cache = {}

        def get_child(parent, name):
            key = (parent.name, name)
            if key in cols_cache:
                return cols_cache[key]
            child = bpy.data.collections.get(name) or bpy.data.collections.new(name)
            if child.name not in parent.children:
                parent.children.link(child)
            cols_cache[key] = child
            return child

        scheme = self.collection_scheme
        if scheme == 'FLAT':
            for obj in imported:
                for col in list(obj.users_collection):
                    if col != root_col:
                        col.objects.unlink(obj)
                if root_col.name not in [c.name for c in obj.users_collection]:
                    root_col.objects.link(obj)
            return

        groups = {}
        for obj in imported:
            obj_name = obj.name.split('.')[0]
            if scheme == 'BY_CHUNK':
                chunk_name = self._guess_chunk_name(obj)
                target = get_child(root_col, chunk_name)
            elif scheme == 'BY_TYPE':
                type_name = self._sanitise_name(obj_name)
                target = get_child(root_col, f"BlockType_{type_name}")
            else:
                chunk_name = self._guess_chunk_name(obj)
                chunk_col = get_child(root_col, chunk_name)
                type_name = self._sanitise_name(obj_name)
                target = get_child(chunk_col, f"BlockType_{type_name}")

            if target not in groups:
                groups[target] = []
            groups[target].append(obj)

        for target, objs in groups.items():
            for obj in objs:
                for col in list(obj.users_collection):
                    if col != target:
                        col.objects.unlink(obj)
                if obj.name not in target.objects:
                    target.objects.link(obj)

        self.report({'INFO'}, f"Organised {len(imported)} objects into collections")

    def _sanitise_name(self, name: str) -> str:
        """Make a name safe for Blender collection names."""
        return ''.join(c if c.isalnum() or c in '_-' else '_' for c in name)

    def _guess_chunk_name(self, obj) -> str:
        """Fast O(1) chunk coordinate estimation using bounding box center."""
        import math
        try:
            bbox = obj.bound_box
            cx = (bbox[0][0] + bbox[6][0]) * 0.5 + obj.location.x
            cz = (bbox[0][2] + bbox[6][2]) * 0.5 + obj.location.z
        except Exception:
            cx, cz = obj.location.x, obj.location.z

        chunk_x = int(math.floor(cx / 16.0))
        chunk_z = int(math.floor(cz / 16.0))
        return f"Chunk_{chunk_x}_{chunk_z}"

    def _ensure_child(self, parent, name):
        child = bpy.data.collections.get(name)
        if child is None:
            child = bpy.data.collections.new(name)
        if child.name not in parent.children:
            parent.children.link(child)
        return child

    def deduplicate_materials(self, context):
        remap = {}
        base_mats = {}
        for mat in list(bpy.data.materials):
            clean = mat.name.split('.')[0]
            if clean in base_mats:
                remap[mat] = base_mats[clean]
            else:
                base_mats[clean] = mat
                if mat.name != clean and clean not in bpy.data.materials:
                    mat.name = clean

        for obj in bpy.data.objects:
            if obj.type == 'MESH':
                for slot in obj.material_slots:
                    if slot.material in remap:
                        slot.material = remap[slot.material]

        for mat in list(bpy.data.materials):
            if mat.users == 0:
                bpy.data.materials.remove(mat)

    def apply_pbr_materials(self, context):
        atlas_path = None
        if self.auto_detect_atlas:
            atlas_path = self._find_atlas()

        for mat in bpy.data.materials:
            self._apply_pbr_to_material(mat, atlas_path)

    def _find_atlas(self):
        obj_dir = os.path.dirname(self.filepath)
        obj_base = os.path.splitext(os.path.basename(self.filepath))[0]

        candidates = [
            os.path.join(obj_dir, f"{obj_base}.atlas.png"),
            os.path.join(obj_dir, f"{obj_base}_atlas.png"),
            os.path.join(obj_dir, "atlas.png"),
            os.path.join(obj_dir, "terrainExt.png"),
        ]
        for path in candidates:
            if os.path.isfile(path):
                return path
        return None

    def _apply_pbr_to_material(self, mat, atlas_path):
        if not mat.use_nodes:
            mat.use_nodes = True
        nodes = mat.node_tree.nodes
        links = mat.node_tree.links

        clean_name = mat.name.split('.')[0].lower()

        # Find Principled BSDF node or create one
        principled = nodes.get('Principled BSDF')
        if not principled:
            for n in nodes:
                if n.type == 'BSDF_PRINCIPLED':
                    principled = n
                    break
        if not principled:
            nodes.clear()
            principled = nodes.new('ShaderNodeBsdfPrincipled')
            principled.location = (0, 0)
            output = nodes.new('ShaderNodeOutputMaterial')
            output.location = (300, 0)
            links.new(principled.outputs['BSDF'], output.inputs['Surface'])

        # MCprep default texture pack path & individual exported textures folder
        mcprep_tp = Path(r"C:\Users\zebby\AppData\Roaming\Blender Foundation\Blender\5.2\scripts\addons\MCprep_addon\MCprep_resources\resourcepacks\mcprep_default\assets\minecraft\textures")
        
        exported_textures_dir = None
        if hasattr(self, 'filepath') and self.filepath:
            exported_textures_dir = Path(self.filepath).parent / "textures"

        # Foliage materials requiring vibrant biome green tinting
        FOLIAGE_MATS = {
            "grass_block", "short_grass", "tall_grass", "fern", "oak_leaves",
            "jungle_leaves", "acacia_leaves", "dark_oak_leaves", "mangrove_leaves",
            "birch_leaves", "spruce_leaves", "vine", "lily_pad", "sugar_cane",
            "leaf_litter", "moss_block", "moss_carpet", "firefly_bush"
        }

        # Materials needing alpha cutout transparency
        ALPHA_MATS = {
            "oak_leaves", "jungle_leaves", "acacia_leaves", "dark_oak_leaves",
            "mangrove_leaves", "birch_leaves", "spruce_leaves", "short_grass",
            "tall_grass", "fern", "vine", "lily_pad", "sugar_cane", "spawner",
            "glass", "tinted_glass", "seagrass", "tall_seagrass", "dandelion",
            "poppy", "blue_orchid", "allium", "azure_bluet", "cornflower",
            "oxeye_daisy", "peony", "pointed_dripstone", "glow_lichen"
        }

        # Try to locate individual 16x16 PNG texture for this block material
        individual_img = None
        candidates = []
        if exported_textures_dir and exported_textures_dir.exists():
            candidates.append(exported_textures_dir / f"{clean_name}.png")
        candidates.extend([
            mcprep_tp / "block" / f"{clean_name}.png",
            mcprep_tp / "item" / f"{clean_name}.png",
            mcprep_tp / "entity/chest" / f"{clean_name}.png",
        ])

        for cand in candidates:
            if cand.exists():
                try:
                    individual_img = bpy.data.images.load(str(cand), check_existing=True)
                    break
                except Exception:
                    pass

        # Find existing TEX_IMAGE node or reuse/create one
        tex_image = None
        for n in nodes:
            if n.type == 'TEX_IMAGE':
                tex_image = n
                break
        if not tex_image:
            tex_image = nodes.new('ShaderNodeTexImage')
            tex_image.location = (-500, 0)

        tex_image.name = "MCPREP_diffuse"
        tex_image.interpolation = 'Closest'

        if individual_img:
            tex_image.image = individual_img
        elif atlas_path and os.path.isfile(atlas_path) and not tex_image.image:
            tex_image.image = bpy.data.images.load(atlas_path, check_existing=True)

        if hasattr(tex_image, 'mnp'):
            try:
                tex_image.mnp.MCPREP_diffuse = True
            except Exception:
                pass
        if tex_image.image:
            try:
                mat["MCPREP_diffuse"] = tex_image.image.name
            except Exception:
                pass

        if principled:
            if clean_name in FOLIAGE_MATS:
                old_mix = nodes.get('FoliageBiomeTint')
                if old_mix:
                    nodes.remove(old_mix)
                
                mix_node = nodes.new('ShaderNodeMix')
                mix_node.name = 'FoliageBiomeTint'
                mix_node.data_type = 'RGBA'
                mix_node.blend_type = 'MULTIPLY'
                # Set Factor socket = 1.0 (full multiply)
                mix_node.inputs[0].default_value = 1.0
                # Set Tint Color socket (Input 7) = Lush Biome Green
                mix_node.inputs[7].default_value = (0.28, 0.72, 0.18, 1.0)
                mix_node.location = (-250, 0)
                
                links.new(tex_image.outputs['Color'], mix_node.inputs[6])
                links.new(mix_node.outputs[2], principled.inputs['Base Color'])
            else:
                links.new(tex_image.outputs['Color'], principled.inputs['Base Color'])

            if clean_name in ALPHA_MATS or 'leaf' in clean_name or 'grass' in clean_name or 'flower' in clean_name:
                links.new(tex_image.outputs['Alpha'], principled.inputs['Alpha'])
                if hasattr(mat, 'blend_method'):
                    try:
                        mat.blend_method = 'CLIP'
                    except Exception:
                        pass

        if clean_name == "water" and principled:
            principled.inputs['Base Color'].default_value = (0.08, 0.35, 0.75, 1.0)
            if 'Roughness' in principled.inputs:
                principled.inputs['Roughness'].default_value = 0.05
            if 'Transmission Weight' in principled.inputs:
                principled.inputs['Transmission Weight'].default_value = 0.85
            if 'IOR' in principled.inputs:
                principled.inputs['IOR'].default_value = 1.333
            if hasattr(mat, 'blend_method'):
                try:
                    mat.blend_method = 'BLEND'
                except Exception:
                    pass

    def invoke(self, context, event):
        context.window_manager.fileselect_add(self)
        return {'RUNNING_MODAL'}


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------

classes = [
    IMPORT_OT_project_bedrock,
]

def register():
    for cls in classes:
        bpy.utils.register_class(cls)
    bpy.types.TOPBAR_MT_file_import.append(menu_func)

def unregister():
    bpy.types.TOPBAR_MT_file_import.remove(menu_func)
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)

def menu_func(self, context):
    self.layout.operator(
        IMPORT_OT_project_bedrock.bl_idname,
        text="Project Bedrock Export (.obj)",
    )

if __name__ == "__main__":
    register()
