# Project Bedrock Blender Import Tools — generated by bedrock-blender
#
# Install: Blender > Edit > Preferences > Add-ons > Install...
# Then enable "Project Bedrock Import Tools"

bl_info = {
    "name": "Project Bedrock Import Tools",
    "author": "Project Bedrock",
    "version": (0, 1, 0),
    "blender": (3, 6, 0),
    "location": "File > Import > Project Bedrock Export (.obj)",
    "description": "Import Project Bedrock OBJ exports with materials, PBR, MCprep compatibility, and organised collections",
    "warning": "",
    "doc_url": "",
    "support": "COMMUNITY",
    "category": "Import-Export",
}

import bpy
import os
import json
import math
from bpy_extras.io_utils import ImportHelper
from bpy.types import Operator
from bpy.props import StringProperty, BoolProperty, EnumProperty

# ---------------------------------------------------------------------------
# Tier 1: place real MCprep 3D assets from the exporter's block manifest
# ---------------------------------------------------------------------------

# Block id -> asset name in mcprep_meshSwap.blend, for the cases where the two
# don't already match. Everything not listed here is looked up by its own name
# (as a collection first, then an object), so this stays small on purpose.
# Blocks placed one block *above* their recorded position. MCprep has no
# `grass_block` asset — its `grass`/`short_grass`/`colormap/grass` objects are
# all the same grass-tuft mesh, meant to sit on top of the block rather than
# replace it. The block itself stays as exported geometry (a cube genuinely is
# the right shape for it); the tuft is what makes the surface read as grass.
MESHSWAP_OFFSETS = {
    "grass_block": (0.0, 0.0, 1.0),
}

# Blocks whose exported geometry must be *kept* even though an asset is placed
# for them — the asset augments the block instead of replacing it.
#
# This only holds for an asset placed at an offset, like a grass tuft sitting
# on top of a grass block. An asset placed at the block's own position is a
# replacement: keeping the exported cube as well leaves two coincident cubes
# that z-fight, which shows up as hard stripes banding across the terrain.
MESHSWAP_AUGMENTS_ONLY = {"grass_block"}

# Name prefix for the instance-source meshes the exporter's prototypes become.
PROTOTYPE_PREFIX = "PROTO_"

# Blocks whose geometry is flat or near-flat, and which must not cast shadows.
#
# A zero-thickness plane still casts a full shadow, so ground cover and
# surface decoration paint hard dark smears across the block beneath them —
# nothing like the game, where these are drawn as unlit decoration. Set on the
# prototype source object, which propagates to every instance of it.
NO_SHADOW_BLOCKS = {
    "leaf_litter",
    "moss_carpet",
    "glow_lichen",
    "vine",
    "lily_pad",
    "rail",
    "powered_rail",
    "seagrass",
    "short_grass",
    "fern",
}


def hide_meshswap_helpers():
    """Stop MCprep's non-renderable helper objects from showing up.

    `bpy.ops.mcprep.meshswap` spawns particle-emitter helpers alongside the
    blocks it swaps -- torch flame and smoke sources, named with a `noImport`
    suffix in the meshswap library. They are meant to drive particle systems,
    not to be drawn: each carries a flame *animation strip* mapped across a
    single quad, so a visible one renders as a column of garbled colour that
    reads as a stray broken torch floating in the scene.

    Unlinking rather than deleting keeps them available as data for whatever
    references them.

    Returns the number of helpers hidden.
    """
    # `noImport` is MCprep's explicit marker, but the particle sources it
    # spawns alongside a swapped block are named `<asset>.flame` / `.smoke`
    # and carry no marker at all. Both families render as stray garbled
    # torches, so match on either.
    def is_helper(name):
        low = name.lower()
        if "noimport" in low:
            return True
        # Strip Blender's `.001` duplicate suffix before testing the stem.
        stem = low.rsplit(".", 1)
        if len(stem) == 2 and stem[1].isdigit():
            low = stem[0]
        if low.endswith((".flame", ".smoke")):
            return True
        # MCprep does not name every emitter `<asset>.flame`: the campfire and
        # lantern families bring `smoke_flame.large` / `smoke_flame.med`, whose
        # suffix is the size, not the role. Matching only on the suffix let
        # those through, and they render exactly as the others would -- a
        # flame animation strip mapped whole across one quad, which reads as a
        # slab of scrambled colour hanging in mid-air beside the block.
        first = low.split(".", 1)[0]
        return first in ("smoke_flame", "smoke_gray", "fire_animation")

    hidden = 0
    for ob in list(bpy.data.objects):
        if not is_helper(ob.name):
            continue
        if not ob.users_collection:
            continue
        for coll in list(ob.users_collection):
            coll.objects.unlink(ob)
        ob.use_fake_user = True
        hidden += 1
    return hidden


# Blocks whose material gets the authored leaf shading. Keyed by suffix so any
# wood type is covered without listing all of them.
LEAF_MATERIAL_SUFFIXES = ("_leaves",)


def _material_base_color_source(mat):
    """The node socket feeding Base Color, and the Principled BSDF itself.

    Returns `(principled, source_socket)` or `(None, None)`. MCprep builds
    either `Image -> Principled` or `Image -> Mix -> Principled`, so the source
    is whatever is already wired in rather than an assumed node name.
    """
    if not mat.use_nodes or not mat.node_tree:
        return None, None
    bsdf = next((n for n in mat.node_tree.nodes if n.type == 'BSDF_PRINCIPLED'), None)
    if bsdf is None:
        return None, None
    base = bsdf.inputs.get("Base Color")
    if base is None or not base.is_linked:
        return bsdf, None
    return bsdf, base.links[0].from_socket


def apply_leaf_shading(mat):
    """Authored leaf look: dithered alpha, roughness 0.7, no specular.

    Leaves are cutout geometry seen in dense overlapping layers. Dithered
    transparency sorts correctly against itself where blended transparency
    produces ordering artefacts through a canopy.
    """
    bsdf, _ = _material_base_color_source(mat)
    if bsdf is None:
        return False
    if hasattr(mat, "surface_render_method"):
        mat.surface_render_method = 'DITHERED'
    bsdf.inputs["Roughness"].default_value = 0.7
    bsdf.inputs["Metallic"].default_value = 0.0
    if "Specular IOR Level" in bsdf.inputs:
        bsdf.inputs["Specular IOR Level"].default_value = 0.0
    if "Transmission Weight" in bsdf.inputs:
        bsdf.inputs["Transmission Weight"].default_value = 0.0
    return True


def apply_water_shading(mat):
    """Authored water look: glass/transparent mix over a procedural wave normal.

    Rebuilt from nodes each time rather than appended from a library, so the
    importer has no external blend dependency. Runs late for the same reason
    everything else here does: MCprep's `prep_materials` rebuilds a material's
    node graph from scratch and would discard this.
    """
    bsdf, _ = _material_base_color_source(mat)
    if bsdf is None:
        return False
    nt = mat.node_tree
    nodes, links = nt.nodes, nt.links

    if hasattr(mat, "surface_render_method"):
        mat.surface_render_method = 'BLENDED'

    bsdf.inputs["Roughness"].default_value = 0.0909
    bsdf.inputs["IOR"].default_value = 1.333
    bsdf.inputs["Metallic"].default_value = 0.0
    if "Transmission Weight" in bsdf.inputs:
        bsdf.inputs["Transmission Weight"].default_value = 1.0
    if "Specular IOR Level" in bsdf.inputs:
        bsdf.inputs["Specular IOR Level"].default_value = 0.0

    output = next((n for n in nodes if n.type == 'OUTPUT_MATERIAL'), None)
    if output is None:
        return False

    # Wave normal: Generated coords -> Mapping -> Gabor -> Ramp -> Bump.
    coord = nodes.new("ShaderNodeTexCoord")
    coord.location = (-1200, -400)
    mapping = nodes.new("ShaderNodeMapping")
    mapping.location = (-1000, -400)
    mapping.inputs["Rotation"].default_value = (0.5236, 0.0, 0.0)
    mapping.inputs["Scale"].default_value = (38.15, 38.15, 38.15)
    links.new(coord.outputs["Generated"], mapping.inputs["Vector"])

    gabor = nodes.new("ShaderNodeTexGabor")
    gabor.location = (-800, -400)
    # Orientation is a 3D vector in 3D mode but a single angle in 2D mode, so
    # the mode has to be set before the value or the assignment type-errors.
    if hasattr(gabor, "gabor_type"):
        gabor.gabor_type = '3D'
    gabor.inputs["Scale"].default_value = 4.9
    gabor.inputs["Frequency"].default_value = 2.0
    gabor.inputs["Anisotropy"].default_value = 1.0
    orientation = gabor.inputs["Orientation"]
    try:
        orientation.default_value = (1.4142, 1.4142, 0.0)
    except TypeError:
        # 2D Gabor: the equivalent of that vector is its angle in the XY plane.
        orientation.default_value = math.radians(45.0)
    links.new(mapping.outputs["Vector"], gabor.inputs["Vector"])

    ramp = nodes.new("ShaderNodeValToRGB")
    ramp.location = (-600, -400)
    ramp.color_ramp.elements[0].position = 0.3318
    ramp.color_ramp.elements[0].color = (0.0, 0.0, 0.0, 1.0)
    ramp.color_ramp.elements[1].position = 0.6045
    ramp.color_ramp.elements[1].color = (1.0, 1.0, 1.0, 1.0)
    links.new(gabor.outputs["Value"], ramp.inputs["Fac"])

    bump = nodes.new("ShaderNodeBump")
    bump.location = (-400, -400)
    bump.inputs["Strength"].default_value = 1.0
    bump.inputs["Distance"].default_value = 0.003
    links.new(ramp.outputs["Color"], bump.inputs["Height"])
    links.new(bump.outputs["Normal"], bsdf.inputs["Normal"])

    glass = nodes.new("ShaderNodeBsdfGlass")
    glass.location = (0, -250)
    glass.inputs["Color"].default_value = (0.2281, 0.3547, 0.5, 1.0)
    glass.inputs["Roughness"].default_value = 0.3729
    glass.inputs["IOR"].default_value = 1.5

    mix_glass = nodes.new("ShaderNodeMixShader")
    mix_glass.location = (250, -100)
    mix_glass.inputs["Fac"].default_value = 0.6
    links.new(bsdf.outputs["BSDF"], mix_glass.inputs[1])
    links.new(glass.outputs["BSDF"], mix_glass.inputs[2])

    # Without this second mix, stacked water columns accumulate to opaque.
    transparent = nodes.new("ShaderNodeBsdfTransparent")
    transparent.location = (250, -350)
    mix_clear = nodes.new("ShaderNodeMixShader")
    mix_clear.location = (450, -100)
    mix_clear.inputs["Fac"].default_value = 0.15
    links.new(mix_glass.outputs["Shader"], mix_clear.inputs[1])
    links.new(transparent.outputs["BSDF"], mix_clear.inputs[2])
    links.new(mix_clear.outputs["Shader"], output.inputs["Surface"])
    return True


def apply_authored_shaders():
    """Apply the authored leaf and water looks to every material that needs one.

    Returns `(leaves_done, water_done)`.
    """
    leaves = water = 0
    for mat in bpy.data.materials:
        base = mat.name.split(".")[0].lower()
        if base.startswith("water"):
            # Rebuilding an already-converted material would stack duplicate
            # node chains on every re-import.
            if any(n.type == 'BSDF_GLASS' for n in (mat.node_tree.nodes if mat.use_nodes and mat.node_tree else [])):
                continue
            water += 1 if apply_water_shading(mat) else 0
        elif base.endswith(LEAF_MATERIAL_SUFFIXES):
            leaves += 1 if apply_leaf_shading(mat) else 0
    return leaves, water


def neutralise_mcprep_tint():
    """Stop MCprep's tint node from multiplying every texture toward black.

    `prep_materials` inserts a MULTIPLY mix node ("Add Color") between the
    diffuse texture and Base Color, meant to carry a biome tint -- but leaves
    its colour input at Blender's default for an unset colour socket, 0.5
    grey, with the factor at 1.0. Multiplying by mid grey halves every
    texture, on every block of the import, which reads as a scene that is
    simply too dark rather than as one material being wrong.

    Our exporter bakes biome tint into the atlas swatches already, so the
    node has nothing to contribute: white makes the multiply an identity.
    Only the unset default is replaced -- a linked input, or any colour the
    user or MCprep deliberately set, is left alone.

    Returns the number of tint sockets corrected.
    """
    # Blender's default for an unset colour socket, and so the signature of a
    # tint nobody filled in.
    UNSET = 0.5
    fixed = 0
    for mat in bpy.data.materials:
        if not mat.use_nodes or not mat.node_tree:
            continue
        for node in mat.node_tree.nodes:
            if node.bl_idname not in ("ShaderNodeMix", "ShaderNodeMixRGB"):
                continue
            if getattr(node, "blend_type", None) != 'MULTIPLY':
                continue
            for socket in node.inputs:
                # `ShaderNodeMix` carries one A/B pair per data type and only
                # the pair matching `data_type` is live, so match on the
                # socket type rather than the name. The texture arrives on a
                # link; the tint is the unlinked one.
                if socket.type != 'RGBA' or socket.is_linked:
                    continue
                value = socket.default_value
                if all(abs(value[i] - UNSET) < 0.01 for i in range(3)):
                    socket.default_value = (1.0, 1.0, 1.0, 1.0)
                    fixed += 1
    return fixed


def set_pixelated_filtering():
    """Force nearest-neighbour sampling on every image texture in the file.

    Minecraft textures are 16x16; Blender's default Linear interpolation
    blends neighbouring texels and turns block faces into smeared mush,
    which is the single most obvious way an import stops looking like the
    game. This runs over `bpy.data` rather than a selection, and last, on
    purpose: MCprep's `prep_materials` rebuilds each material's node graph
    from scratch, so interpolation set before it runs is silently discarded.

    Returns the number of texture nodes changed.
    """
    changed = 0
    for mat in bpy.data.materials:
        if not mat.use_nodes or not mat.node_tree:
            continue
        for node in mat.node_tree.nodes:
            if node.type != 'TEX_IMAGE':
                continue
            if node.interpolation != 'Closest':
                node.interpolation = 'Closest'
                changed += 1
    # Node groups (MCprep builds some of its shading inside them) hold their
    # own texture nodes, which the material loop above never reaches.
    for group in bpy.data.node_groups:
        for node in group.nodes:
            if node.type == 'TEX_IMAGE' and node.interpolation != 'Closest':
                node.interpolation = 'Closest'
                changed += 1
    return changed

MESHSWAP_ALIASES = {
    "grass": "short_grass",
    "tall_grass": "tall_grass_bottom",
    "large_fern": "fern",
    "sunflower": "sunflower_bottom",
    "cactus": "cactus_side",
    "wheat": "wheat_stage7",
    "carrots": "carrots_stage3",
    "potatoes": "potatoes_stage3",
    "cobweb": "cobweb",
    "dead_bush": "dead_bush",
    "brown_mushroom": "brown_mushroom",
    "red_mushroom": "red_mushroom",
    "sugar_cane": "sugar_cane",
    "lily_pad": "lily_pad",
    "ladder": "ladder",
    "rail": "rail",
    "powered_rail": "powered_rail",
    "vine": "vine",
    "torch": "torch",
    "wall_torch": "torch",
    "redstone_torch": "redstone_torch",
    "chest": "chest",
    "trapped_chest": "chest",
    "glowstone": "glowstone",
    "sea_lantern": "sea_lantern",
    "lantern": "lantern",
    "shroomlight": "shroomlight",
    "spawner": "spawner",
    "bookshelf": "bookshelf",
    "crafting_table": "crafting_table_top",
    "enchanting_table": "enchanting_table_top",
    "furnace": "furnace_front",
    "jack_o_lantern": "jack_o_lantern",
    "carved_pumpkin": "carved_pumpkin",
    "redstone_lamp": "redstone_lamp",
    "fire": "fire",
    "soul_fire": "soul_fire",
    "soul_torch": "soul_torch",
    "soul_lantern": "soul_lantern",
}


def _meshswap_blend_path():
    """Absolute path to MCprep's meshswap asset library, or None."""
    try:
        prefs = bpy.context.preferences.addons.get("MCprep_addon")
        if prefs is not None:
            path = bpy.path.abspath(getattr(bpy.context.scene, "meshswap_path", "") or "")
            if path and os.path.isfile(path):
                return path
        import addon_utils
        for mod in addon_utils.modules():
            if mod.__name__ == "MCprep_addon":
                candidate = os.path.join(
                    os.path.dirname(mod.__file__),
                    "MCprep_resources",
                    "mcprep_meshSwap.blend",
                )
                if os.path.isfile(candidate):
                    return candidate
    except Exception:
        pass
    return None


def _meshswap_contents(blend_path):
    """(collections, objects) available in the meshswap library."""
    with bpy.data.libraries.load(blend_path, link=False) as (src, _dst):
        return set(src.collections), set(src.objects)


def _append_meshswap_asset(blend_path, name, is_collection):
    """Append one asset by name and return the datablock (or None).

    Identifies the result by diffing the datablock list rather than looking it
    up by name afterwards. The OBJ import names its objects after block types
    (`short_grass`, `dandelion`, `vine`, ...), which collides with the asset
    names in the meshswap library — Blender then renames the incoming asset to
    `short_grass.001`, and a name lookup silently returns the OBJ's own mesh
    instead of the asset just appended.
    """
    store = bpy.data.collections if is_collection else bpy.data.objects
    before = set(store.keys())
    with bpy.data.libraries.load(blend_path, link=False) as (src, dst):
        available = src.collections if is_collection else src.objects
        if name not in available:
            return None
        if is_collection:
            dst.collections = [name]
        else:
            dst.objects = [name]
    added = [key for key in store.keys() if key not in before]
    if not added:
        # Already present from an earlier import; reuse it.
        existing = store.get(name)
        if is_collection:
            _unlink_collection_from_scenes(existing)
        return existing
    # Prefer the block that actually came from this append.
    chosen = None
    for key in added:
        if key == name or key.startswith(f"{name}."):
            chosen = store[key]
            break
    if chosen is None:
        chosen = store[added[0]]

    # Appending one object drags its dependencies in with it: MCprep's torch
    # brings flame and smoke helpers (named with a `noImport` suffix, plus
    # `*.flame` / `*.smoke` particle sources). Blender links those into the
    # scene, where they render as stray torches whose animation-strip textures
    # are mapped whole -- a column of garbled colour. Only the asset we asked
    # for should be visible; the helpers stay as data for it to reference.
    if not is_collection:
        for key in added:
            extra = store.get(key)
            if extra is None or extra is chosen or not hasattr(extra, "users_collection"):
                continue
            for coll in list(extra.users_collection):
                coll.objects.unlink(extra)
            extra.use_fake_user = True
    else:
        _unlink_collection_from_scenes(chosen)
        _centre_collection_for_instancing(chosen)

    return chosen


def _centre_collection_for_instancing(collection):
    """Move a collection's instancing origin onto its own contents.

    MCprep's library assets are laid out on a display grid inside the blend, so
    a collection's meshes sit at arbitrary offsets from its origin -- the soul
    lantern's parts are at (-2.5, 5.5, 0.5). Instancing preserves that, so
    every lantern appeared displaced from the block it belongs to rather than
    on it, which reads as the asset floating away from its fence post.

    `instance_offset` is the collection's own answer to this: it defines the
    point that lands on the instance position. Setting it to the centre of the
    mesh contents puts the asset where the block is. Lights and other
    non-geometry are ignored on purpose -- an emitter parked away from the
    model would drag the centre off the thing you can actually see.
    """
    meshes = [ob for ob in collection.all_objects if ob.type == 'MESH']
    if not meshes:
        return
    xs = [ob.location.x for ob in meshes]
    ys = [ob.location.y for ob in meshes]
    # Z uses the minimum, not the mean: a block sits *on* its position, so the
    # bottom of the asset is what should meet it. Averaging would half-bury a
    # tall asset like a door or a hanging lantern.
    zs = [ob.location.z for ob in meshes]
    collection.instance_offset = (
        sum(xs) / len(xs),
        sum(ys) / len(ys),
        min(zs),
    )


def _unlink_collection_from_scenes(asset):
    """Take an appended asset collection out of every scene, keeping the data.

    Appending a *collection* links it into the scene, so its objects render
    where the meshswap library authored them -- next to nothing, in the middle
    of the world. The instancer only ever needs the datablock, so the visible
    copy is pure surplus: every torch and lantern shows up as its real
    instances *plus* the stray library copy sitting off on its own, which is
    what a torch appearing three times where one should be actually is. Object
    assets were already handled this way; collections were not.
    """
    if asset is None or not hasattr(asset, "children"):
        return
    for scene in bpy.data.scenes:
        if asset.name in scene.collection.children:
            scene.collection.children.unlink(asset)
    for parent in bpy.data.collections:
        if parent is asset:
            continue
        if asset.name in parent.children:
            parent.children.unlink(asset)
    asset.use_fake_user = True


def _build_instancer_node_group(name, asset, is_collection):
    """Geometry node group: instance `asset` on every point of the input mesh.

    Instancing rather than duplicating real objects is what makes this scale —
    a selection can easily hold six figures of plants, and one instanced point
    cloud per block type stays cheap where that many separate objects would
    not.
    """
    group = bpy.data.node_groups.new(name, "GeometryNodeTree")
    group.interface.new_socket("Geometry", in_out='INPUT', socket_type='NodeSocketGeometry')
    group.interface.new_socket("Geometry", in_out='OUTPUT', socket_type='NodeSocketGeometry')

    nodes, links = group.nodes, group.links
    n_in = nodes.new("NodeGroupInput")
    n_in.location = (-400, 0)
    n_out = nodes.new("NodeGroupOutput")
    n_out.location = (400, 0)
    iop = nodes.new("GeometryNodeInstanceOnPoints")
    iop.location = (100, 0)

    if is_collection:
        info = nodes.new("GeometryNodeCollectionInfo")
        info.location = (-200, -150)
        info.inputs["Collection"].default_value = asset
        # Keep the collection's internal layout; pick one child at random only
        # if the library offers variants (torches do).
        if "Separate Children" in info.inputs:
            info.inputs["Separate Children"].default_value = False
        if "Reset Children" in info.inputs:
            info.inputs["Reset Children"].default_value = True
    else:
        info = nodes.new("GeometryNodeObjectInfo")
        info.location = (-200, -150)
        info.inputs["Object"].default_value = asset
        if "As Instance" in info.inputs:
            info.inputs["As Instance"].default_value = True

    # Collection Info outputs "Instances"; Object Info outputs "Geometry".
    source = info.outputs.get("Geometry") or info.outputs.get("Instances")
    links.new(n_in.outputs[0], iop.inputs["Points"])
    links.new(source, iop.inputs["Instance"])
    links.new(iop.outputs["Instances"], n_out.inputs[0])
    return group


def _load_prototype(prototypes_dir, stem, block_name=None):
    """Import `prototypes/<stem>.obj` and return it as an instancing source.

    The exporter writes one of these per distinct block *state*: that state's
    true vanilla geometry, textured from named PNGs taken straight out of the
    player's client JAR. Instancing it beats drawing the block from the shared
    atlas — nothing is shared, so no neighbouring tile can bleed along an edge,
    and a texture is found by name rather than by position in a table that can
    drift out of step with the atlas image.

    `stem` carries the block state (`oak_fence__east-true_north-true`), so a
    fence joined north-south and one joined east-west load as different meshes.
    `block_name` is the plain block id, used for rules keyed by block type
    rather than by state; it defaults to the stem for stateless blocks.
    """
    if block_name is None:
        block_name = stem
    path = os.path.join(prototypes_dir, f"{stem}.obj")
    if not os.path.isfile(path):
        return None
    before = set(bpy.data.objects.keys())
    try:
        # Import the raw file and rotate it here rather than asking the
        # importer to convert axes. The up_axis/forward_axis arguments are
        # honoured for the world OBJ but silently ignored on this call, which
        # left every prototype lying on its side: Minecraft's top and bottom
        # faces (constant Y) came in as Blender side faces, and its north and
        # south faces pointed up and down. Doing the conversion explicitly
        # cannot be ignored.
        bpy.ops.wm.obj_import(filepath=path, forward_axis='Y', up_axis='Z')
    except Exception:
        return None
    added = [k for k in bpy.data.objects.keys() if k not in before]
    if not added:
        return None

    parts = [bpy.data.objects[k] for k in added]
    # A block whose faces use several textures imports as several objects;
    # join them so one instance carries the whole block.
    proto = parts[0]
    if len(parts) > 1:
        bpy.ops.object.select_all(action='DESELECT')
        for part in parts:
            part.select_set(True)
        bpy.context.view_layer.objects.active = proto
        try:
            bpy.ops.object.join()
        except Exception:
            pass
    # Minecraft Y-up -> Blender Z-up: (x, y, z) -> (x, -z, y), which is a
    # +90 degree turn about X. Applied to the mesh so the instancer sees an
    # already-upright block and needs no per-instance rotation.
    proto.rotation_euler = (math.radians(90.0), 0.0, 0.0)
    bpy.context.view_layer.objects.active = proto
    try:
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=False)
    except Exception:
        pass

    proto.name = f"{PROTOTYPE_PREFIX}{stem}"
    if block_name in NO_SHADOW_BLOCKS:
        proto.visible_shadow = False
    # Source only — it must not render on its own.
    for coll in list(proto.users_collection):
        coll.objects.unlink(proto)
    proto.use_fake_user = True
    return proto


def instance_blocks_from_manifest(context, manifest_path, report=None, grass_tufts=False):
    """Place MCprep 3D assets at every position the manifest lists.

    Returns (placed_counts, skipped_names).
    """
    blend_path = _meshswap_blend_path()
    if not blend_path:
        if report:
            report({'WARNING'}, "MCprep meshswap library not found — skipping block instancing")
        return {}, []

    with open(manifest_path, encoding="utf-8") as handle:
        manifest = json.load(handle)

    aliases = dict(MESHSWAP_ALIASES)
    if grass_tufts:
        # Opt-in: scatter MCprep's grass tuft over every grass block. Vanilla
        # only grows grass on *some* blocks, so applying it to all of them
        # reads as much denser than the game does.
        aliases["grass_block"] = "grass"

    collections, objects = _meshswap_contents(blend_path)
    root = bpy.data.collections.get("Bedrock Instances") or bpy.data.collections.new(
        "Bedrock Instances"
    )
    if root.name not in context.scene.collection.children:
        context.scene.collection.children.link(root)

    # Prototypes belonging to *this* export, named after it exactly as the
    # manifest is. A single shared "prototypes" folder holds whatever the last
    # export wrote, so importing any earlier one finds only the block states
    # that later export happened to need -- and every state it lacks falls
    # back silently to the OBJ's atlas cube. The legacy shared folder is still
    # accepted so exports made before this change keep working.
    prototypes_dir = os.path.splitext(manifest_path)[0] + ".prototypes"
    if prototypes_dir.endswith(".blocks.prototypes"):
        prototypes_dir = prototypes_dir[: -len(".blocks.prototypes")] + ".prototypes"
    if not os.path.isdir(prototypes_dir):
        legacy = os.path.join(os.path.dirname(manifest_path), "prototypes")
        if os.path.isdir(legacy):
            prototypes_dir = legacy
            if report:
                report(
                    {'WARNING'},
                    "Using the shared prototypes folder: it may belong to a "
                    "different export, so some blocks can fall back to plain "
                    "cubes. Re-export to get prototypes named for this file.",
                )
    placed, skipped, failed, from_prototype = {}, [], [], []
    for block_name, variants in manifest.get("blocks", {}).items():
      # One asset that won't load must not cost every later block its swap.
      try:
            asset_name = aliases.get(block_name, block_name)
            is_collection = asset_name in collections
            use_prototype = not is_collection and asset_name not in objects
            if use_prototype and not os.path.isdir(prototypes_dir):
                skipped.append(block_name)
                continue

            # A library asset is chosen by block *name*, but some blocks change
            # shape with their state in ways the library models as separate
            # assets: a hanging lantern carries a chain, a standing one does
            # not. Vanilla expresses that as `hanging=true`, and MCprep ships
            # `lantern_hanging` beside `lantern`. Without this, every hanging
            # lantern got the standing model -- no chain, and floating below
            # whatever it should have hung from.
            #
            # Where the library has no such variant (there is no
            # `soul_lantern_hanging`), the name simply will not resolve and the
            # block falls through to its prototype, which is built from the
            # vanilla model and so has the chain anyway. That fallback is why
            # this needs no list of which variants exist.
            def resolve_for(properties):
                name = aliases.get(block_name, block_name)
                if properties.get("hanging") == "true":
                    hanging = f"{name}_hanging"
                    if hanging in collections or hanging in objects:
                        name = hanging
                    else:
                        # The library models this block standing only -- MCprep
                        # ships `lantern_hanging` but no `soul_lantern_hanging`.
                        # Using the standing asset for a hanging block gives a
                        # lantern with no chain, floating under whatever it
                        # should be attached to. The prototype is built from the
                        # vanilla model for this exact state, so it has the
                        # chain: correct shape beats a higher-fidelity asset of
                        # the wrong shape.
                        return name, False, True
                coll = name in collections
                return name, coll, (not coll and name not in objects)

            # Two-tall plants (tall_grass, peony, lilac, sunflower) occupy two
            # blocks but a *library asset* models the whole plant in one piece,
            # so placing it at both halves stacks two copies. Keep the lower
            # half only -- for library assets.
            #
            # A prototype is the opposite case: it is built per block state, so
            # the upper half of a door or a tall plant is a genuinely different
            # mesh holding the top of that object. Dropping it leaves every
            # door as its bottom half and every two-tall plant beheaded. The
            # skip must therefore apply to library assets alone.
            #
            # Keying by state also keeps distinct shapes apart: a fence joined
            # north-south and one joined east-west are not the same mesh, and
            # merging them renders every fence in the world identically. The
            # exporter names each variant's mesh in `prototype`. MCprep assets
            # have no per-state variants, so they stay merged under one key.
            shapes = {}
            resolutions = {}
            for variant in variants:
                props = variant.get("properties", {})
                v_asset, v_is_coll, v_proto = resolve_for(props)
                if not v_proto and props.get("half") == "upper":
                    continue
                key = variant.get("prototype", block_name) if v_proto else v_asset
                shapes.setdefault(key, []).append(variant)
                resolutions[key] = (v_asset, v_is_coll, v_proto)

            # Resolve the OBJ's own object for this block type *before*
            # appending: the asset may share its name, after which a lookup is
            # ambiguous. Removed once, not per shape.
            obj_geometry = bpy.data.objects.get(block_name)

            # An asset only augments the block when it is offset away from it
            # *and* is not a prototype — a prototype always stands in for the
            # block itself.
            augments_block = (
                block_name in MESHSWAP_AUGMENTS_ONLY
                and not use_prototype
                and MESHSWAP_OFFSETS.get(block_name, (0.0, 0.0, 0.0)) != (0.0, 0.0, 0.0)
            )

            total_placed = 0
            for shape_key, shape_variants in sorted(shapes.items()):
                asset_name, is_collection, use_prototype = resolutions[shape_key]
                # The offset exists to sit an augmenting asset on top of its
                # block -- a grass tuft above a grass block. A prototype *is*
                # the block, so lifting it leaves the terrain floating a block
                # too high, with a gap where each block should have been.
                if use_prototype:
                    ox, oy, oz = 0.0, 0.0, 0.0
                else:
                    ox, oy, oz = MESHSWAP_OFFSETS.get(block_name, (0.0, 0.0, 0.0))

                coords = []
                for variant in shape_variants:
                    for x, y, z in variant["positions"]:
                        # Manifest is Minecraft-space (Y-up), matching the OBJ's
                        # own vertices; the OBJ comes in with up_axis='Y',
                        # forward_axis='NEGATIVE_Z', i.e. (x, y, z) -> (x, -z, y).
                        coords.append((x + ox, -z + oy, y + oz))
                if not coords:
                    continue

                if use_prototype:
                    asset = _load_prototype(prototypes_dir, shape_key, block_name)
                    if asset is None:
                        skipped.append(shape_key)
                        continue
                    from_prototype.append(shape_key)
                else:
                    asset = _append_meshswap_asset(blend_path, asset_name, is_collection)
                if asset is None:
                    skipped.append(shape_key)
                    continue
                # The asset is only a source for instances — it must not render
                # in its own right, so keep it out of the scene's collections.
                if not is_collection:
                    for coll in list(getattr(asset, "users_collection", []) or []):
                        coll.objects.unlink(asset)
                    asset.use_fake_user = True

                mesh = bpy.data.meshes.new(f"PB_points_{shape_key}")
                mesh.from_pydata(coords, [], [])
                mesh.update()
                holder = bpy.data.objects.new(f"PB_{shape_key}", mesh)
                root.objects.link(holder)

                group = _build_instancer_node_group(
                    f"PB_Instancer_{shape_key}", asset, is_collection
                )
                modifier = holder.modifiers.new("PB_Instancer", 'NODES')
                modifier.node_group = group
                total_placed += len(coords)

            if not total_placed:
                continue

            # The OBJ already contains geometry for this block type; leaving it
            # in place would z-fight with the assets just placed — unless they
            # only *augment* the block (a grass tuft on top of a grass block),
            # in which case the block's own geometry must stay.
            if (
                obj_geometry is not None
                and obj_geometry.name in bpy.data.objects
                and not augments_block
            ):
                bpy.data.objects.remove(obj_geometry, do_unlink=True)

            placed[block_name] = total_placed
      except Exception as exc:
            failed.append(f"{block_name} ({exc})")

    if from_prototype:
        print(
            f"  {len(from_prototype)} block type(s) used exporter prototypes "
            f"(real geometry + JAR textures, no atlas): "
            + ", ".join(sorted(from_prototype))
        )
    if failed:
        print("  Asset placement failed for: " + "; ".join(failed))
    return placed, skipped

# Swappable block types supported by MCprep 3D library (vegetation, 3D items, containers)
SWAPPABLE_BLOCKS = {
    "dandelion", "poppy", "blue_orchid", "allium", "azure_bluet",
    "red_tulip", "orange_tulip", "white_tulip", "pink_tulip", "oxeye_daisy",
    "cornflower", "lily_of_the_valley", "sunflower", "lilac", "rose_bush",
    "peony", "wheat", "carrots", "potatoes", "beetroots", "torch", "soul_torch",
    "redstone_torch", "lantern", "soul_lantern", "chest", "trapped_chest",
    "ender_chest", "crafting_table", "furnace", "blast_furnace", "smoker",
}

# Biome tint (grass/leaves/ferns green) is baked directly into the exported
# atlas per-swatch by the Rust exporter (mineways.rs: tint_biome_swatches),
# not applied here. A material-level tint in Blender can't distinguish "this
# face's texture is grayscale and needs tinting" from "this face's texture
# (e.g. grass_block_side) is already fully coloured" when both faces share
# one material — tinting the whole material darkens the already-correct one.

# Materials needing alpha cutout transparency.
ALPHA_MATS = {
    "oak_leaves", "jungle_leaves", "acacia_leaves", "dark_oak_leaves",
    "mangrove_leaves", "birch_leaves", "spruce_leaves", "short_grass",
    "tall_grass", "fern", "vine", "lily_pad", "sugar_cane", "spawner",
    "glass", "tinted_glass", "seagrass", "tall_seagrass", "dandelion",
    "poppy", "blue_orchid", "allium", "azure_bluet", "cornflower",
    "oxeye_daisy", "peony", "pointed_dripstone", "glow_lichen",
}

# ---------------------------------------------------------------------------
# Import Operator
# ---------------------------------------------------------------------------

class IMPORT_OT_project_bedrock(Operator, ImportHelper):
    """Import a Project Bedrock OBJ export with materials, MCprep integration, and organisation"""
    bl_idname = "import_scene.project_bedrock"
    bl_label = "Import Project Bedrock Export"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".obj"

    filter_glob: StringProperty(
        default="*.obj;*.glb;*.gltf",
        options={'HIDDEN'},
    )

    use_pbr: BoolProperty(
        name="Apply PBR Materials",
        description="Apply PBR material presets (roughness, metallic, emissive)",
        default=True,
    )

    def prep_prototype_materials(self, context):
        """Run MCprep's material prep over the prototype meshes.

        The prototypes are the instanced sources, so treating them once fixes
        every placement of that block type.
        """
        if not hasattr(bpy.ops, 'mcprep') or not hasattr(bpy.ops.mcprep, 'prep_materials'):
            return 0
        targets = [
            ob for ob in bpy.data.objects
            if ob.name.startswith(PROTOTYPE_PREFIX) and ob.type == 'MESH' and ob.data.materials
        ]
        if not targets:
            return 0

        # Prototypes are instance sources, deliberately unlinked from every
        # collection so they do not render on their own. An object outside the
        # view layer cannot be selected, and prep_materials works on the
        # selection -- so link them for the duration and put them back after.
        scene_coll = context.scene.collection
        linked = []
        for ob in targets:
            if ob.name not in scene_coll.objects:
                scene_coll.objects.link(ob)
                linked.append(ob)
        try:
            bpy.ops.object.select_all(action='DESELECT')
            for ob in targets:
                ob.select_set(True)
            context.view_layer.objects.active = targets[0]
            bpy.ops.mcprep.prep_materials('EXEC_DEFAULT')
        except Exception as e:
            self.report({'WARNING'}, f"MCprep prep_materials (prototypes) warning: {e}")
            return 0
        finally:
            for ob in linked:
                scene_coll.objects.unlink(ob)
        return len(targets)

    use_mcprep_materials: BoolProperty(
        name="Use MCprep Prep Materials",
        description="Automatically run MCprep material prep on imported objects if MCprep addon is active",
        default=True,
    )

    use_mcprep_meshswap: BoolProperty(
        name="Use MCprep MeshSwap",
        description="Automatically swap vegetation, torches, and 3D blocks with MCprep models if MCprep addon is active",
        default=True,
    )

    use_block_manifest: BoolProperty(
        name="Place MCprep Assets from Manifest",
        description=(
            "Read the exporter's blocks.json and instance a real MCprep 3D "
            "asset at every recorded block position, replacing that block "
            "type's flat/cube geometry from the OBJ"
        ),
        default=True,
    )

    grass_tufts: BoolProperty(
        name="Grass Tufts on Grass Blocks",
        description=(
            "Scatter MCprep's 3D grass tuft on top of every grass block. "
            "MCprep has no grass_block model of its own, so the block keeps "
            "its exported geometry and the tuft is added above it. Off by "
            "default: vanilla only grows grass on some blocks, so covering "
            "all of them looks considerably denser than the game"
        ),
        default=False,
    )

    add_mc_sky: BoolProperty(
        name="Add MCprep Sky",
        description=(
            "Run MCprep's Create MC Sky after importing: a Minecraft sky "
            "world, sun/moon, and clouds. Skipped silently if MCprep is not "
            "installed"
        ),
        default=True,
    )

    organise_collections: BoolProperty(
        name="Organise into Collections",
        description="Organise imported objects into collections by chunk and block type",
        default=True,
    )

    collection_scheme: EnumProperty(
        name="Collection Scheme",
        description="How to organise objects into collections",
        items=[
            ('CHUNK_THEN_TYPE', 'Chunk > Block Type', 'Group by chunk, then block type'),
            ('BY_CHUNK', 'By Chunk', 'One collection per chunk'),
            ('BY_TYPE', 'By Block Type', 'One collection per block type'),
            ('FLAT', 'Flat', 'All objects in one collection'),
        ],
        default='CHUNK_THEN_TYPE',
    )

    auto_detect_atlas: BoolProperty(
        name="Auto-detect Atlas",
        description="Automatically find and assign the texture atlas PNG",
        default=True,
    )

    def execute(self, context):
        import time
        t_start = time.time()
        wm = context.window_manager
        wm.progress_begin(0, 100)

        wm.progress_update(10)
        t0 = time.time()
        result = self.import_obj(context)
        t_import = (time.time() - t0) * 1000.0
        if result != {'FINISHED'}:
            wm.progress_end()
            return result

        self.deduplicate_materials(context)

        imported_objs = [obj for obj in context.selected_objects if obj.type == 'MESH']
        if not imported_objs:
            imported_objs = [obj for obj in bpy.data.objects if obj.type == 'MESH']

        # 1. Apply PBR & Atlas texturing FIRST so materials have texture nodes for MCprep
        wm.progress_update(30)
        t0 = time.time()
        if self.use_pbr:
            self.apply_pbr_materials(context)
        t_pbr = (time.time() - t0) * 1000.0

        # 2. Fast O(1) collection organization
        wm.progress_update(50)
        t0 = time.time()
        if self.organise_collections:
            self.organise_objects(context)
        t_collections = (time.time() - t0) * 1000.0

        # 3. Configure MCprep exporter setting & run MCprep operators non-interactively ('EXEC_DEFAULT')
        wm.progress_update(70)
        t_mcprep_materials = 0.0
        t_mcprep_meshswap = 0.0
        if hasattr(bpy.ops, 'mcprep'):
            try:
                if 'MCprep_addon' in bpy.context.preferences.addons:
                    bpy.context.preferences.addons['MCprep_addon'].preferences.MCprep_exporter_type = 'Mineways'
            except Exception:
                pass

            if self.use_mcprep_materials and hasattr(bpy.ops.mcprep, 'prep_materials'):
                t0 = time.time()
                try:
                    bpy.ops.mcprep.prep_materials('EXEC_DEFAULT')
                except Exception as e:
                    self.report({'WARNING'}, f"MCprep prep_materials warning: {e}")
                t_mcprep_materials = (time.time() - t0) * 1000.0

            wm.progress_update(90)
            # MCprep's own meshswap operator is deliberately not run.
            #
            # It swaps whole OBJ objects for library assets, which is the same
            # job the manifest instancer does in step 5 -- but the instancer
            # does it better, because the manifest gives it an exact position
            # and block state per block, where meshswap can only infer from a
            # merged mesh. Running both placed every swappable block twice,
            # which is why a single lantern or torch in the save appeared as
            # two or three in Blender.

        # 4. Water colour/transmission override, applied AFTER MCprep so it
        # survives — MCprep's own prep_materials rebuilds each material's
        # node graph from scratch, discarding anything wired in step 1.
        # (Biome tint itself is baked into the exported atlas per-swatch by
        # the Rust exporter, so it doesn't need a post-MCprep pass here.)
        t0 = time.time()
        self.apply_water_appearance(context)
        t_tint = (time.time() - t0) * 1000.0

        # 5. Place real MCprep 3D assets from the exporter's manifest. Runs
        # last so it can delete the OBJ geometry for any block type it takes
        # over, without earlier passes tripping over the missing objects.
        t0 = time.time()
        t_instancing = 0.0
        instanced = {}
        if self.use_block_manifest:
            # Only the manifest belonging to *this* OBJ. A shared
            # "blocks.json" in the output folder gets silently paired with
            # whichever export ran last, and a manifest from a different
            # region places every asset at coordinates from another part of
            # the world — plants and chests scattered through open air.
            manifest_path = os.path.splitext(self.filepath)[0] + ".blocks.json"
            if not os.path.isfile(manifest_path):
                legacy = os.path.join(os.path.dirname(self.filepath), "blocks.json")
                if os.path.isfile(legacy):
                    self.report(
                        {'WARNING'},
                        "Ignoring blocks.json: it is not named for this export and may "
                        "describe a different region. Re-export to place 3D assets.",
                    )
            if os.path.isfile(manifest_path):
                try:
                    instanced, skipped = instance_blocks_from_manifest(
                        context, manifest_path, self.report, self.grass_tufts
                    )
                    if skipped:
                        print(
                            "  No MCprep asset for: " + ", ".join(sorted(skipped))
                        )
                except Exception as e:
                    self.report({'WARNING'}, f"Block instancing failed: {e}")
            t_instancing = (time.time() - t0) * 1000.0

        # 6. Give the prototype meshes the same MCprep material treatment the
        # terrain got. Prototypes are loaded in step 5, after prep_materials
        # has already run, so without this pass the block types that use a
        # prototype -- usually most of them -- keep the plain material the OBJ
        # importer built and look untreated next to the MCprep-shaded terrain.
        t0 = time.time()
        if self.use_mcprep_materials:
            self.prep_prototype_materials(context)
        # Nearest-neighbour sampling, applied last and to everything. Setting
        # it earlier does not survive: prep_materials rebuilds each material's
        # node graph from scratch, discarding the interpolation set in step 1.
        # Minecraft art is 16x16 pixel texels; any smoothing turns them to mush.
        # After MCprep and after the prototypes are in, so both the atlas
        # materials and the prototype materials get the authored look.
        shaded_leaves, shaded_water = apply_authored_shaders()
        untinted = neutralise_mcprep_tint()
        pixelated = set_pixelated_filtering()
        # Runs last so it also catches helpers spawned by MCprep's meshswap,
        # not just those pulled in as append dependencies.
        helpers_hidden = hide_meshswap_helpers()
        t_filtering = (time.time() - t0) * 1000.0

        # 7. MCprep's Minecraft sky: world, sun/moon, clouds. Last, so it
        # cannot disturb the geometry passes, and only if MCprep is installed
        # -- the add-on treats MCprep as an optional dependency everywhere else
        # and this is no different.
        t0 = time.time()
        t_sky = 0.0
        if self.add_mc_sky and hasattr(bpy.ops, 'mcprep') and hasattr(bpy.ops.mcprep, 'add_mc_sky'):
            # `world_type` is a *dynamic* enum with no default: the shader-based
            # sky is only offered on Cycles/EEVEE, so asking for it under any
            # other engine raises. Pick the mesh sky there instead.
            shader_engines = {'CYCLES', 'BLENDER_EEVEE', 'BLENDER_EEVEE_NEXT'}
            world_type = (
                'world_shader'
                if context.scene.render.engine in shader_engines
                else 'world_mesh'
            )
            try:
                bpy.ops.mcprep.add_mc_sky(
                    'EXEC_DEFAULT',
                    world_type=world_type,
                    add_clouds=True,
                    remove_existing_suns=True,
                )
            except Exception as e:
                self.report({'WARNING'}, f"MCprep add_mc_sky warning: {e}")
            t_sky = (time.time() - t0) * 1000.0

        wm.progress_update(100)
        wm.progress_end()

        t_total = time.time() - t_start
        summary_msg = (
            f"\n=======================================================\n"
            f" Project Bedrock Import Complete in {t_total:.2f}s\n"
            f" -------------------------------------------------------\n"
            f"  - OBJ Import:               {t_import:.1f} ms\n"
            f"  - PBR Setup:                {t_pbr:.1f} ms\n"
            f"  - Collection Organisation:  {t_collections:.1f} ms\n"
            f"  - MCprep Materials:         {t_mcprep_materials:.1f} ms\n"
            f"  - MCprep MeshSwap:          {t_mcprep_meshswap:.1f} ms\n"
            f"  - Water Appearance:         {t_tint:.1f} ms\n"
            f"  - MCprep Asset Placement:   {t_instancing:.1f} ms"
            f" ({sum(instanced.values())} instances across {len(instanced)} block types)\n"
            f"  - Cleanup:                  {t_filtering:.1f} ms"
            f" ({pixelated} texture node(s) set to Closest)\n"
            f"  - MCprep Sky:               {t_sky:.1f} ms\n"
            f"  - Objects Processed:        {len(imported_objs)}\n"
            f"=======================================================\n"
        )
        print(summary_msg)
        self.report({'INFO'}, f"Project Bedrock Import complete in {t_total:.2f}s ({len(imported_objs)} objects)")

        return {'FINISHED'}

    def import_obj(self, context):
        """Import the mesh using Blender's built-in importer for its format.

        Everything the add-on does after this point -- MCprep materials, the
        manifest-driven prototype instancing, nearest-neighbour filtering, the
        leaf and water shading -- works off objects and materials, not off the
        file, so it applies to any format Blender can read.
        """
        res = {'CANCELLED'}
        if self.filepath.lower().endswith(('.glb', '.gltf')):
            return self.import_gltf(context)

        # Modern C++ importer (Blender 4.0+, 5.x)
        if hasattr(bpy.ops.wm, 'obj_import'):
            try:
                res = bpy.ops.wm.obj_import(
                    filepath=self.filepath,
                    forward_axis='NEGATIVE_Z',
                    up_axis='Y',
                    use_split_objects=True,
                    use_split_groups=True
                )
            except Exception:
                try:
                    res = bpy.ops.wm.obj_import(filepath=self.filepath)
                except Exception as e:
                    self.report({'WARNING'}, f"wm.obj_import failed: {e}")

        # Legacy importer (Blender 3.x)
        elif hasattr(bpy.ops, 'import_scene') and hasattr(bpy.ops.import_scene, 'obj'):
            try:
                res = bpy.ops.import_scene.obj(
                    filepath=self.filepath,
                    use_split_groups=True,
                    use_split_objects=True,
                    axis_forward='-Z',
                    axis_up='Y',
                )
            except Exception as e:
                self.report({'ERROR'}, f"import_scene.obj failed: {e}")
                return {'CANCELLED'}

        # Post-import: ensure each object is named by its active material so MCprep recognises all block types
        for obj in context.selected_objects:
            if obj.type == 'MESH' and obj.active_material:
                clean_name = obj.active_material.name.split('.')[0]
                obj.name = clean_name

        return res

    def import_gltf(self, context):
        """Import a .glb/.gltf.

        No axis arguments here on purpose: glTF declares Y-up in its own
        specification and Blender's importer converts to Z-up itself, unlike
        the OBJ importer which has to be told. Passing a conversion as well
        would rotate the scene twice.

        Objects are renamed after their material for the same reason as the
        OBJ path -- MCprep matches block types by name, and a glTF names its
        nodes however the tool that wrote it chose to.
        """
        if not hasattr(bpy.ops.import_scene, 'gltf'):
            self.report({'ERROR'}, "The glTF importer is not enabled in this Blender")
            return {'CANCELLED'}
        try:
            res = bpy.ops.import_scene.gltf(filepath=self.filepath)
        except Exception as e:
            self.report({'ERROR'}, f"import_scene.gltf failed: {e}")
            return {'CANCELLED'}

        for obj in context.selected_objects:
            if obj.type == 'MESH' and obj.active_material:
                obj.name = obj.active_material.name.split('.')[0]
        return res

    def organise_objects(self, context):
        """Move imported objects into organised collections fast."""
        imported = [obj for obj in context.selected_objects if obj.type == 'MESH']
        if not imported:
            imported = [o for o in bpy.data.objects if o.type == 'MESH' and len(o.users_collection) <= 1]

        if not imported:
            return

        root_name = "Bedrock Export"
        root_col = (bpy.data.collections.get(root_name)
                    or bpy.data.collections.new(root_name))

        if root_col.name not in context.scene.collection.children:
            context.scene.collection.children.link(root_col)

        cols_cache = {}

        def get_child(parent, name):
            key = (parent.name, name)
            if key in cols_cache:
                return cols_cache[key]
            child = bpy.data.collections.get(name) or bpy.data.collections.new(name)
            if child.name not in parent.children:
                parent.children.link(child)
            cols_cache[key] = child
            return child

        scheme = self.collection_scheme
        if scheme == 'FLAT':
            for obj in imported:
                for col in list(obj.users_collection):
                    if col != root_col:
                        col.objects.unlink(obj)
                if root_col.name not in [c.name for c in obj.users_collection]:
                    root_col.objects.link(obj)
            return

        groups = {}
        for obj in imported:
            obj_name = obj.name.split('.')[0]
            if scheme == 'BY_CHUNK':
                chunk_name = self._guess_chunk_name(obj)
                target = get_child(root_col, chunk_name)
            elif scheme == 'BY_TYPE':
                type_name = self._sanitise_name(obj_name)
                target = get_child(root_col, f"BlockType_{type_name}")
            else:
                chunk_name = self._guess_chunk_name(obj)
                chunk_col = get_child(root_col, chunk_name)
                type_name = self._sanitise_name(obj_name)
                target = get_child(chunk_col, f"BlockType_{type_name}")

            if target not in groups:
                groups[target] = []
            groups[target].append(obj)

        for target, objs in groups.items():
            for obj in objs:
                for col in list(obj.users_collection):
                    if col != target:
                        col.objects.unlink(obj)
                if obj.name not in target.objects:
                    target.objects.link(obj)

        self.report({'INFO'}, f"Organised {len(imported)} objects into collections")

    def _sanitise_name(self, name: str) -> str:
        """Make a name safe for Blender collection names."""
        return ''.join(c if c.isalnum() or c in '_-' else '_' for c in name)

    def _guess_chunk_name(self, obj) -> str:
        """Fast O(1) chunk coordinate estimation using bounding box center."""
        import math
        try:
            bbox = obj.bound_box
            cx = (bbox[0][0] + bbox[6][0]) * 0.5 + obj.location.x
            cz = (bbox[0][2] + bbox[6][2]) * 0.5 + obj.location.z
        except Exception:
            cx, cz = obj.location.x, obj.location.z

        chunk_x = int(math.floor(cx / 16.0))
        chunk_z = int(math.floor(cz / 16.0))
        return f"Chunk_{chunk_x}_{chunk_z}"

    def _ensure_child(self, parent, name):
        child = bpy.data.collections.get(name)
        if child is None:
            child = bpy.data.collections.new(name)
        if child.name not in parent.children:
            parent.children.link(child)
        return child

    def deduplicate_materials(self, context):
        remap = {}
        base_mats = {}
        for mat in list(bpy.data.materials):
            clean = mat.name.split('.')[0]
            if clean in base_mats:
                remap[mat] = base_mats[clean]
            else:
                base_mats[clean] = mat
                if mat.name != clean and clean not in bpy.data.materials:
                    mat.name = clean

        for obj in bpy.data.objects:
            if obj.type == 'MESH':
                for slot in obj.material_slots:
                    if slot.material in remap:
                        slot.material = remap[slot.material]

        for mat in list(bpy.data.materials):
            if mat.users == 0:
                bpy.data.materials.remove(mat)

    def apply_pbr_materials(self, context):
        atlas_path = None
        if self.auto_detect_atlas:
            atlas_path = self._find_atlas()

        for mat in bpy.data.materials:
            self._apply_pbr_to_material(mat, atlas_path)

    # Alpha cutout is no longer set up here. The exporter's MTL now declares
    # it per material the way Mineways' does (`illum 4` + `map_d`), which
    # Blender's OBJ importer wires natively and *per pixel*. Probing the atlas
    # from Python could only judge a whole material at once, so a block that
    # samples several tiles — a grass block uses top, side, dirt and the side
    # overlay — was called transparent because of the one tile that is, and
    # solid ground ended up with holes through it.

    def apply_water_appearance(self, context):
        """Override the water material's colour/transmission.

        Runs after MCprep for the same reason as apply_biome_tint: MCprep's
        prep_materials rebuilds this material from scratch and would
        otherwise discard an override wired in any earlier step.
        """
        mat = bpy.data.materials.get("water")
        if not mat or not mat.use_nodes or not mat.node_tree:
            return
        principled = mat.node_tree.nodes.get('Principled BSDF')
        if not principled:
            for n in mat.node_tree.nodes:
                if n.type == 'BSDF_PRINCIPLED':
                    principled = n
                    break
        if not principled:
            return

        base_color_input = principled.inputs['Base Color']
        for link in list(base_color_input.links):
            mat.node_tree.links.remove(link)  # a linked socket ignores default_value
        base_color_input.default_value = (0.08, 0.35, 0.75, 1.0)
        if 'Roughness' in principled.inputs:
            principled.inputs['Roughness'].default_value = 0.05
        if 'Transmission Weight' in principled.inputs:
            principled.inputs['Transmission Weight'].default_value = 0.85
        if 'IOR' in principled.inputs:
            principled.inputs['IOR'].default_value = 1.333
        self._set_alpha_render_mode(mat, 'BLENDED')

    def _find_atlas(self):
        obj_dir = os.path.dirname(self.filepath)
        obj_base = os.path.splitext(os.path.basename(self.filepath))[0]

        candidates = [
            os.path.join(obj_dir, f"{obj_base}.atlas.png"),
            os.path.join(obj_dir, f"{obj_base}_atlas.png"),
            os.path.join(obj_dir, "atlas.png"),
            os.path.join(obj_dir, "terrainExt.png"),
        ]
        for path in candidates:
            if os.path.isfile(path):
                return path
        return None

    def _set_alpha_render_mode(self, mat, mode):
        """Set alpha rendering mode across Blender versions.

        Blender 4.2+ controls this via `surface_render_method` ('DITHERED'
        for cutout foliage, 'BLENDED' for glass/water/translucent). On 5.x,
        `blend_method` still exists as a property but no longer affects
        rendering, so it must not be relied on as the primary path.
        """
        if hasattr(mat, 'surface_render_method'):
            try:
                mat.surface_render_method = mode
                return
            except Exception:
                pass
        if hasattr(mat, 'blend_method'):
            try:
                mat.blend_method = 'CLIP' if mode == 'DITHERED' else 'BLEND'
            except Exception:
                pass

    def _apply_pbr_to_material(self, mat, atlas_path):
        if not mat.use_nodes:
            mat.use_nodes = True
        nodes = mat.node_tree.nodes
        links = mat.node_tree.links

        clean_name = mat.name.split('.')[0].lower()

        # Find Principled BSDF node or create one
        principled = nodes.get('Principled BSDF')
        if not principled:
            for n in nodes:
                if n.type == 'BSDF_PRINCIPLED':
                    principled = n
                    break
        if not principled:
            nodes.clear()
            principled = nodes.new('ShaderNodeBsdfPrincipled')
            principled.location = (0, 0)
            output = nodes.new('ShaderNodeOutputMaterial')
            output.location = (300, 0)
            links.new(principled.outputs['BSDF'], output.inputs['Surface'])

        # NOTE: we intentionally do NOT swap in a standalone per-block PNG
        # here (e.g. a "textures/<name>.png" next to the export), even if
        # one exists. The mesh's UVs are baked relative to the shared atlas
        # (a small sub-rectangle per face, e.g. u=[0.3125, 0.375] for one
        # atlas column) — pointing the same UVs at a standalone 16x16 image
        # instead samples a razor-thin sliver of it, stretched across the
        # whole face, which renders as a flat/wrong solid colour. The atlas
        # is the only texture whose UV space actually matches this mesh.

        # Find existing TEX_IMAGE node or reuse/create one
        tex_image = None
        for n in nodes:
            if n.type == 'TEX_IMAGE':
                tex_image = n
                break
        if not tex_image:
            tex_image = nodes.new('ShaderNodeTexImage')
            tex_image.location = (-500, 0)

        tex_image.name = "MCPREP_diffuse"
        tex_image.interpolation = 'Closest'

        if atlas_path and os.path.isfile(atlas_path) and not tex_image.image:
            tex_image.image = bpy.data.images.load(atlas_path, check_existing=True)

        if hasattr(tex_image, 'mnp'):
            try:
                tex_image.mnp.MCPREP_diffuse = True
            except Exception:
                pass
        if tex_image.image:
            try:
                mat["MCPREP_diffuse"] = tex_image.image.name
            except Exception:
                pass

        if principled:
            # Base colour only — biome tinting is applied in a later pass
            # (apply_biome_tint), after MCprep's own material rebuild, since
            # anything wired here gets discarded by bpy.ops.mcprep.prep_materials.
            links.new(tex_image.outputs['Color'], principled.inputs['Base Color'])

            if clean_name in ALPHA_MATS or 'leaf' in clean_name or 'grass' in clean_name or 'flower' in clean_name:
                links.new(tex_image.outputs['Alpha'], principled.inputs['Alpha'])
                self._set_alpha_render_mode(mat, 'DITHERED')

        # Water's colour/transmission override lives in apply_water_appearance,
        # applied after MCprep for the same reason as biome tint (see
        # apply_biome_tint) — MCprep's prep_materials rebuilds this material
        # from scratch and would otherwise discard it.

    def invoke(self, context, event):
        context.window_manager.fileselect_add(self)
        return {'RUNNING_MODAL'}


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------

classes = [
    IMPORT_OT_project_bedrock,
]

def register():
    for cls in classes:
        bpy.utils.register_class(cls)
    bpy.types.TOPBAR_MT_file_import.append(menu_func)

def unregister():
    bpy.types.TOPBAR_MT_file_import.remove(menu_func)
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)

def menu_func(self, context):
    self.layout.operator(
        IMPORT_OT_project_bedrock.bl_idname,
        text="Project Bedrock Export (.obj)",
    )

if __name__ == "__main__":
    register()
