//! Per-block geometry.
//!
//! Blocks whose real shape is a plain cube emit one quad per unoccluded face.
//! Everything else — plants, carpets, clusters, stairs, slabs, fences — emits
//! the boxes from vanilla's own block model instead (see
//! [`crate::block_models`], generated by `tools/gen_block_models.py`).
//!
//! Face culling uses chunkforge-core's appearance-table opacity.

use crate::block_models::{model_for, ModelElement};
use crate::chunk::strip_namespace;
use crate::java_simple::appearance;
use std::collections::HashMap;

/// A filesystem- and identifier-safe key for the block state of one mesh.
///
/// Consumers that build a mesh per block *type* get fences and stairs wrong:
/// a fence's shape depends on which neighbours it connects to and a stair's on
/// `facing`/`half`/`shape`, so a single mesh reused at every position renders
/// one arbitrary form of the block everywhere. Keying meshes by state fixes
/// that, and this is the shared naming both the exporter and the importer use
/// so their files line up.
///
/// Only states the block's model actually reads are included, so variants
/// differing solely by something cosmetic like `waterlogged` collapse onto one
/// mesh rather than duplicating it. Blocks whose geometry is stateless return
/// `None`, keeping their prototype named after the block alone.
pub fn geometry_state_key(
    block_name: &str,
    properties: &HashMap<String, String>,
) -> Option<String> {
    let short = strip_namespace(block_name);
    let model = model_for(short)?;

    // Sorted so the same state always produces the same key, whatever order
    // the properties arrived in.
    let mut relevant: Vec<(&str, &str)> = model
        .variants
        .iter()
        .flat_map(|variant| variant.when.iter())
        .map(|cond| cond.key)
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .filter_map(|key| properties.get(key).map(|value| (key, value.as_str())))
        .collect();
    relevant.sort_unstable();

    if relevant.is_empty() {
        return None;
    }
    Some(
        relevant
            .iter()
            .map(|(key, value)| format!("{key}-{value}"))
            .collect::<Vec<_>>()
            .join("_"),
    )
}

/// Prototype file stem for a block in a given state: `oak_fence__east-true_...`.
pub fn prototype_stem(block_name: &str, properties: &HashMap<String, String>) -> String {
    let short = strip_namespace(block_name);
    match geometry_state_key(block_name, properties) {
        Some(state) => format!("{short}__{state}"),
        None => short.to_owned(),
    }
}

/// One quad face emitted for a block.
#[derive(Debug, Clone)]
pub struct BlockQuad {
    /// 4 corners in world space, CW from outside.
    pub corners: [[f64; 3]; 4],
    /// Face index 0..5 for UV look-up (top/bottom/east/west/south/north).
    pub face_idx: usize,
    /// Normal direction as a face-index offset.
    pub normal: [i32; 3],
    /// Optional override texture name (None = use face-based UV from block).
    pub texture: Option<String>,
    /// The model's own UV rectangle for this face, `[x1, y1, x2, y2]` in
    /// vanilla's 0..16 pixel space with y measured from the top of the image.
    ///
    /// Carried through because it is not always the whole texture, and not
    /// always the right way round: vanilla mirrors a right-hinged door by
    /// reversing this rectangle rather than by moving any geometry. Deriving
    /// UVs from vertex positions alone therefore cannot tell the two hinges
    /// apart, and every door came out with its handle on the same side.
    /// `None` for plain cube faces, which use the whole texture.
    pub uv: Option<[f32; 4]>,
}

/// Get the quads for a block.  All blocks are full cubes; visible faces
/// are determined solely by neighbour opacity (chunkforge-core's table).
pub fn block_quads<'a>(
    wx: i32,
    wy: i32,
    wz: i32,
    block_name: &str,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> Vec<BlockQuad> {
    block_quads_stated(wx, wy, wz, block_name, &HashMap::new(), lookup)
}

/// [`block_quads`], but able to pick the block-state-specific shape.
///
/// Orientation lives in the block state: a stair's `facing`/`half`, a fence's
/// per-side connection flags. Without them every stair in a build points the
/// same way and fences lose their rails, so callers that have the state
/// should pass it.
/// How far to turn a code-drawn block about Y for its `facing`.
///
/// The renderers take the facing from the block state and rotate the model
/// themselves, so the transcribed boxes are all in the default orientation and
/// the turn has to be applied here. Blocks without a facing return 0, which
/// leaves them alone.
fn block_entity_rotation(properties: &HashMap<String, String>) -> f32 {
    match properties.get("facing").map(String::as_str) {
        Some("south") => 180.0,
        Some("west") => 270.0,
        Some("east") => 90.0,
        _ => 0.0,
    }
}

pub fn block_quads_stated<'a>(
    wx: i32,
    wy: i32,
    wz: i32,
    block_name: &str,
    properties: &HashMap<String, String>,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> Vec<BlockQuad> {
    let short = strip_namespace(block_name);

    // Blocks the game draws from code have no geometry in any model JSON, so
    // parsing the assets finds nothing and they fall back to a plain cube --
    // a chest as a featureless box, a bell as its bare mounting bar. Their
    // shapes come from a transcribed table instead, and are *added to* the
    // model's own boxes rather than replacing them, because a bell needs both
    // the bar the model gives us and the bell the table does.
    let mut extra = Vec::new();
    if let Some(be) = crate::block_entity_models::block_entity_model(short) {
        let props = |key: &str| properties.get(key).map(String::as_str);
        for variant in be.variants {
            if variant.matches(&props) {
                extra.extend(model_quads(
                    wx,
                    wy,
                    wz,
                    block_name,
                    variant.elements,
                    0.0,
                    block_entity_rotation(properties),
                    lookup,
                ));
                break;
            }
        }
    }

    // Blocks with a real (non-cube) model draw their own boxes. Without this
    // the block id was ignored outright and everything became a cube, which
    // is why plants, carpets and clusters all came out as solid blocks.
    if let Some(model) = model_for(short) {
        let props = |key: &str| properties.get(key).map(String::as_str);
        let mut quads = std::mem::take(&mut extra);
        for variant in model.variants {
            if !variant.matches(&props) {
                continue;
            }
            quads.extend(model_quads(
                wx,
                wy,
                wz,
                block_name,
                variant.elements,
                variant.x_rot,
                variant.y_rot,
                lookup,
            ));
            // A multipart block is the union of every matching part (fence
            // post plus each connected side); an ordinary blockstate picks
            // exactly one.
            if !model.multipart {
                break;
            }
        }
        if !quads.is_empty() {
            return quads;
        }
        // No variant matched (unexpected state) — fall through to a cube
        // rather than emitting nothing and leaving a hole in the world.
    }

    // A code-drawn block with no model JSON at all -- a chest, a conduit, a
    // decorated pot. The transcribed boxes are the whole block, and without
    // this they would be thrown away for the cube fallback below.
    if !extra.is_empty() {
        return extra;
    }

    let mut quads = Vec::with_capacity(6);
    for (face_idx, (normal, corners)) in CUBE_FACES.iter().enumerate() {
        let nx = wx + normal[0];
        let ny = wy + normal[1];
        let nz = wz + normal[2];
        if is_occluded_for(block_name, nx, ny, nz, lookup) {
            continue;
        }
        let offset = [wx as f64, wy as f64, wz as f64];
        quads.push(BlockQuad {
            corners: [
                add3(corners[0], offset),
                add3(corners[1], offset),
                add3(corners[2], offset),
                add3(corners[3], offset),
            ],
            face_idx,
            normal: *normal,
            texture: None,
            uv: None,
        });
    }
    quads
}

/// Per-corner UVs for one quad, spanning its whole texture.
///
/// A prototype mesh is textured from the block's own PNG rather than a slice
/// of a shared atlas, so each face maps the full image. Derived from the
/// face's own extent so a partial box (a slab's side, a stair's step) shows
/// the matching part of the texture instead of stretching the whole thing
/// across it.
pub fn face_uv_corners(quad: &BlockQuad) -> [[f32; 2]; 4] {
    let normal = quad.normal;
    // Pick the two axes that span this face.
    let (ua, va) = if normal[1] != 0 {
        (0usize, 2usize)
    } else if normal[0] != 0 {
        (2, 1)
    } else {
        (0, 1)
    };
    // Side faces run bottom-up in world space but top-down in texture space.
    let flip_v = normal[1] == 0;
    let mut out = [[0.0f32; 2]; 4];

    if let Some([x1, y1, x2, y2]) = quad.uv {
        // The model states this face's rectangle outright, so the coordinates
        // are that rectangle spread across the face -- *not* the face's
        // position within the block. Those are different things whenever a box
        // is smaller than a full block: a stair's bottom slab spans y 0..8 and
        // declares uv [0, 8, 16, 16], meaning "the lower half of the image
        // stretched over me". Deriving from position and then remapping into
        // the rectangle applies that halving twice and shows a quarter of the
        // texture instead.
        //
        // Interpolating the rectangle across the face also mirrors for free
        // when it is reversed (x1 > x2), which is how vanilla flips a
        // right-hinged door.
        let span = |axis: usize| {
            let vals = quad.corners.iter().map(|c| c[axis] as f32);
            let lo = vals.clone().fold(f32::INFINITY, f32::min);
            let hi = vals.fold(f32::NEG_INFINITY, f32::max);
            (lo, hi - lo)
        };
        let (u_lo, u_len) = span(ua);
        let (v_lo, v_len) = span(va);
        let (ru1, ru2) = (x1 / 16.0, x2 / 16.0);
        let (rv1, rv2) = (y1 / 16.0, y2 / 16.0);

        for (slot, corner) in out.iter_mut().zip(quad.corners.iter()) {
            // Where this corner sits across the face itself, 0..1. A
            // degenerate span (a face seen edge-on) collapses to 0 rather
            // than dividing by zero.
            let s = if u_len > 1e-6 { (corner[ua] as f32 - u_lo) / u_len } else { 0.0 };
            let t = if v_len > 1e-6 { (corner[va] as f32 - v_lo) / v_len } else { 0.0 };
            let t = if flip_v { 1.0 - t } else { t };
            *slot = [ru1 + s * (ru2 - ru1), rv1 + t * (rv2 - rv1)];
        }
        return out;
    }

    for (slot, corner) in out.iter_mut().zip(quad.corners.iter()) {
        let u = corner[ua].rem_euclid(1.0) as f32;
        let v = corner[va].rem_euclid(1.0) as f32;
        // A coordinate landing exactly on the far edge wraps to 0; keep it at 1.
        let u = if u == 0.0 && corner[ua] > 0.0 { 1.0 } else { u };
        let v = if v == 0.0 && corner[va] > 0.0 { 1.0 } else { v };
        *slot = [u, if flip_v { 1.0 - v } else { v }];
    }
    out
}

/// Emit quads for a block described by vanilla model boxes.
///
/// Model space is 0..16 pixels per block; this scales to 0..1 and offsets to
/// the block's world position. Model faces are never culled against
/// neighbours — a plant or carpet is not a solid cube, so a neighbouring
/// block does not hide it, and culling by the cube rule would punch holes in
/// the shape.
fn model_quads<'a>(
    wx: i32,
    wy: i32,
    wz: i32,
    self_name: &str,
    elements: &[ModelElement],
    x_rot: f32,
    y_rot: f32,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> Vec<BlockQuad> {
    let mut quads = Vec::new();
    let offset = [wx as f64, wy as f64, wz as f64];
    // Blockstate rotation turns the whole model about the block centre.
    let block_centre = [0.5, 0.5, 0.5];

    for element in elements {
        for face in element.faces {
            let face_idx = face.face as usize;
            let Some((normal, unit_corners)) = CUBE_FACES.get(face_idx) else {
                continue;
            };
            // A face flush with the block boundary is hidden by an opaque
            // neighbour exactly as a cube face would be. Interior faces (a
            // slab's top, a plant's planes) are never culled — nothing next
            // door can cover them. Skipped entirely when the model is
            // rotated, since the boundary test assumes model axes.
            if x_rot == 0.0 && y_rot == 0.0 && element.rotation.is_none() {
                let axis = normal.iter().position(|n| *n != 0).unwrap_or(0);
                let outward_at_boundary = if normal[axis] > 0 {
                    (element.to[axis] - 16.0).abs() < 0.01
                } else {
                    element.from[axis].abs() < 0.01
                };
                if outward_at_boundary
                    && is_occluded_for(
                        self_name,
                        wx + normal[0],
                        wy + normal[1],
                        wz + normal[2],
                        lookup,
                    )
                {
                    continue;
                }
            }
            // Place the unit cube's face onto this box's extents.
            let mut corners = [[0.0f64; 3]; 4];
            for (slot, unit) in corners.iter_mut().zip(unit_corners.iter()) {
                for axis in 0..3 {
                    let lo = f64::from(element.from[axis]) / 16.0;
                    let hi = f64::from(element.to[axis]) / 16.0;
                    slot[axis] = lo + unit[axis] * (hi - lo);
                }
            }
            if let Some((axis, angle, origin, rescale)) = element.rotation {
                let origin = [
                    f64::from(origin[0]) / 16.0,
                    f64::from(origin[1]) / 16.0,
                    f64::from(origin[2]) / 16.0,
                ];
                for corner in &mut corners {
                    *corner = rotate_about(*corner, axis as usize, f64::from(angle), origin, rescale);
                }
            }
            // Blockstate rotation: x first, then y, matching vanilla.
            let mut normal_dir = [
                f64::from(normal[0]),
                f64::from(normal[1]),
                f64::from(normal[2]),
            ];
            // Negated: vanilla's blockstate `x`/`y` rotation turns the model
            // *clockwise* seen from the positive axis, the opposite sense to
            // `rotate_about`. Getting this backwards is close to invisible —
            // 0 and 180 degrees are symmetric, so north and south still land
            // right — while every 90-degree case silently mirrors: east/west
            // and up/down swap. That put mushroom caps on the opposite face
            // from the one the save named, and turned stairs, doors, buttons
            // and amethyst buds the wrong way round.
            if x_rot != 0.0 {
                for corner in &mut corners {
                    *corner = rotate_about(*corner, 0, -f64::from(x_rot), block_centre, false);
                }
                normal_dir = rotate_about(normal_dir, 0, -f64::from(x_rot), [0.0; 3], false);
            }
            if y_rot != 0.0 {
                for corner in &mut corners {
                    *corner = rotate_about(*corner, 1, -f64::from(y_rot), block_centre, false);
                }
                normal_dir = rotate_about(normal_dir, 1, -f64::from(y_rot), [0.0; 3], false);
            }
            for corner in &mut corners {
                *corner = add3(*corner, offset);
            }
            quads.push(BlockQuad {
                corners,
                face_idx,
                normal: [
                    normal_dir[0].round() as i32,
                    normal_dir[1].round() as i32,
                    normal_dir[2].round() as i32,
                ],
                texture: Some(face.texture.to_owned()),
                uv: Some(face.uv),
            });
        }
    }
    quads
}

/// Rotate a point about `origin` around one axis, in degrees.
///
/// `rescale` is vanilla's flag for stretching the result back out to the full
/// block width — without it the 45°-rotated planes of a cross-shaped plant
/// come out noticeably too small.
fn rotate_about(
    point: [f64; 3],
    axis: usize,
    degrees: f64,
    origin: [f64; 3],
    rescale: bool,
) -> [f64; 3] {
    let (sin, cos) = degrees.to_radians().sin_cos();
    let scale = if rescale {
        1.0 / degrees.to_radians().cos().abs().max(f64::EPSILON)
    } else {
        1.0
    };
    let p = [
        point[0] - origin[0],
        point[1] - origin[1],
        point[2] - origin[2],
    ];
    // The two axes that actually move for this rotation.
    let (a, b) = match axis {
        0 => (1, 2), // x: y/z
        1 => (2, 0), // y: z/x
        _ => (0, 1), // z: x/y
    };
    let mut out = p;
    out[a] = (p[a] * cos - p[b] * sin) * scale;
    out[b] = (p[a] * sin + p[b] * cos) * scale;
    [
        out[0] + origin[0],
        out[1] + origin[1],
        out[2] + origin[2],
    ]
}

/// A face at `(x, y, z)` is occluded iff the neighbour block exists AND
/// chunkforge-core reports it as opaque.
#[cfg(test)]
fn is_occluded<'a>(
    x: i32,
    y: i32,
    z: i32,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> bool {
    is_occluded_for("", x, y, z, lookup)
}

/// Occlusion test that also knows which block is asking.
///
/// A fluid never draws the face it shares with more of the same fluid — an
/// ocean would otherwise emit six faces for every block in it. Water is not a
/// full cube (its height varies with `level`), so the shape-based test below
/// correctly says it does not hide *other* blocks, but it must still hide
/// itself: without this, water alone accounted for 2.7M of a 3.4M-face export.
fn is_occluded_for<'a>(
    self_name: &str,
    x: i32,
    y: i32,
    z: i32,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> bool {
    match lookup(x, y, z) {
        Some(name) => {
            if !self_name.is_empty()
                && strip_namespace(name) == strip_namespace(self_name)
                && is_self_occluding(strip_namespace(name))
            {
                return true;
            }
            occludes(name)
        }
        None => false,
    }
}

/// Blocks that hide the faces they share with their own kind.
///
/// Space-filling but non-solid blocks: fluids fill their cell, and glass is
/// drawn without internal panes between neighbouring blocks.
fn is_self_occluding(short: &str) -> bool {
    matches!(
        short,
        "water" | "lava" | "flowing_water" | "flowing_lava" | "glass" | "tinted_glass" | "ice"
    )
}

/// True when a block genuinely hides the face of its neighbour.
///
/// Opacity alone is not enough. The appearance table reports anything it
/// doesn't recognise as opaque, which is safe for colouring but wrong for
/// culling: `leaf_litter` is a flat carpet a fraction of a block thick, yet
/// it reported opaque and so deleted the grass-block face underneath it —
/// leaving holes in the ground with the sky visible through them.
///
/// Nor is "is it a full cube" the right test on its own: `grass_block` has a
/// second overlay layer in its model and therefore isn't classed as a plain
/// cube, but it is still solid and must occlude. What matters is whether the
/// block's shape actually *covers* the face, so require an element spanning
/// the whole block — blocks with no model entry are plain cubes and qualify.
fn occludes(name: &str) -> bool {
    if !appearance(name).opaque {
        return false;
    }
    match model_for(strip_namespace(name)) {
        None => true,
        Some(model) => model.variants.iter().any(|variant| {
            variant.elements.iter().any(|element| {
                element.from.iter().all(|v| v.abs() < 0.01)
                    && element.to.iter().all(|v| (v - 16.0).abs() < 0.01)
            })
        }),
    }
}

fn add3(a: [f64; 3], b: [f64; 3]) -> [f64; 3] {
    [a[0] + b[0], a[1] + b[1], a[2] + b[2]]
}

/// The 6 faces of a unit cube, CW winding when viewed from outside.
/// Index order: 0=+Y(top), 1=-Y(bottom), 2=+X(east), 3=-X(west),
/// 4=+Z(south), 5=-Z(north).
pub const CUBE_FACES: [([i32; 3], [[f64; 3]; 4]); 6] = [
    (
        [0, 1, 0],
        [
            [0.0, 1.0, 1.0],
            [1.0, 1.0, 1.0],
            [1.0, 1.0, 0.0],
            [0.0, 1.0, 0.0],
        ],
    ),
    (
        [0, -1, 0],
        [
            [0.0, 0.0, 0.0],
            [1.0, 0.0, 0.0],
            [1.0, 0.0, 1.0],
            [0.0, 0.0, 1.0],
        ],
    ),
    (
        [1, 0, 0],
        [
            [1.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            [1.0, 1.0, 0.0],
            [1.0, 1.0, 1.0],
        ],
    ),
    (
        [-1, 0, 0],
        [
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [0.0, 1.0, 1.0],
            [0.0, 1.0, 0.0],
        ],
    ),
    (
        [0, 0, 1],
        [
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 1.0],
            [1.0, 1.0, 1.0],
            [0.0, 1.0, 1.0],
        ],
    ),
    (
        [0, 0, -1],
        [
            [1.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
            [1.0, 1.0, 0.0],
        ],
    ),
];

#[cfg(test)]
mod tests {
    use super::*;

    /// A thin block must not delete the face of the solid block beneath it.
    ///
    /// `leaf_litter` is a carpet a fraction of a block thick, but the
    /// appearance table calls it opaque (as it does anything it doesn't
    /// recognise). Culling on opacity alone therefore removed the grass-block
    /// top face under every patch of leaf litter, leaving holes that rendered
    /// as flat sky-coloured gaps in the terrain.
    #[test]
    fn thin_blocks_do_not_occlude_their_neighbours() {
        for thin in ["leaf_litter", "moss_carpet", "snow", "short_grass"] {
            assert!(
                !occludes(&format!("minecraft:{thin}")),
                "{thin} is not a full block and must not cull its neighbour"
            );
        }
    }

    /// ...but genuinely solid blocks still must, or every buried face in the
    /// world gets exported.
    #[test]
    fn solid_blocks_still_occlude() {
        for solid in ["stone", "dirt", "deepslate", "grass_block"] {
            assert!(
                occludes(&format!("minecraft:{solid}")),
                "{solid} is solid and must cull its neighbour"
            );
        }
    }
}

#[cfg(test)]
mod fence_state_tests {
    use super::*;

    /// A fence's shape comes entirely from which neighbours it connects to, so
    /// two different connection states must not produce the same mesh. Before
    /// prototypes were keyed by state, every fence in a world rendered as
    /// whichever connection pattern happened to be commonest.
    #[test]
    fn fence_geometry_varies_with_connections() {
        let nothing = |_: i32, _: i32, _: i32| -> Option<&str> { None };
        let build = |pairs: &[(&str, &str)]| {
            let props: HashMap<String, String> = pairs
                .iter()
                .map(|(k, v)| ((*k).to_owned(), (*v).to_owned()))
                .collect();
            let quads = block_quads_stated(0, 0, 0, "minecraft:oak_fence", &props, &nothing);
            (quads.len(), prototype_stem("minecraft:oak_fence", &props))
        };

        let post = build(&[("north", "false"), ("south", "false"), ("east", "false"), ("west", "false")]);
        let ns = build(&[("north", "true"), ("south", "true"), ("east", "false"), ("west", "false")]);
        let ew = build(&[("north", "false"), ("south", "false"), ("east", "true"), ("west", "true")]);

        assert!(post.0 > 0, "a bare fence post must still emit geometry");
        assert!(ns.0 > post.0, "connecting north-south must add rails");
        assert_eq!(ns.0, ew.0, "two connections is two connections either way");
        assert_ne!(ns.1, ew.1, "north-south and east-west need different meshes");
        assert_ne!(post.1, ns.1, "a bare post is not a connected fence");
    }

    /// Stairs likewise: facing must reach the mesh, or every stair in a world
    /// points the same way.
    #[test]
    fn stair_geometry_varies_with_facing() {
        let nothing = |_: i32, _: i32, _: i32| -> Option<&str> { None };
        let build = |facing: &str| {
            let props: HashMap<String, String> = [
                ("facing", facing), ("half", "bottom"), ("shape", "straight"),
            ]
            .iter()
            .map(|(k, v)| ((*k).to_owned(), (*v).to_owned()))
            .collect();
            let quads = block_quads_stated(0, 0, 0, "minecraft:oak_stairs", &props, &nothing);
            let corners: Vec<_> = quads.iter().map(|q| q.corners).collect();
            (corners, prototype_stem("minecraft:oak_stairs", &props))
        };
        let north = build("north");
        let east = build("east");
        assert!(!north.0.is_empty(), "stairs must emit geometry");
        assert_ne!(north.1, east.1, "facings need different meshes");
        assert_ne!(north.0, east.0, "a north stair is not an east stair");
    }
}

#[cfg(test)]
mod blockstate_rotation_tests {
    use super::*;

    /// Blockstate `x`/`y` rotation is *clockwise* viewed from the positive
    /// axis, the opposite sense to a textbook counter-clockwise rotation.
    ///
    /// A mushroom block is the clearest witness: vanilla models it as one flat
    /// face turned into place by the blockstate, one variant per side. With
    /// the rotation inverted, north and south still land correctly — 0 and 180
    /// degrees are symmetric — while east/west and up/down silently swap, so
    /// the cap texture appears on the face opposite the one the save asked
    /// for. The same error turns every stair, door, button and bud the wrong
    /// way round.
    #[test]
    fn single_face_lands_on_the_side_the_state_names() {
        let nothing = |_: i32, _: i32, _: i32| -> Option<&str> { None };
        let face_normal = |side: &str| {
            let props: HashMap<String, String> = ["north", "south", "east", "west", "up", "down"]
                .iter()
                .map(|k| ((*k).to_owned(), if *k == side { "true" } else { "false" }.to_owned()))
                .collect();
            let quads =
                block_quads_stated(0, 0, 0, "minecraft:red_mushroom_block", &props, &nothing);
            let capped: Vec<_> = quads
                .iter()
                .filter(|q| q.texture.as_deref() == Some("red_mushroom_block"))
                .collect();
            assert_eq!(capped.len(), 1, "{side}: exactly one face wears the cap");
            capped[0].normal
        };

        // Minecraft axes: +Y up, +Z south, +X east.
        assert_eq!(face_normal("up"), [0, 1, 0], "up must face up");
        assert_eq!(face_normal("down"), [0, -1, 0], "down must face down");
        assert_eq!(face_normal("north"), [0, 0, -1], "north must face north");
        assert_eq!(face_normal("south"), [0, 0, 1], "south must face south");
        assert_eq!(face_normal("east"), [1, 0, 0], "east must face east");
        assert_eq!(face_normal("west"), [-1, 0, 0], "west must face west");
    }
}
