//! Per-block geometry.
//!
//! Blocks whose real shape is a plain cube emit one quad per unoccluded face.
//! Everything else — plants, carpets, clusters, stairs, slabs, fences — emits
//! the boxes from vanilla's own block model instead (see
//! [`crate::block_models`], generated by `tools/gen_block_models.py`).
//!
//! Face culling uses chunkforge-core's appearance-table opacity.

use crate::block_models::{model_for, ModelElement};
use crate::chunk::strip_namespace;
use crate::java_simple::appearance;
use std::collections::HashMap;

/// One quad face emitted for a block.
#[derive(Debug, Clone)]
pub struct BlockQuad {
    /// 4 corners in world space, CW from outside.
    pub corners: [[f64; 3]; 4],
    /// Face index 0..5 for UV look-up (top/bottom/east/west/south/north).
    pub face_idx: usize,
    /// Normal direction as a face-index offset.
    pub normal: [i32; 3],
    /// Optional override texture name (None = use face-based UV from block).
    pub texture: Option<String>,
}

/// Get the quads for a block.  All blocks are full cubes; visible faces
/// are determined solely by neighbour opacity (chunkforge-core's table).
pub fn block_quads<'a>(
    wx: i32,
    wy: i32,
    wz: i32,
    block_name: &str,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> Vec<BlockQuad> {
    block_quads_stated(wx, wy, wz, block_name, &HashMap::new(), lookup)
}

/// [`block_quads`], but able to pick the block-state-specific shape.
///
/// Orientation lives in the block state: a stair's `facing`/`half`, a fence's
/// per-side connection flags. Without them every stair in a build points the
/// same way and fences lose their rails, so callers that have the state
/// should pass it.
pub fn block_quads_stated<'a>(
    wx: i32,
    wy: i32,
    wz: i32,
    block_name: &str,
    properties: &HashMap<String, String>,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> Vec<BlockQuad> {
    // Blocks with a real (non-cube) model draw their own boxes. Without this
    // the block id was ignored outright and everything became a cube, which
    // is why plants, carpets and clusters all came out as solid blocks.
    if let Some(model) = model_for(strip_namespace(block_name)) {
        let props = |key: &str| properties.get(key).map(String::as_str);
        let mut quads = Vec::new();
        for variant in model.variants {
            if !variant.matches(&props) {
                continue;
            }
            quads.extend(model_quads(
                wx,
                wy,
                wz,
                block_name,
                variant.elements,
                variant.x_rot,
                variant.y_rot,
                lookup,
            ));
            // A multipart block is the union of every matching part (fence
            // post plus each connected side); an ordinary blockstate picks
            // exactly one.
            if !model.multipart {
                break;
            }
        }
        if !quads.is_empty() {
            return quads;
        }
        // No variant matched (unexpected state) — fall through to a cube
        // rather than emitting nothing and leaving a hole in the world.
    }

    let mut quads = Vec::with_capacity(6);
    for (face_idx, (normal, corners)) in CUBE_FACES.iter().enumerate() {
        let nx = wx + normal[0];
        let ny = wy + normal[1];
        let nz = wz + normal[2];
        if is_occluded_for(block_name, nx, ny, nz, lookup) {
            continue;
        }
        let offset = [wx as f64, wy as f64, wz as f64];
        quads.push(BlockQuad {
            corners: [
                add3(corners[0], offset),
                add3(corners[1], offset),
                add3(corners[2], offset),
                add3(corners[3], offset),
            ],
            face_idx,
            normal: *normal,
            texture: None,
        });
    }
    quads
}

/// Per-corner UVs for one quad, spanning its whole texture.
///
/// A prototype mesh is textured from the block's own PNG rather than a slice
/// of a shared atlas, so each face maps the full image. Derived from the
/// face's own extent so a partial box (a slab's side, a stair's step) shows
/// the matching part of the texture instead of stretching the whole thing
/// across it.
pub fn face_uv_corners(quad: &BlockQuad) -> [[f32; 2]; 4] {
    let normal = quad.normal;
    // Pick the two axes that span this face.
    let (ua, va) = if normal[1] != 0 {
        (0usize, 2usize)
    } else if normal[0] != 0 {
        (2, 1)
    } else {
        (0, 1)
    };
    // Side faces run bottom-up in world space but top-down in texture space.
    let flip_v = normal[1] == 0;
    let mut out = [[0.0f32; 2]; 4];
    for (slot, corner) in out.iter_mut().zip(quad.corners.iter()) {
        let u = corner[ua].rem_euclid(1.0) as f32;
        let v = corner[va].rem_euclid(1.0) as f32;
        // A coordinate landing exactly on the far edge wraps to 0; keep it at 1.
        let u = if u == 0.0 && corner[ua] > 0.0 { 1.0 } else { u };
        let v = if v == 0.0 && corner[va] > 0.0 { 1.0 } else { v };
        *slot = [u, if flip_v { 1.0 - v } else { v }];
    }
    out
}

/// Emit quads for a block described by vanilla model boxes.
///
/// Model space is 0..16 pixels per block; this scales to 0..1 and offsets to
/// the block's world position. Model faces are never culled against
/// neighbours — a plant or carpet is not a solid cube, so a neighbouring
/// block does not hide it, and culling by the cube rule would punch holes in
/// the shape.
fn model_quads<'a>(
    wx: i32,
    wy: i32,
    wz: i32,
    self_name: &str,
    elements: &[ModelElement],
    x_rot: f32,
    y_rot: f32,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> Vec<BlockQuad> {
    let mut quads = Vec::new();
    let offset = [wx as f64, wy as f64, wz as f64];
    // Blockstate rotation turns the whole model about the block centre.
    let block_centre = [0.5, 0.5, 0.5];

    for element in elements {
        for face in element.faces {
            let face_idx = face.face as usize;
            let Some((normal, unit_corners)) = CUBE_FACES.get(face_idx) else {
                continue;
            };
            // A face flush with the block boundary is hidden by an opaque
            // neighbour exactly as a cube face would be. Interior faces (a
            // slab's top, a plant's planes) are never culled — nothing next
            // door can cover them. Skipped entirely when the model is
            // rotated, since the boundary test assumes model axes.
            if x_rot == 0.0 && y_rot == 0.0 && element.rotation.is_none() {
                let axis = normal.iter().position(|n| *n != 0).unwrap_or(0);
                let outward_at_boundary = if normal[axis] > 0 {
                    (element.to[axis] - 16.0).abs() < 0.01
                } else {
                    element.from[axis].abs() < 0.01
                };
                if outward_at_boundary
                    && is_occluded_for(
                        self_name,
                        wx + normal[0],
                        wy + normal[1],
                        wz + normal[2],
                        lookup,
                    )
                {
                    continue;
                }
            }
            // Place the unit cube's face onto this box's extents.
            let mut corners = [[0.0f64; 3]; 4];
            for (slot, unit) in corners.iter_mut().zip(unit_corners.iter()) {
                for axis in 0..3 {
                    let lo = f64::from(element.from[axis]) / 16.0;
                    let hi = f64::from(element.to[axis]) / 16.0;
                    slot[axis] = lo + unit[axis] * (hi - lo);
                }
            }
            if let Some((axis, angle, origin, rescale)) = element.rotation {
                let origin = [
                    f64::from(origin[0]) / 16.0,
                    f64::from(origin[1]) / 16.0,
                    f64::from(origin[2]) / 16.0,
                ];
                for corner in &mut corners {
                    *corner = rotate_about(*corner, axis as usize, f64::from(angle), origin, rescale);
                }
            }
            // Blockstate rotation: x first, then y, matching vanilla.
            let mut normal_dir = [
                f64::from(normal[0]),
                f64::from(normal[1]),
                f64::from(normal[2]),
            ];
            if x_rot != 0.0 {
                for corner in &mut corners {
                    *corner = rotate_about(*corner, 0, f64::from(x_rot), block_centre, false);
                }
                normal_dir = rotate_about(normal_dir, 0, f64::from(x_rot), [0.0; 3], false);
            }
            if y_rot != 0.0 {
                for corner in &mut corners {
                    *corner = rotate_about(*corner, 1, f64::from(y_rot), block_centre, false);
                }
                normal_dir = rotate_about(normal_dir, 1, f64::from(y_rot), [0.0; 3], false);
            }
            for corner in &mut corners {
                *corner = add3(*corner, offset);
            }
            quads.push(BlockQuad {
                corners,
                face_idx,
                normal: [
                    normal_dir[0].round() as i32,
                    normal_dir[1].round() as i32,
                    normal_dir[2].round() as i32,
                ],
                texture: Some(face.texture.to_owned()),
            });
        }
    }
    quads
}

/// Rotate a point about `origin` around one axis, in degrees.
///
/// `rescale` is vanilla's flag for stretching the result back out to the full
/// block width — without it the 45°-rotated planes of a cross-shaped plant
/// come out noticeably too small.
fn rotate_about(
    point: [f64; 3],
    axis: usize,
    degrees: f64,
    origin: [f64; 3],
    rescale: bool,
) -> [f64; 3] {
    let (sin, cos) = degrees.to_radians().sin_cos();
    let scale = if rescale {
        1.0 / degrees.to_radians().cos().abs().max(f64::EPSILON)
    } else {
        1.0
    };
    let p = [
        point[0] - origin[0],
        point[1] - origin[1],
        point[2] - origin[2],
    ];
    // The two axes that actually move for this rotation.
    let (a, b) = match axis {
        0 => (1, 2), // x: y/z
        1 => (2, 0), // y: z/x
        _ => (0, 1), // z: x/y
    };
    let mut out = p;
    out[a] = (p[a] * cos - p[b] * sin) * scale;
    out[b] = (p[a] * sin + p[b] * cos) * scale;
    [
        out[0] + origin[0],
        out[1] + origin[1],
        out[2] + origin[2],
    ]
}

/// A face at `(x, y, z)` is occluded iff the neighbour block exists AND
/// chunkforge-core reports it as opaque.
#[cfg(test)]
fn is_occluded<'a>(
    x: i32,
    y: i32,
    z: i32,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> bool {
    is_occluded_for("", x, y, z, lookup)
}

/// Occlusion test that also knows which block is asking.
///
/// A fluid never draws the face it shares with more of the same fluid — an
/// ocean would otherwise emit six faces for every block in it. Water is not a
/// full cube (its height varies with `level`), so the shape-based test below
/// correctly says it does not hide *other* blocks, but it must still hide
/// itself: without this, water alone accounted for 2.7M of a 3.4M-face export.
fn is_occluded_for<'a>(
    self_name: &str,
    x: i32,
    y: i32,
    z: i32,
    lookup: &impl Fn(i32, i32, i32) -> Option<&'a str>,
) -> bool {
    match lookup(x, y, z) {
        Some(name) => {
            if !self_name.is_empty()
                && strip_namespace(name) == strip_namespace(self_name)
                && is_self_occluding(strip_namespace(name))
            {
                return true;
            }
            occludes(name)
        }
        None => false,
    }
}

/// Blocks that hide the faces they share with their own kind.
///
/// Space-filling but non-solid blocks: fluids fill their cell, and glass is
/// drawn without internal panes between neighbouring blocks.
fn is_self_occluding(short: &str) -> bool {
    matches!(
        short,
        "water" | "lava" | "flowing_water" | "flowing_lava" | "glass" | "tinted_glass" | "ice"
    )
}

/// True when a block genuinely hides the face of its neighbour.
///
/// Opacity alone is not enough. The appearance table reports anything it
/// doesn't recognise as opaque, which is safe for colouring but wrong for
/// culling: `leaf_litter` is a flat carpet a fraction of a block thick, yet
/// it reported opaque and so deleted the grass-block face underneath it —
/// leaving holes in the ground with the sky visible through them.
///
/// Nor is "is it a full cube" the right test on its own: `grass_block` has a
/// second overlay layer in its model and therefore isn't classed as a plain
/// cube, but it is still solid and must occlude. What matters is whether the
/// block's shape actually *covers* the face, so require an element spanning
/// the whole block — blocks with no model entry are plain cubes and qualify.
fn occludes(name: &str) -> bool {
    if !appearance(name).opaque {
        return false;
    }
    match model_for(strip_namespace(name)) {
        None => true,
        Some(model) => model.variants.iter().any(|variant| {
            variant.elements.iter().any(|element| {
                element.from.iter().all(|v| v.abs() < 0.01)
                    && element.to.iter().all(|v| (v - 16.0).abs() < 0.01)
            })
        }),
    }
}

fn add3(a: [f64; 3], b: [f64; 3]) -> [f64; 3] {
    [a[0] + b[0], a[1] + b[1], a[2] + b[2]]
}

/// The 6 faces of a unit cube, CW winding when viewed from outside.
/// Index order: 0=+Y(top), 1=-Y(bottom), 2=+X(east), 3=-X(west),
/// 4=+Z(south), 5=-Z(north).
pub const CUBE_FACES: [([i32; 3], [[f64; 3]; 4]); 6] = [
    (
        [0, 1, 0],
        [
            [0.0, 1.0, 1.0],
            [1.0, 1.0, 1.0],
            [1.0, 1.0, 0.0],
            [0.0, 1.0, 0.0],
        ],
    ),
    (
        [0, -1, 0],
        [
            [0.0, 0.0, 0.0],
            [1.0, 0.0, 0.0],
            [1.0, 0.0, 1.0],
            [0.0, 0.0, 1.0],
        ],
    ),
    (
        [1, 0, 0],
        [
            [1.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            [1.0, 1.0, 0.0],
            [1.0, 1.0, 1.0],
        ],
    ),
    (
        [-1, 0, 0],
        [
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [0.0, 1.0, 1.0],
            [0.0, 1.0, 0.0],
        ],
    ),
    (
        [0, 0, 1],
        [
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 1.0],
            [1.0, 1.0, 1.0],
            [0.0, 1.0, 1.0],
        ],
    ),
    (
        [0, 0, -1],
        [
            [1.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
            [1.0, 1.0, 0.0],
        ],
    ),
];

#[cfg(test)]
mod tests {
    use super::*;

    /// A thin block must not delete the face of the solid block beneath it.
    ///
    /// `leaf_litter` is a carpet a fraction of a block thick, but the
    /// appearance table calls it opaque (as it does anything it doesn't
    /// recognise). Culling on opacity alone therefore removed the grass-block
    /// top face under every patch of leaf litter, leaving holes that rendered
    /// as flat sky-coloured gaps in the terrain.
    #[test]
    fn thin_blocks_do_not_occlude_their_neighbours() {
        for thin in ["leaf_litter", "moss_carpet", "snow", "short_grass"] {
            assert!(
                !occludes(&format!("minecraft:{thin}")),
                "{thin} is not a full block and must not cull its neighbour"
            );
        }
    }

    /// ...but genuinely solid blocks still must, or every buried face in the
    /// world gets exported.
    #[test]
    fn solid_blocks_still_occlude() {
        for solid in ["stone", "dirt", "deepslate", "grass_block"] {
            assert!(
                occludes(&format!("minecraft:{solid}")),
                "{solid} is solid and must cull its neighbour"
            );
        }
    }
}
