// Auto-generated from Mineways blockInfo.cpp ù 506 blocks
pub const BLF_WHOLE: u32 = 0x1;
pub const BLF_ALMOST_WHOLE: u32 = 0x2;
pub const BLF_STAIRS: u32 = 0x4;
pub const BLF_HALF: u32 = 0x8;
pub const BLF_BILLBOARD: u32 = 0x20;
pub const BLF_SMALL_BILLBOARD: u32 = 0x400;
pub const BLF_PANE: u32 = 0x40;
pub const BLF_FLATTEN: u32 = 0x80;
pub const BLF_NONE: u32 = 0x800000;
pub struct BlockInfo {
    pub name: &'static str,
    pub txr_x: u32,
    pub txr_y: u32,
    pub variant_mask: u32,
    pub flags: u32,
}
pub static G_BLOCK_DEFINITIONS: [BlockInfo; 506] = [
    BlockInfo {
        name: "Air",
        txr_x: 13,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x800000,
    },
    BlockInfo {
        name: "Stone",
        txr_x: 1,
        txr_y: 0,
        variant_mask: 0x1f,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Grass Block",
        txr_x: 0,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Dirt",
        txr_x: 2,
        txr_y: 0,
        variant_mask: 0x07,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Cobblestone",
        txr_x: 0,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Oak Planks",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x0f,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Oak Sapling",
        txr_x: 15,
        txr_y: 0,
        variant_mask: 0x07,
        flags: 0x201480,
    },
    BlockInfo {
        name: "Bedrock",
        txr_x: 1,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Water",
        txr_x: 8,
        txr_y: 26,
        variant_mask: 0x00,
        flags: 0x802,
    },
    BlockInfo {
        name: "Stationary Water",
        txr_x: 15,
        txr_y: 13,
        variant_mask: 0x10,
        flags: 0x802,
    },
    BlockInfo {
        name: "Lava",
        txr_x: 9,
        txr_y: 26,
        variant_mask: 0x00,
        flags: 0x10002,
    },
    BlockInfo {
        name: "Stationary Lava",
        txr_x: 15,
        txr_y: 15,
        variant_mask: 0x00,
        flags: 0x10002,
    },
    BlockInfo {
        name: "Sand",
        txr_x: 2,
        txr_y: 1,
        variant_mask: 0x01,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Gravel",
        txr_x: 3,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Gold Ore",
        txr_x: 0,
        txr_y: 2,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Iron Ore",
        txr_x: 1,
        txr_y: 2,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Coal Ore",
        txr_x: 2,
        txr_y: 2,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Oak Log",
        txr_x: 5,
        txr_y: 1,
        variant_mask: 0x13,
        flags: 0x22001,
    },
    BlockInfo {
        name: "Oak Leaves",
        txr_x: 4,
        txr_y: 3,
        variant_mask: 0x03,
        flags: 0x4005001,
    },
    BlockInfo {
        name: "Sponge",
        txr_x: 0,
        txr_y: 3,
        variant_mask: 0x01,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Glass",
        txr_x: 1,
        txr_y: 3,
        variant_mask: 0x01,
        flags: 0x21001,
    },
    BlockInfo {
        name: "Lapis Lazuli Ore",
        txr_x: 0,
        txr_y: 10,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Block of Lapis Lazuli",
        txr_x: 0,
        txr_y: 9,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Dispenser",
        txr_x: 14,
        txr_y: 3,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Sandstone",
        txr_x: 0,
        txr_y: 11,
        variant_mask: 0x03,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Note Block",
        txr_x: 12,
        txr_y: 8,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Bed",
        txr_x: 6,
        txr_y: 8,
        variant_mask: 0x00,
        flags: 0xC1010,
    },
    BlockInfo {
        name: "Powered Rail",
        txr_x: 3,
        txr_y: 11,
        variant_mask: 0x00,
        flags: 0x52810A0,
    },
    BlockInfo {
        name: "Detector Rail",
        txr_x: 3,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x56810A0,
    },
    BlockInfo {
        name: "Sticky Piston",
        txr_x: 12,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0xC0002,
    },
    BlockInfo {
        name: "Cobweb",
        txr_x: 11,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x201020,
    },
    BlockInfo {
        name: "Short Grass",
        txr_x: 7,
        txr_y: 2,
        variant_mask: 0x0f,
        flags: 0x211480,
    },
    BlockInfo {
        name: "Dead Bush",
        txr_x: 7,
        txr_y: 3,
        variant_mask: 0x00,
        flags: 0x201480,
    },
    BlockInfo {
        name: "Piston",
        txr_x: 12,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0xC0002,
    },
    BlockInfo {
        name: "Piston Head",
        txr_x: 11,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0xC0002,
    },
    BlockInfo {
        name: "Wool",
        txr_x: 0,
        txr_y: 4,
        variant_mask: 0x0f,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Block moved by Piston",
        txr_x: 11,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0x800000,
    },
    BlockInfo {
        name: "Dandelion",
        txr_x: 13,
        txr_y: 0,
        variant_mask: 0x0f,
        flags: 0x201480,
    },
    BlockInfo {
        name: "Poppy",
        txr_x: 12,
        txr_y: 0,
        variant_mask: 0x0f,
        flags: 0x201480,
    },
    BlockInfo {
        name: "Brown Mushroom",
        txr_x: 13,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x211480,
    },
    BlockInfo {
        name: "Red Mushroom",
        txr_x: 12,
        txr_y: 1,
        variant_mask: 0x03,
        flags: 0x201480,
    },
    BlockInfo {
        name: "Block of Gold",
        txr_x: 7,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Block of Iron",
        txr_x: 6,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Double Stone Slab",
        txr_x: 10,
        txr_y: 23,
        variant_mask: 0x07,
        flags: 0x24020001,
    },
    BlockInfo {
        name: "Stone Slab",
        txr_x: 10,
        txr_y: 23,
        variant_mask: 0x07,
        flags: 0x41C0008,
    },
    BlockInfo {
        name: "Bricks",
        txr_x: 7,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "TNT",
        txr_x: 9,
        txr_y: 0,
        variant_mask: 0x01,
        flags: 0x1,
    },
    BlockInfo {
        name: "Bookshelf",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x10,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Mossy Cobblestone",
        txr_x: 4,
        txr_y: 2,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Obsidian",
        txr_x: 5,
        txr_y: 2,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Torch",
        txr_x: 0,
        txr_y: 5,
        variant_mask: 0x00,
        flags: 0x211490,
    },
    BlockInfo {
        name: "Fire",
        txr_x: 15,
        txr_y: 1,
        variant_mask: 0x10,
        flags: 0x211020,
    },
    BlockInfo {
        name: "Spawner",
        txr_x: 1,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x1002,
    },
    BlockInfo {
        name: "Oak Stairs",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Chest",
        txr_x: 9,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x40C0002,
    },
    BlockInfo {
        name: "Redstone Wire",
        txr_x: 4,
        txr_y: 10,
        variant_mask: 0x0f,
        flags: 0x1601080,
    },
    BlockInfo {
        name: "Diamond Ore",
        txr_x: 2,
        txr_y: 3,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Block of Diamond",
        txr_x: 8,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Crafting Table",
        txr_x: 11,
        txr_y: 2,
        variant_mask: 0x07,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Wheat",
        txr_x: 15,
        txr_y: 5,
        variant_mask: 0x00,
        flags: 0x201020,
    },
    BlockInfo {
        name: "Farmland",
        txr_x: 7,
        txr_y: 5,
        variant_mask: 0x00,
        flags: 0x1C0002,
    },
    BlockInfo {
        name: "Furnace",
        txr_x: 14,
        txr_y: 3,
        variant_mask: 0x30,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Burning Furnace",
        txr_x: 14,
        txr_y: 3,
        variant_mask: 0x00,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Oak Sign",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x30,
        flags: 0x40C0200,
    },
    BlockInfo {
        name: "Oak Door",
        txr_x: 1,
        txr_y: 5,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Ladder",
        txr_x: 3,
        txr_y: 5,
        variant_mask: 0x00,
        flags: 0x5209100,
    },
    BlockInfo {
        name: "Rail",
        txr_x: 0,
        txr_y: 8,
        variant_mask: 0x00,
        flags: 0x52810A0,
    },
    BlockInfo {
        name: "Cobblestone Stairs",
        txr_x: 0,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Wall Sign",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x38,
        flags: 0x42C0100,
    },
    BlockInfo {
        name: "Lever",
        txr_x: 0,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0x640300,
    },
    BlockInfo {
        name: "Stone Pressure Plate",
        txr_x: 1,
        txr_y: 0,
        variant_mask: 0x7e,
        flags: 0x4C0080,
    },
    BlockInfo {
        name: "Iron Door",
        txr_x: 2,
        txr_y: 5,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Oak Pressure Plate",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x4C0080,
    },
    BlockInfo {
        name: "Redstone Ore",
        txr_x: 3,
        txr_y: 3,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Glowing Redstone Ore",
        txr_x: 3,
        txr_y: 3,
        variant_mask: 0x00,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Redstone Torch (inactive)",
        txr_x: 3,
        txr_y: 7,
        variant_mask: 0x00,
        flags: 0x601490,
    },
    BlockInfo {
        name: "Redstone Torch (active)",
        txr_x: 3,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0x611490,
    },
    BlockInfo {
        name: "Stone Button",
        txr_x: 1,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Snow",
        txr_x: 2,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x2C0080,
    },
    BlockInfo {
        name: "Ice",
        txr_x: 3,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x801,
    },
    BlockInfo {
        name: "Snow Block",
        txr_x: 2,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Cactus",
        txr_x: 5,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x2C1022,
    },
    BlockInfo {
        name: "Clay",
        txr_x: 8,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Sugar Cane",
        txr_x: 9,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x201020,
    },
    BlockInfo {
        name: "Jukebox",
        txr_x: 11,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Fence",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Pumpkin",
        txr_x: 6,
        txr_y: 6,
        variant_mask: 0x04,
        flags: 0x1,
    },
    BlockInfo {
        name: "Netherrack",
        txr_x: 7,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Soul Sand",
        txr_x: 8,
        txr_y: 6,
        variant_mask: 0x01,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Glowstone",
        txr_x: 9,
        txr_y: 6,
        variant_mask: 0x01,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Nether Portal",
        txr_x: 14,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x2D0850,
    },
    BlockInfo {
        name: "Jack o'Lantern",
        txr_x: 6,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0x10001,
    },
    BlockInfo {
        name: "Cake",
        txr_x: 9,
        txr_y: 7,
        variant_mask: 0x3f,
        flags: 0xC0002,
    },
    BlockInfo {
        name: "Redstone Repeater (inactive)",
        txr_x: 3,
        txr_y: 8,
        variant_mask: 0x00,
        flags: 0x2C0090,
    },
    BlockInfo {
        name: "Redstone Repeater (active)",
        txr_x: 3,
        txr_y: 9,
        variant_mask: 0x00,
        flags: 0x2C0090,
    },
    BlockInfo {
        name: "Locked Chest",
        txr_x: 9,
        txr_y: 1,
        variant_mask: 0x0F,
        flags: 0x1,
    },
    BlockInfo {
        name: "Stained Glass",
        txr_x: 0,
        txr_y: 20,
        variant_mask: 0x0f,
        flags: 0x20801,
    },
    BlockInfo {
        name: "Oak Trapdoor",
        txr_x: 4,
        txr_y: 5,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Infested Stone",
        txr_x: 1,
        txr_y: 0,
        variant_mask: 0x07,
        flags: 0x1,
    },
    BlockInfo {
        name: "Stone Bricks",
        txr_x: 6,
        txr_y: 3,
        variant_mask: 0x03,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Brown Mushroom Block",
        txr_x: 14,
        txr_y: 7,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Red Mushroom Block",
        txr_x: 13,
        txr_y: 7,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Iron Bars",
        txr_x: 5,
        txr_y: 5,
        variant_mask: 0x00,
        flags: 0x40C1040,
    },
    BlockInfo {
        name: "Glass Pane",
        txr_x: 1,
        txr_y: 3,
        variant_mask: 0x00,
        flags: 0x40C1040,
    },
    BlockInfo {
        name: "Melon",
        txr_x: 9,
        txr_y: 8,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Pumpkin Stem",
        txr_x: 14,
        txr_y: 11,
        variant_mask: 0x0f,
        flags: 0x201500,
    },
    BlockInfo {
        name: "Melon Stem",
        txr_x: 15,
        txr_y: 6,
        variant_mask: 0x0f,
        flags: 0x201500,
    },
    BlockInfo {
        name: "Vines",
        txr_x: 15,
        txr_y: 8,
        variant_mask: 0x00,
        flags: 0x1201160,
    },
    BlockInfo {
        name: "Fence Gate",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Brick Stairs",
        txr_x: 7,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Stone Brick Stairs",
        txr_x: 6,
        txr_y: 3,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Mycelium",
        txr_x: 14,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Lily Pad",
        txr_x: 12,
        txr_y: 4,
        variant_mask: 0x00,
        flags: 0x1201080,
    },
    BlockInfo {
        name: "Nether Brick",
        txr_x: 0,
        txr_y: 14,
        variant_mask: 0x03,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Nether Brick Fence",
        txr_x: 0,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Nether Brick Stairs",
        txr_x: 0,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Nether Wart",
        txr_x: 4,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x2010A0,
    },
    BlockInfo {
        name: "Enchanting Table",
        txr_x: 6,
        txr_y: 10,
        variant_mask: 0x00,
        flags: 0x1C0002,
    },
    BlockInfo {
        name: "Brewing Stand",
        txr_x: 13,
        txr_y: 9,
        variant_mask: 0x00,
        flags: 0x51010,
    },
    BlockInfo {
        name: "Cauldron",
        txr_x: 10,
        txr_y: 8,
        variant_mask: 0x0c,
        flags: 0x1D1002,
    },
    BlockInfo {
        name: "End Portal",
        txr_x: 8,
        txr_y: 11,
        variant_mask: 0x00,
        flags: 0x1D0002,
    },
    BlockInfo {
        name: "End Portal Frame",
        txr_x: 14,
        txr_y: 9,
        variant_mask: 0x00,
        flags: 0x1C0002,
    },
    BlockInfo {
        name: "End Stone",
        txr_x: 15,
        txr_y: 10,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Dragon Egg",
        txr_x: 7,
        txr_y: 10,
        variant_mask: 0x00,
        flags: 0xD0002,
    },
    BlockInfo {
        name: "Redstone Lamp (inactive)",
        txr_x: 3,
        txr_y: 13,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Redstone Lamp (active)",
        txr_x: 4,
        txr_y: 13,
        variant_mask: 0x00,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Double Oak Slab",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x07,
        flags: 0x24020001,
    },
    BlockInfo {
        name: "Oak Slab",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x07,
        flags: 0x41C0008,
    },
    BlockInfo {
        name: "Cocoa",
        txr_x: 8,
        txr_y: 10,
        variant_mask: 0x00,
        flags: 0x2C1200,
    },
    BlockInfo {
        name: "Sandstone Stairs",
        txr_x: 0,
        txr_y: 11,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Emerald Ore",
        txr_x: 11,
        txr_y: 10,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Ender Chest",
        txr_x: 10,
        txr_y: 13,
        variant_mask: 0x00,
        flags: 0x40D0002,
    },
    BlockInfo {
        name: "Tripwire Hook",
        txr_x: 12,
        txr_y: 10,
        variant_mask: 0x00,
        flags: 0x240300,
    },
    BlockInfo {
        name: "Tripwire",
        txr_x: 13,
        txr_y: 10,
        variant_mask: 0x00,
        flags: 0xA00000,
    },
    BlockInfo {
        name: "Tripwire",
        txr_x: 13,
        txr_y: 10,
        variant_mask: 0x0F,
        flags: 0x1000,
    },
    BlockInfo {
        name: "Block of Emerald",
        txr_x: 12,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Spruce Stairs",
        txr_x: 6,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Birch Stairs",
        txr_x: 6,
        txr_y: 13,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Jungle Stairs",
        txr_x: 7,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Command Block",
        txr_x: 10,
        txr_y: 24,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Beacon",
        txr_x: 11,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x51002,
    },
    BlockInfo {
        name: "Cobblestone Wall",
        txr_x: 0,
        txr_y: 1,
        variant_mask: 0x1f,
        flags: 0x41C0010,
    },
    BlockInfo {
        name: "Flower Pot",
        txr_x: 10,
        txr_y: 11,
        variant_mask: 0xff,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Carrot",
        txr_x: 11,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x2010A0,
    },
    BlockInfo {
        name: "Potato",
        txr_x: 15,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x2010A0,
    },
    BlockInfo {
        name: "Oak Button",
        txr_x: 4,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Mob Head",
        txr_x: 6,
        txr_y: 6,
        variant_mask: 0x80,
        flags: 0x2C0002,
    },
    BlockInfo {
        name: "Anvil",
        txr_x: 7,
        txr_y: 13,
        variant_mask: 0x0c,
        flags: 0xC0002,
    },
    BlockInfo {
        name: "Trapped Chest",
        txr_x: 9,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x44C0002,
    },
    BlockInfo {
        name: "Light Weighted Pressure Plate",
        txr_x: 7,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x4C0080,
    },
    BlockInfo {
        name: "Heavy Weighted Pressure Plate",
        txr_x: 6,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x4C0080,
    },
    BlockInfo {
        name: "Redstone Comparator",
        txr_x: 14,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x6C0090,
    },
    BlockInfo {
        name: "Redstone Comparator (deprecated)",
        txr_x: 15,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x6C0090,
    },
    BlockInfo {
        name: "Daylight Sensor",
        txr_x: 6,
        txr_y: 15,
        variant_mask: 0x00,
        flags: 0x4C8090,
    },
    BlockInfo {
        name: "Block of Redstone",
        txr_x: 14,
        txr_y: 15,
        variant_mask: 0x00,
        flags: 0x420001,
    },
    BlockInfo {
        name: "Nether Quartz Ore",
        txr_x: 8,
        txr_y: 17,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Hopper",
        txr_x: 13,
        txr_y: 15,
        variant_mask: 0x00,
        flags: 0xC0002,
    },
    BlockInfo {
        name: "Block of Quartz",
        txr_x: 7,
        txr_y: 17,
        variant_mask: 0x05,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Quartz Stairs",
        txr_x: 7,
        txr_y: 17,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Activator Rail",
        txr_x: 10,
        txr_y: 17,
        variant_mask: 0x00,
        flags: 0x52810A0,
    },
    BlockInfo {
        name: "Dropper",
        txr_x: 14,
        txr_y: 3,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Colored Terracotta",
        txr_x: 0,
        txr_y: 16,
        variant_mask: 0x0f,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Stained Glass Pane",
        txr_x: 0,
        txr_y: 20,
        variant_mask: 0x0f,
        flags: 0x40C0840,
    },
    BlockInfo {
        name: "Acacia Leaves",
        txr_x: 11,
        txr_y: 19,
        variant_mask: 0x03,
        flags: 0x4005001,
    },
    BlockInfo {
        name: "Acacia Log",
        txr_x: 13,
        txr_y: 19,
        variant_mask: 0x13,
        flags: 0x22001,
    },
    BlockInfo {
        name: "Acacia Stairs",
        txr_x: 0,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Dark Oak Stairs",
        txr_x: 1,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Slime Block",
        txr_x: 3,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x60801,
    },
    BlockInfo {
        name: "Barrier",
        txr_x: 14,
        txr_y: 25,
        variant_mask: 0x00,
        flags: 0x4001001,
    },
    BlockInfo {
        name: "Iron Trapdoor",
        txr_x: 2,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Prismarine",
        txr_x: 12,
        txr_y: 22,
        variant_mask: 0x03,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Sea Lantern",
        txr_x: 14,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Hay Bale",
        txr_x: 10,
        txr_y: 15,
        variant_mask: 0x03,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Carpet",
        txr_x: 0,
        txr_y: 4,
        variant_mask: 0x1f,
        flags: 0x2C0080,
    },
    BlockInfo {
        name: "Terracotta",
        txr_x: 0,
        txr_y: 17,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Block of Coal",
        txr_x: 13,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Packed Ice",
        txr_x: 12,
        txr_y: 17,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Sunflower",
        txr_x: 0,
        txr_y: 18,
        variant_mask: 0x07,
        flags: 0x2010A0,
    },
    BlockInfo {
        name: "Banner",
        txr_x: 0,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Wall Banner",
        txr_x: 0,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Daylight Detector",
        txr_x: 13,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x4C8090,
    },
    BlockInfo {
        name: "Red Sandstone",
        txr_x: 12,
        txr_y: 19,
        variant_mask: 0x03,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Red Sandstone Stairs",
        txr_x: 12,
        txr_y: 19,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Double Red Sandstone Slab",
        txr_x: 12,
        txr_y: 19,
        variant_mask: 0x07,
        flags: 0x24020001,
    },
    BlockInfo {
        name: "Red Sandstone Slab",
        txr_x: 12,
        txr_y: 19,
        variant_mask: 0x07,
        flags: 0x41C0008,
    },
    BlockInfo {
        name: "Spruce Fence Gate",
        txr_x: 6,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Birch Fence Gate",
        txr_x: 6,
        txr_y: 13,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Jungle Fence Gate",
        txr_x: 7,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Dark Oak Fence Gate",
        txr_x: 1,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Acacia Fence Gate",
        txr_x: 0,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Spruce Fence",
        txr_x: 6,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Birch Fence",
        txr_x: 6,
        txr_y: 13,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Jungle Fence",
        txr_x: 7,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Dark Oak Fence",
        txr_x: 1,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Acacia Fence",
        txr_x: 0,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Spruce Door",
        txr_x: 1,
        txr_y: 23,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Birch Door",
        txr_x: 3,
        txr_y: 23,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Jungle Door",
        txr_x: 5,
        txr_y: 23,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Acacia Door",
        txr_x: 7,
        txr_y: 23,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Dark Oak Door",
        txr_x: 9,
        txr_y: 23,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "End Rod",
        txr_x: 12,
        txr_y: 23,
        variant_mask: 0x00,
        flags: 0x250200,
    },
    BlockInfo {
        name: "Chorus Plant",
        txr_x: 13,
        txr_y: 23,
        variant_mask: 0x00,
        flags: 0x2C0002,
    },
    BlockInfo {
        name: "Chorus Flower",
        txr_x: 14,
        txr_y: 23,
        variant_mask: 0x00,
        flags: 0x2C0002,
    },
    BlockInfo {
        name: "Purpur Block",
        txr_x: 0,
        txr_y: 24,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Purpur Pillar",
        txr_x: 2,
        txr_y: 24,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Purpur Stairs",
        txr_x: 0,
        txr_y: 24,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Double Purpur Slab",
        txr_x: 0,
        txr_y: 24,
        variant_mask: 0x07,
        flags: 0x24020001,
    },
    BlockInfo {
        name: "Purpur Slab",
        txr_x: 0,
        txr_y: 24,
        variant_mask: 0x07,
        flags: 0x41C0008,
    },
    BlockInfo {
        name: "End Stone Bricks",
        txr_x: 3,
        txr_y: 24,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Beetroot Seeds",
        txr_x: 4,
        txr_y: 24,
        variant_mask: 0x00,
        flags: 0x2010A0,
    },
    BlockInfo {
        name: "Dirt Path",
        txr_x: 8,
        txr_y: 24,
        variant_mask: 0x00,
        flags: 0x1C0002,
    },
    BlockInfo {
        name: "End Gateway",
        txr_x: 8,
        txr_y: 11,
        variant_mask: 0x00,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Repeating Command Block",
        txr_x: 14,
        txr_y: 24,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Chain Command Block",
        txr_x: 2,
        txr_y: 25,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Frosted Ice",
        txr_x: 6,
        txr_y: 25,
        variant_mask: 0x00,
        flags: 0x801,
    },
    BlockInfo {
        name: "Magma Block",
        txr_x: 0,
        txr_y: 26,
        variant_mask: 0x00,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Nether Wart Block",
        txr_x: 1,
        txr_y: 26,
        variant_mask: 0x01,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Red Nether Bricks",
        txr_x: 2,
        txr_y: 26,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Bone Block",
        txr_x: 4,
        txr_y: 26,
        variant_mask: 0x13,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Structure Void",
        txr_x: 1,
        txr_y: 8,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Observer",
        txr_x: 4,
        txr_y: 33,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "White Shulker Box",
        txr_x: 0,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Orange Shulker Box",
        txr_x: 1,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Magenta Shulker Box",
        txr_x: 2,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Light Blue Shulker Box",
        txr_x: 3,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Yellow Shulker Box",
        txr_x: 4,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Lime Shulker Box",
        txr_x: 5,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Pink Shulker Box",
        txr_x: 6,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Gray Shulker Box",
        txr_x: 7,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Light Grey Shulker Box",
        txr_x: 8,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Cyan Shulker Box",
        txr_x: 9,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Purple Shulker Box",
        txr_x: 10,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Blue Shulker Box",
        txr_x: 11,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Brown Shulker Box",
        txr_x: 12,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Green Shulker Box",
        txr_x: 13,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Red Shulker Box",
        txr_x: 14,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Black Shulker Box",
        txr_x: 15,
        txr_y: 27,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "White Glazed Terracotta",
        txr_x: 0,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Orange Glazed Terracotta",
        txr_x: 1,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Magenta Glazed Terracotta",
        txr_x: 2,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Light Blue Glazed Terracotta",
        txr_x: 3,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Yellow Glazed Terracotta",
        txr_x: 4,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Lime Glazed Terracotta",
        txr_x: 5,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Pink Glazed Terracotta",
        txr_x: 6,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Gray Glazed Terracotta",
        txr_x: 7,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Light Grey Glazed Terracotta",
        txr_x: 8,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Cyan Glazed Terracotta",
        txr_x: 9,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Purple Glazed Terracotta",
        txr_x: 10,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Blue Glazed Terracotta",
        txr_x: 11,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Brown Glazed Terracotta",
        txr_x: 12,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Green Glazed Terracotta",
        txr_x: 13,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Red Glazed Terracotta",
        txr_x: 14,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Black Glazed Terracotta",
        txr_x: 15,
        txr_y: 28,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Concrete",
        txr_x: 0,
        txr_y: 29,
        variant_mask: 0x0f,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Concrete Powder",
        txr_x: 0,
        txr_y: 30,
        variant_mask: 0x0f,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Unknown Block",
        txr_x: 1,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Unknown Block",
        txr_x: 1,
        txr_y: 1,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Structure Block",
        txr_x: 10,
        txr_y: 25,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Air",
        txr_x: 13,
        txr_y: 14,
        variant_mask: 0x00,
        flags: 0x800000,
    },
    BlockInfo {
        name: "Prismarine Stairs",
        txr_x: 12,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Prismarine Brick Stairs",
        txr_x: 10,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Dark Prismarine Stairs",
        txr_x: 11,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Spruce Trapdoor",
        txr_x: 12,
        txr_y: 34,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Birch Trapdoor",
        txr_x: 13,
        txr_y: 34,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Jungle Trapdoor",
        txr_x: 14,
        txr_y: 34,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Acacia Trapdoor",
        txr_x: 15,
        txr_y: 34,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Dark Oak Trapdoor",
        txr_x: 0,
        txr_y: 35,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Spruce Button",
        txr_x: 6,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Birch Button",
        txr_x: 6,
        txr_y: 13,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Jungle Button",
        txr_x: 7,
        txr_y: 12,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Acacia Button",
        txr_x: 0,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Dark Oak Button",
        txr_x: 1,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Pale Oak Button",
        txr_x: 8,
        txr_y: 67,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Pale Oak Door",
        txr_x: 4,
        txr_y: 67,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Pale Oak Fence",
        txr_x: 8,
        txr_y: 67,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Pale Oak Fence Gate",
        txr_x: 8,
        txr_y: 67,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Pale Oak Stairs",
        txr_x: 8,
        txr_y: 67,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Stripped Oak Log",
        txr_x: 6,
        txr_y: 34,
        variant_mask: 0x03,
        flags: 0x22001,
    },
    BlockInfo {
        name: "Stripped Acacia Log",
        txr_x: 10,
        txr_y: 34,
        variant_mask: 0x03,
        flags: 0x22001,
    },
    BlockInfo {
        name: "Stripped Oak Wood",
        txr_x: 0,
        txr_y: 34,
        variant_mask: 0x03,
        flags: 0x22001,
    },
    BlockInfo {
        name: "Stripped Acacia Wood",
        txr_x: 4,
        txr_y: 34,
        variant_mask: 0x03,
        flags: 0x22001,
    },
    BlockInfo {
        name: "Orange Banner",
        txr_x: 1,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Magenta Banner",
        txr_x: 2,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Light Blue Banner",
        txr_x: 3,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Yellow Banner",
        txr_x: 4,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Lime Banner",
        txr_x: 5,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Pink Banner",
        txr_x: 6,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Gray Banner",
        txr_x: 7,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Light Gray Banner",
        txr_x: 8,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Cyan Banner",
        txr_x: 9,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Purple Banner",
        txr_x: 10,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Blue Banner",
        txr_x: 11,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Brown Banner",
        txr_x: 12,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Green Banner",
        txr_x: 13,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Red Banner",
        txr_x: 14,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Black Banner",
        txr_x: 15,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x40200,
    },
    BlockInfo {
        name: "Orange Wall Banner",
        txr_x: 1,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Magenta Wall Banner",
        txr_x: 2,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Light Blue Wall Banner",
        txr_x: 3,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Yellow Wall Banner",
        txr_x: 4,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Lime Wall Banner",
        txr_x: 5,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Pink Wall Banner",
        txr_x: 6,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Gray Wall Banner",
        txr_x: 7,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Light Gray Wall Banner",
        txr_x: 8,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Cyan Wall Banner",
        txr_x: 9,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Purple Wall Banner",
        txr_x: 10,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Blue Wall Banner",
        txr_x: 11,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Brown Wall Banner",
        txr_x: 12,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Green Wall Banner",
        txr_x: 13,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Red Wall Banner",
        txr_x: 14,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Black Wall Banner",
        txr_x: 15,
        txr_y: 29,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Tall Seagrass",
        txr_x: 14,
        txr_y: 33,
        variant_mask: 0x00,
        flags: 0x22010A0,
    },
    BlockInfo {
        name: "Seagrass",
        txr_x: 15,
        txr_y: 33,
        variant_mask: 0x00,
        flags: 0x2201480,
    },
    BlockInfo {
        name: "Smooth Stone",
        txr_x: 10,
        txr_y: 23,
        variant_mask: 0x03,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Blue Ice",
        txr_x: 13,
        txr_y: 33,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Dried Kelp Block",
        txr_x: 7,
        txr_y: 33,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Kelp",
        txr_x: 11,
        txr_y: 33,
        variant_mask: 0x00,
        flags: 0x2201480,
    },
    BlockInfo {
        name: "Coral Block",
        txr_x: 6,
        txr_y: 35,
        variant_mask: 0x07,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Dead Coral Block",
        txr_x: 1,
        txr_y: 35,
        variant_mask: 0x07,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Coral",
        txr_x: 11,
        txr_y: 35,
        variant_mask: 0x07,
        flags: 0x4201480,
    },
    BlockInfo {
        name: "Coral Fan",
        txr_x: 11,
        txr_y: 35,
        variant_mask: 0x07,
        flags: 0x4201480,
    },
    BlockInfo {
        name: "Dead Coral Fan",
        txr_x: 5,
        txr_y: 36,
        variant_mask: 0x07,
        flags: 0x4201480,
    },
    BlockInfo {
        name: "Coral Wall Fan",
        txr_x: 11,
        txr_y: 35,
        variant_mask: 0x07,
        flags: 0x4201480,
    },
    BlockInfo {
        name: "Dead Coral Wall Fan",
        txr_x: 5,
        txr_y: 36,
        variant_mask: 0x07,
        flags: 0x4201480,
    },
    BlockInfo {
        name: "Conduit",
        txr_x: 13,
        txr_y: 36,
        variant_mask: 0x00,
        flags: 0x42D1010,
    },
    BlockInfo {
        name: "Sea Pickle",
        txr_x: 12,
        txr_y: 33,
        variant_mask: 0x03,
        flags: 0x42D1200,
    },
    BlockInfo {
        name: "Turtle Egg",
        txr_x: 10,
        txr_y: 36,
        variant_mask: 0x00,
        flags: 0x2C1200,
    },
    BlockInfo {
        name: "Dead Coral",
        txr_x: 14,
        txr_y: 36,
        variant_mask: 0x07,
        flags: 0x4201480,
    },
    BlockInfo {
        name: "Standing Sign",
        txr_x: 0,
        txr_y: 22,
        variant_mask: 0x30,
        flags: 0x40C0200,
    },
    BlockInfo {
        name: "Sweet Berry Bush",
        txr_x: 12,
        txr_y: 37,
        variant_mask: 0x00,
        flags: 0x201480,
    },
    BlockInfo {
        name: "Bamboo",
        txr_x: 10,
        txr_y: 37,
        variant_mask: 0x00,
        flags: 0x41200,
    },
    BlockInfo {
        name: "Double Andesite Slab",
        txr_x: 4,
        txr_y: 22,
        variant_mask: 0x07,
        flags: 0x24020001,
    },
    BlockInfo {
        name: "Andesite Slab",
        txr_x: 4,
        txr_y: 22,
        variant_mask: 0x07,
        flags: 0x41C0008,
    },
    BlockInfo {
        name: "Jigsaw",
        txr_x: 13,
        txr_y: 39,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Composter",
        txr_x: 11,
        txr_y: 38,
        variant_mask: 0x00,
        flags: 0x1C0002,
    },
    BlockInfo {
        name: "Barrel",
        txr_x: 0,
        txr_y: 38,
        variant_mask: 0x00,
        flags: 0x1,
    },
    BlockInfo {
        name: "Stone Cutter",
        txr_x: 4,
        txr_y: 41,
        variant_mask: 0x00,
        flags: 0x1C1002,
    },
    BlockInfo {
        name: "Grindstone",
        txr_x: 10,
        txr_y: 39,
        variant_mask: 0x00,
        flags: 0xC0002,
    },
    BlockInfo {
        name: "Lectern",
        txr_x: 0,
        txr_y: 40,
        variant_mask: 0x00,
        flags: 0xC0002,
    },
    BlockInfo {
        name: "Bell",
        txr_x: 4,
        txr_y: 38,
        variant_mask: 0x00,
        flags: 0xC1010,
    },
    BlockInfo {
        name: "Lantern",
        txr_x: 11,
        txr_y: 37,
        variant_mask: 0x1E,
        flags: 0x4051200,
    },
    BlockInfo {
        name: "Campfire",
        txr_x: 0,
        txr_y: 39,
        variant_mask: 0x0c,
        flags: 0x4051090,
    },
    BlockInfo {
        name: "Scaffolding",
        txr_x: 8,
        txr_y: 40,
        variant_mask: 0x00,
        flags: 0x4041010,
    },
    BlockInfo {
        name: "Bee Nest",
        txr_x: 12,
        txr_y: 41,
        variant_mask: 0x20,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Honey Block",
        txr_x: 3,
        txr_y: 42,
        variant_mask: 0x00,
        flags: 0x40801,
    },
    BlockInfo {
        name: "Honeycomb Block",
        txr_x: 4,
        txr_y: 42,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Crying Obsidian",
        txr_x: 2,
        txr_y: 45,
        variant_mask: 0x01,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Respawn Anchor",
        txr_x: 3,
        txr_y: 45,
        variant_mask: 0x07,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Crimson Trapdoor",
        txr_x: 9,
        txr_y: 43,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Warped Trapdoor",
        txr_x: 9,
        txr_y: 44,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Crimson Button",
        txr_x: 8,
        txr_y: 43,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Warped Button",
        txr_x: 8,
        txr_y: 44,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Polished Blackstone Button",
        txr_x: 4,
        txr_y: 46,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Crimson Fence",
        txr_x: 8,
        txr_y: 43,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Warped Fence",
        txr_x: 8,
        txr_y: 44,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Crimson Fence Gate",
        txr_x: 8,
        txr_y: 43,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Warped Fence Gate",
        txr_x: 8,
        txr_y: 44,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Crimson Door",
        txr_x: 11,
        txr_y: 43,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Warped Door",
        txr_x: 11,
        txr_y: 44,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Pale Oak Trapdoor",
        txr_x: 10,
        txr_y: 67,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Pale Hanging Moss",
        txr_x: 1,
        txr_y: 68,
        variant_mask: 0x00,
        flags: 0x2010A0,
    },
    BlockInfo {
        name: "Pale Moss Carpet",
        txr_x: 13,
        txr_y: 67,
        variant_mask: 0x00,
        flags: 0x12C1080,
    },
    BlockInfo {
        name: "Double Crimson Slab",
        txr_x: 8,
        txr_y: 43,
        variant_mask: 0x07,
        flags: 0x24020001,
    },
    BlockInfo {
        name: "Crimson Slab",
        txr_x: 8,
        txr_y: 43,
        variant_mask: 0x07,
        flags: 0x41C0008,
    },
    BlockInfo {
        name: "Soul Torch",
        txr_x: 11,
        txr_y: 42,
        variant_mask: 0x00,
        flags: 0x211490,
    },
    BlockInfo {
        name: "Weeping Vines",
        txr_x: 15,
        txr_y: 43,
        variant_mask: 0x23,
        flags: 0x42010A0,
    },
    BlockInfo {
        name: "Iron Chain",
        txr_x: 12,
        txr_y: 46,
        variant_mask: 0x33,
        flags: 0x4041200,
    },
    BlockInfo {
        name: "Stone Stairs",
        txr_x: 1,
        txr_y: 0,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Granite Stairs",
        txr_x: 8,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Polished Granite Stairs",
        txr_x: 9,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Smooth Quartz Stairs",
        txr_x: 7,
        txr_y: 17,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Diorite Stairs",
        txr_x: 6,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Polished Diorite Stairs",
        txr_x: 7,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "End Stone Brick Stairs",
        txr_x: 3,
        txr_y: 24,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Andesite Stairs",
        txr_x: 4,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Polished Andesite Stairs",
        txr_x: 5,
        txr_y: 22,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Red Nether Brick Stairs",
        txr_x: 2,
        txr_y: 26,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Mossy Stone Brick Stairs",
        txr_x: 4,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Mossy Cobblestone Stairs",
        txr_x: 4,
        txr_y: 2,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Smooth Sandstone Stairs",
        txr_x: 0,
        txr_y: 11,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Smooth Red Sandstone Stairs",
        txr_x: 12,
        txr_y: 19,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Crimson Stairs",
        txr_x: 8,
        txr_y: 43,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Warped Stairs",
        txr_x: 8,
        txr_y: 44,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Blackstone Stairs",
        txr_x: 0,
        txr_y: 46,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Polished Blackstone Stairs",
        txr_x: 4,
        txr_y: 46,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Polished Blackstone Brick Stairs",
        txr_x: 5,
        txr_y: 46,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Candle",
        txr_x: 14,
        txr_y: 46,
        variant_mask: 0x00,
        flags: 0x4241600,
    },
    BlockInfo {
        name: "Lit Candle",
        txr_x: 15,
        txr_y: 46,
        variant_mask: 0x30,
        flags: 0x251600,
    },
    BlockInfo {
        name: "White Candle",
        txr_x: 0,
        txr_y: 47,
        variant_mask: 0x0f,
        flags: 0x4241600,
    },
    BlockInfo {
        name: "Lit White Candle",
        txr_x: 0,
        txr_y: 48,
        variant_mask: 0x30,
        flags: 0x251600,
    },
    BlockInfo {
        name: "Block of Amethyst",
        txr_x: 0,
        txr_y: 49,
        variant_mask: 0x3f,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Small Amethyst Bud",
        txr_x: 1,
        txr_y: 49,
        variant_mask: 0x03,
        flags: 0x4011480,
    },
    BlockInfo {
        name: "Pointed Dripstone",
        txr_x: 9,
        txr_y: 49,
        variant_mask: 0x00,
        flags: 0x4001400,
    },
    BlockInfo {
        name: "Cut Copper Stairs",
        txr_x: 9,
        txr_y: 50,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Exposed Cut Copper Stairs",
        txr_x: 10,
        txr_y: 50,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Weathered Cut Copper Stairs",
        txr_x: 11,
        txr_y: 50,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Oxidized Cut Copper Stairs",
        txr_x: 12,
        txr_y: 50,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Lightning Rod",
        txr_x: 13,
        txr_y: 50,
        variant_mask: 0x30,
        flags: 0x4640200,
    },
    BlockInfo {
        name: "(unused)",
        txr_x: 10,
        txr_y: 11,
        variant_mask: 0x00,
        flags: 0x2C0200,
    },
    BlockInfo {
        name: "Double Cut Copper Slab",
        txr_x: 9,
        txr_y: 50,
        variant_mask: 0x17,
        flags: 0x24020001,
    },
    BlockInfo {
        name: "Cut Copper Slab",
        txr_x: 9,
        txr_y: 50,
        variant_mask: 0x17,
        flags: 0x41C0008,
    },
    BlockInfo {
        name: "Waxed Cut Copper Stairs",
        txr_x: 9,
        txr_y: 50,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "(unused)",
        txr_x: 6,
        txr_y: 6,
        variant_mask: 0x00,
        flags: 0x2C0002,
    },
    BlockInfo {
        name: "Waxed Exposed Cut Copper Stairs",
        txr_x: 10,
        txr_y: 50,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Waxed Weathered Cut Copper Stairs",
        txr_x: 11,
        txr_y: 50,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Waxed Oxidized Cut Copper Stairs",
        txr_x: 12,
        txr_y: 50,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Cave Vines",
        txr_x: 15,
        txr_y: 50,
        variant_mask: 0x01,
        flags: 0x201020,
    },
    BlockInfo {
        name: "Cave Vines lit",
        txr_x: 1,
        txr_y: 51,
        variant_mask: 0x01,
        flags: 0x211020,
    },
    BlockInfo {
        name: "Spore Blossom",
        txr_x: 3,
        txr_y: 51,
        variant_mask: 0x00,
        flags: 0x2010A0,
    },
    BlockInfo {
        name: "Azalea",
        txr_x: 5,
        txr_y: 51,
        variant_mask: 0x01,
        flags: 0x2C1022,
    },
    BlockInfo {
        name: "Big Dripleaf",
        txr_x: 3,
        txr_y: 52,
        variant_mask: 0x01,
        flags: 0x42010A0,
    },
    BlockInfo {
        name: "Small Dripleaf",
        txr_x: 7,
        txr_y: 52,
        variant_mask: 0x00,
        flags: 0x42010A0,
    },
    BlockInfo {
        name: "Glow Lichen",
        txr_x: 14,
        txr_y: 52,
        variant_mask: 0x00,
        flags: 0x5211160,
    },
    BlockInfo {
        name: "Sculk Sensor",
        txr_x: 15,
        txr_y: 52,
        variant_mask: 0x04,
        flags: 0x44D1008,
    },
    BlockInfo {
        name: "Cobbled Deepslate Stairs",
        txr_x: 6,
        txr_y: 53,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Polished Deepslate Stairs",
        txr_x: 8,
        txr_y: 53,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Deepslate Brick Stairs",
        txr_x: 9,
        txr_y: 53,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Deepslate Tile Stairs",
        txr_x: 10,
        txr_y: 53,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Mangrove Log",
        txr_x: 12,
        txr_y: 54,
        variant_mask: 0x13,
        flags: 0x22001,
    },
    BlockInfo {
        name: "Decorated Pot",
        txr_x: 3,
        txr_y: 61,
        variant_mask: 0x00,
        flags: 0x40C0002,
    },
    BlockInfo {
        name: "Mangrove Door",
        txr_x: 10,
        txr_y: 54,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Mangrove Trapdoor",
        txr_x: 5,
        txr_y: 55,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Mangrove Propagule",
        txr_x: 1,
        txr_y: 55,
        variant_mask: 0x00,
        flags: 0x4201480,
    },
    BlockInfo {
        name: "Mangrove Roots",
        txr_x: 3,
        txr_y: 55,
        variant_mask: 0x00,
        flags: 0x41001,
    },
    BlockInfo {
        name: "Muddy Mangrove Roots",
        txr_x: 8,
        txr_y: 55,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Stripped Mangrove Log",
        txr_x: 14,
        txr_y: 54,
        variant_mask: 0x03,
        flags: 0x22001,
    },
    BlockInfo {
        name: "Stripped Mangrove Wood",
        txr_x: 15,
        txr_y: 54,
        variant_mask: 0x03,
        flags: 0x22001,
    },
    BlockInfo {
        name: "Mangrove Stairs",
        txr_x: 0,
        txr_y: 55,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Mud Brick Stairs",
        txr_x: 7,
        txr_y: 55,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Mangrove Sign",
        txr_x: 0,
        txr_y: 55,
        variant_mask: 0x30,
        flags: 0x40C0200,
    },
    BlockInfo {
        name: "Mangrove Wall Sign",
        txr_x: 0,
        txr_y: 55,
        variant_mask: 0x38,
        flags: 0x42C0100,
    },
    BlockInfo {
        name: "Resin Brick Stairs",
        txr_x: 1,
        txr_y: 67,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Mangrove Button",
        txr_x: 0,
        txr_y: 55,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Mangrove Fence",
        txr_x: 0,
        txr_y: 55,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Mangrove Fence Gate",
        txr_x: 0,
        txr_y: 55,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Sculk Shrieker",
        txr_x: 7,
        txr_y: 56,
        variant_mask: 0x00,
        flags: 0x1C1002,
    },
    BlockInfo {
        name: "Sculk Vein",
        txr_x: 12,
        txr_y: 56,
        variant_mask: 0x00,
        flags: 0x5201160,
    },
    BlockInfo {
        name: "Frogspawn",
        txr_x: 8,
        txr_y: 54,
        variant_mask: 0x00,
        flags: 0x1201080,
    },
    BlockInfo {
        name: "Ochre Froglight",
        txr_x: 11,
        txr_y: 55,
        variant_mask: 0x03,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Mangrove Leaves",
        txr_x: 11,
        txr_y: 54,
        variant_mask: 0x3f,
        flags: 0x4005001,
    },
    BlockInfo {
        name: "Cherry Button",
        txr_x: 8,
        txr_y: 57,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Cherry Door",
        txr_x: 4,
        txr_y: 57,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Cherry Fence",
        txr_x: 8,
        txr_y: 57,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Cherry Fence Gate",
        txr_x: 8,
        txr_y: 57,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Resin Clump",
        txr_x: 2,
        txr_y: 67,
        variant_mask: 0x00,
        flags: 0x5201160,
    },
    BlockInfo {
        name: "Cherry Stairs",
        txr_x: 8,
        txr_y: 57,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Cherry Trapdoor",
        txr_x: 10,
        txr_y: 57,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Bamboo Button",
        txr_x: 14,
        txr_y: 60,
        variant_mask: 0x00,
        flags: 0x2C0100,
    },
    BlockInfo {
        name: "Bamboo Door",
        txr_x: 8,
        txr_y: 60,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Bamboo Fence",
        txr_x: 12,
        txr_y: 60,
        variant_mask: 0x00,
        flags: 0x141C0010,
    },
    BlockInfo {
        name: "Bamboo Fence Gate",
        txr_x: 11,
        txr_y: 60,
        variant_mask: 0x00,
        flags: 0x81C8010,
    },
    BlockInfo {
        name: "Creaking Heart",
        txr_x: 5,
        txr_y: 68,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Bamboo Stairs",
        txr_x: 14,
        txr_y: 60,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Bamboo Trapdoor",
        txr_x: 15,
        txr_y: 60,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Bamboo Mosaic Stairs",
        txr_x: 13,
        txr_y: 60,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Pink Petals",
        txr_x: 11,
        txr_y: 57,
        variant_mask: 0x30,
        flags: 0x2010A0,
    },
    BlockInfo {
        name: "Pitcher Plant",
        txr_x: 5,
        txr_y: 58,
        variant_mask: 0x00,
        flags: 0x2C10A0,
    },
    BlockInfo {
        name: "Sniffer Egg",
        txr_x: 10,
        txr_y: 58,
        variant_mask: 0x00,
        flags: 0xC0002,
    },
    BlockInfo {
        name: "Suspicious Gravel",
        txr_x: 10,
        txr_y: 59,
        variant_mask: 0x04,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Torchflower",
        txr_x: 3,
        txr_y: 60,
        variant_mask: 0x00,
        flags: 0x2010A0,
    },
    BlockInfo {
        name: "Oak Wall Hanging Sign",
        txr_x: 0,
        txr_y: 34,
        variant_mask: 0x3c,
        flags: 0x42C0200,
    },
    BlockInfo {
        name: "Oak Hanging Sign",
        txr_x: 0,
        txr_y: 34,
        variant_mask: 0x20,
        flags: 0x42C0200,
    },
    BlockInfo {
        name: "Birch Hanging Sign",
        txr_x: 2,
        txr_y: 34,
        variant_mask: 0x20,
        flags: 0x42C0200,
    },
    BlockInfo {
        name: "Acacia Hanging Sign",
        txr_x: 4,
        txr_y: 34,
        variant_mask: 0x20,
        flags: 0x42C0200,
    },
    BlockInfo {
        name: "Crimson Hanging Sign",
        txr_x: 13,
        txr_y: 43,
        variant_mask: 0x20,
        flags: 0x42C0200,
    },
    BlockInfo {
        name: "Mangrove Hanging Sign",
        txr_x: 15,
        txr_y: 54,
        variant_mask: 0x20,
        flags: 0x42C0200,
    },
    BlockInfo {
        name: "Bamboo Hanging Sign",
        txr_x: 11,
        txr_y: 60,
        variant_mask: 0x20,
        flags: 0x42C0200,
    },
    BlockInfo {
        name: "Trial Spawner",
        txr_x: 13,
        txr_y: 64,
        variant_mask: 0x00,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Vault",
        txr_x: 12,
        txr_y: 65,
        variant_mask: 0x00,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Crafter",
        txr_x: 10,
        txr_y: 62,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Heavy Core",
        txr_x: 9,
        txr_y: 63,
        variant_mask: 0x00,
        flags: 0x42D1010,
    },
    BlockInfo {
        name: "Copper Bulb",
        txr_x: 10,
        txr_y: 61,
        variant_mask: 0x0F,
        flags: 0x30001,
    },
    BlockInfo {
        name: "Copper Grate",
        txr_x: 0,
        txr_y: 62,
        variant_mask: 0x07,
        flags: 0x4021001,
    },
    BlockInfo {
        name: "Tuff Stairs",
        txr_x: 7,
        txr_y: 49,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Polished Tuff Stairs",
        txr_x: 3,
        txr_y: 64,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Tuff Brick Stairs",
        txr_x: 15,
        txr_y: 64,
        variant_mask: 0x00,
        flags: 0x41C0004,
    },
    BlockInfo {
        name: "Copper Trapdoor",
        txr_x: 1,
        txr_y: 62,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Exposed Copper Trapdoor",
        txr_x: 8,
        txr_y: 63,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Weathered Copper Trapdoor",
        txr_x: 8,
        txr_y: 66,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Oxidized Copper Trapdoor",
        txr_x: 2,
        txr_y: 64,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Waxed Copper Trapdoor",
        txr_x: 1,
        txr_y: 62,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Waxed Exposed Copper Trapdoor",
        txr_x: 8,
        txr_y: 63,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Waxed Weathered Copper Trapdoor",
        txr_x: 8,
        txr_y: 66,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Waxed Oxidized Copper Trapdoor",
        txr_x: 2,
        txr_y: 64,
        variant_mask: 0x00,
        flags: 0x40C9090,
    },
    BlockInfo {
        name: "Copper Door",
        txr_x: 15,
        txr_y: 61,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Exposed Copper Door",
        txr_x: 6,
        txr_y: 63,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Weathered Copper Door",
        txr_x: 6,
        txr_y: 66,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Oxidized Copper Door",
        txr_x: 0,
        txr_y: 64,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Waxed Copper Door",
        txr_x: 15,
        txr_y: 61,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Waxed Exposed Copper Door",
        txr_x: 6,
        txr_y: 63,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Waxed Weathered Copper Door",
        txr_x: 6,
        txr_y: 66,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Waxed Oxidized Copper Door",
        txr_x: 0,
        txr_y: 64,
        variant_mask: 0x00,
        flags: 0xC9010,
    },
    BlockInfo {
        name: "Test Block",
        txr_x: 6,
        txr_y: 69,
        variant_mask: 0x00,
        flags: 0x20001,
    },
    BlockInfo {
        name: "Dried Ghast",
        txr_x: 15,
        txr_y: 69,
        variant_mask: 0x00,
        flags: 0x40C0002,
    },
    BlockInfo {
        name: "Copper Bars",
        txr_x: 6,
        txr_y: 71,
        variant_mask: 0x30,
        flags: 0x40C1040,
    },
    BlockInfo {
        name: "Waxed Copper Bars",
        txr_x: 6,
        txr_y: 71,
        variant_mask: 0x30,
        flags: 0x40C1040,
    },
    BlockInfo {
        name: "Copper Torch",
        txr_x: 14,
        txr_y: 71,
        variant_mask: 0x00,
        flags: 0x211490,
    },
    BlockInfo {
        name: "Waxed Lightning Rod",
        txr_x: 13,
        txr_y: 50,
        variant_mask: 0x30,
        flags: 0x4640200,
    },
    BlockInfo {
        name: "Copper Chest",
        txr_x: 8,
        txr_y: 72,
        variant_mask: 0x20,
        flags: 0x40C0002,
    },
    BlockInfo {
        name: "Oxidised Copper Chest",
        txr_x: 4,
        txr_y: 74,
        variant_mask: 0x20,
        flags: 0x40C0002,
    },
    BlockInfo {
        name: "Waxed Copper Chest",
        txr_x: 8,
        txr_y: 72,
        variant_mask: 0x20,
        flags: 0x40C0002,
    },
    BlockInfo {
        name: "Waxed Oxidised Copper Chest",
        txr_x: 4,
        txr_y: 74,
        variant_mask: 0x20,
        flags: 0x40C0002,
    },
    BlockInfo {
        name: "Acacia Shelf",
        txr_x: 0,
        txr_y: 76,
        variant_mask: 0x38,
        flags: 0x40C0010,
    },
    BlockInfo {
        name: "Pale Oak Shelf",
        txr_x: 8,
        txr_y: 77,
        variant_mask: 0x18,
        flags: 0x40C0010,
    },
    BlockInfo {
        name: "Copper Golem Statue",
        txr_x: 5,
        txr_y: 50,
        variant_mask: 0x30,
        flags: 0x40C0002,
    },
    BlockInfo {
        name: "Waxed Copper Golem Statue",
        txr_x: 5,
        txr_y: 50,
        variant_mask: 0x30,
        flags: 0x40C0002,
    },
];
