// Auto-generated by tools/gen_block_entity_models.py.
//
// Do not hand-edit; change the script and regenerate.
//
// Geometry for blocks the game draws from code rather than a model
// JSON. Parsing the vanilla assets finds nothing for these, so without
// this table a chest is a featureless cube and a bell is a bare post.

use crate::block_models::{ModelElement, ModelFace};

/// A block-state condition; empty `values` never matches.
#[derive(Debug, Clone, Copy)]
pub struct BlockEntityCondition {
    pub key: &'static str,
    pub values: &'static [&'static str],
}

/// One form of a code-drawn block.
#[derive(Debug, Clone, Copy)]
pub struct BlockEntityVariant {
    /// All must match; empty means always.
    pub when: &'static [BlockEntityCondition],
    pub elements: &'static [ModelElement],
}

/// Every form of one code-drawn block.
#[derive(Debug, Clone, Copy)]
pub struct BlockEntityModel {
    pub variants: &'static [BlockEntityVariant],
}

#[rustfmt::skip]
static BLOCK_ENTITY_MODELS: &[(&str, BlockEntityModel)] = &[
    ("banner", BlockEntityModel { variants: &[
        BlockEntityVariant { when: &[], elements: &[
            ModelElement { from: [7.33, 0.00, 7.33], to: [8.66, 28.00, 8.66], rotation: None, faces: &[
                ModelFace { face: 0, uv: [11.33, 0.00, 11.66, 0.33], texture: "entity/banner/base" },
                ModelFace { face: 1, uv: [11.66, 0.00, 12.00, 0.33], texture: "entity/banner/base" },
                ModelFace { face: 2, uv: [11.66, 0.33, 12.00, 7.33], texture: "entity/banner/base" },
                ModelFace { face: 3, uv: [11.00, 0.33, 11.33, 7.33], texture: "entity/banner/base" },
                ModelFace { face: 4, uv: [12.00, 0.33, 12.33, 7.33], texture: "entity/banner/base" },
                ModelFace { face: 5, uv: [11.33, 0.33, 11.66, 7.33], texture: "entity/banner/base" },
            ] },
            ModelElement { from: [1.33, 26.67, 7.33], to: [14.66, 28.00, 8.66], rotation: None, faces: &[
                ModelFace { face: 0, uv: [0.33, 10.50, 3.67, 10.83], texture: "entity/banner/base" },
                ModelFace { face: 1, uv: [3.67, 10.50, 7.00, 10.83], texture: "entity/banner/base" },
                ModelFace { face: 2, uv: [3.67, 10.83, 4.00, 11.16], texture: "entity/banner/base" },
                ModelFace { face: 3, uv: [0.00, 10.83, 0.33, 11.16], texture: "entity/banner/base" },
                ModelFace { face: 4, uv: [4.00, 10.83, 7.33, 11.16], texture: "entity/banner/base" },
                ModelFace { face: 5, uv: [0.33, 10.83, 3.67, 11.16], texture: "entity/banner/base" },
            ] },
            ModelElement { from: [1.33, 1.33, 7.67], to: [14.66, 28.00, 8.34], rotation: None, faces: &[
                ModelFace { face: 0, uv: [0.17, 0.00, 3.50, 0.17], texture: "entity/banner/base" },
                ModelFace { face: 1, uv: [3.50, 0.00, 6.83, 0.17], texture: "entity/banner/base" },
                ModelFace { face: 2, uv: [3.50, 0.17, 3.67, 6.84], texture: "entity/banner/base" },
                ModelFace { face: 3, uv: [0.00, 0.17, 0.17, 6.84], texture: "entity/banner/base" },
                ModelFace { face: 4, uv: [3.67, 0.17, 7.00, 6.84], texture: "entity/banner/base" },
                ModelFace { face: 5, uv: [0.17, 0.17, 3.50, 6.84], texture: "entity/banner/base" },
            ] },
        ] },
    ] }),
    ("bell", BlockEntityModel { variants: &[
        BlockEntityVariant { when: &[], elements: &[
            ModelElement { from: [5.00, 6.00, 5.00], to: [11.00, 13.00, 11.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [3.00, 0.00, 6.00, 3.00], texture: "entity/bell/bell_body" },
                ModelFace { face: 1, uv: [6.00, 0.00, 9.00, 3.00], texture: "entity/bell/bell_body" },
                ModelFace { face: 2, uv: [6.00, 3.00, 9.00, 6.50], texture: "entity/bell/bell_body" },
                ModelFace { face: 3, uv: [0.00, 3.00, 3.00, 6.50], texture: "entity/bell/bell_body" },
                ModelFace { face: 4, uv: [9.00, 3.00, 12.00, 6.50], texture: "entity/bell/bell_body" },
                ModelFace { face: 5, uv: [3.00, 3.00, 6.00, 6.50], texture: "entity/bell/bell_body" },
            ] },
            ModelElement { from: [4.00, 4.00, 4.00], to: [12.00, 6.00, 12.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [4.00, 6.50, 8.00, 10.50], texture: "entity/bell/bell_body" },
                ModelFace { face: 1, uv: [8.00, 6.50, 12.00, 10.50], texture: "entity/bell/bell_body" },
                ModelFace { face: 2, uv: [8.00, 10.50, 12.00, 11.50], texture: "entity/bell/bell_body" },
                ModelFace { face: 3, uv: [0.00, 10.50, 4.00, 11.50], texture: "entity/bell/bell_body" },
                ModelFace { face: 4, uv: [12.00, 10.50, 16.00, 11.50], texture: "entity/bell/bell_body" },
                ModelFace { face: 5, uv: [4.00, 10.50, 8.00, 11.50], texture: "entity/bell/bell_body" },
            ] },
        ] },
    ] }),
    ("chest", BlockEntityModel { variants: &[
        BlockEntityVariant { when: &[], elements: &[
            ModelElement { from: [1.00, 0.00, 1.00], to: [15.00, 10.00, 15.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [3.50, 4.75, 7.00, 8.25], texture: "entity/chest/normal" },
                ModelFace { face: 1, uv: [7.00, 4.75, 10.50, 8.25], texture: "entity/chest/normal" },
                ModelFace { face: 2, uv: [7.00, 8.25, 10.50, 10.75], texture: "entity/chest/normal" },
                ModelFace { face: 3, uv: [0.00, 8.25, 3.50, 10.75], texture: "entity/chest/normal" },
                ModelFace { face: 4, uv: [10.50, 8.25, 14.00, 10.75], texture: "entity/chest/normal" },
                ModelFace { face: 5, uv: [3.50, 8.25, 7.00, 10.75], texture: "entity/chest/normal" },
            ] },
            ModelElement { from: [1.00, 10.00, 1.00], to: [15.00, 15.00, 15.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [3.50, 0.00, 7.00, 3.50], texture: "entity/chest/normal" },
                ModelFace { face: 1, uv: [7.00, 0.00, 10.50, 3.50], texture: "entity/chest/normal" },
                ModelFace { face: 2, uv: [7.00, 3.50, 10.50, 4.75], texture: "entity/chest/normal" },
                ModelFace { face: 3, uv: [0.00, 3.50, 3.50, 4.75], texture: "entity/chest/normal" },
                ModelFace { face: 4, uv: [10.50, 3.50, 14.00, 4.75], texture: "entity/chest/normal" },
                ModelFace { face: 5, uv: [3.50, 3.50, 7.00, 4.75], texture: "entity/chest/normal" },
            ] },
            ModelElement { from: [7.00, 8.00, 0.00], to: [9.00, 12.00, 1.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [0.25, 0.00, 0.75, 0.25], texture: "entity/chest/normal" },
                ModelFace { face: 1, uv: [0.75, 0.00, 1.25, 0.25], texture: "entity/chest/normal" },
                ModelFace { face: 2, uv: [0.75, 0.25, 1.00, 1.25], texture: "entity/chest/normal" },
                ModelFace { face: 3, uv: [0.00, 0.25, 0.25, 1.25], texture: "entity/chest/normal" },
                ModelFace { face: 4, uv: [1.00, 0.25, 1.50, 1.25], texture: "entity/chest/normal" },
                ModelFace { face: 5, uv: [0.25, 0.25, 0.75, 1.25], texture: "entity/chest/normal" },
            ] },
        ] },
    ] }),
    ("conduit", BlockEntityModel { variants: &[
        BlockEntityVariant { when: &[], elements: &[
            ModelElement { from: [5.00, 5.00, 5.00], to: [11.00, 11.00, 11.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [3.00, 0.00, 6.00, 6.00], texture: "entity/conduit/base" },
                ModelFace { face: 1, uv: [6.00, 0.00, 9.00, 6.00], texture: "entity/conduit/base" },
                ModelFace { face: 2, uv: [6.00, 6.00, 9.00, 12.00], texture: "entity/conduit/base" },
                ModelFace { face: 3, uv: [0.00, 6.00, 3.00, 12.00], texture: "entity/conduit/base" },
                ModelFace { face: 4, uv: [9.00, 6.00, 12.00, 12.00], texture: "entity/conduit/base" },
                ModelFace { face: 5, uv: [3.00, 6.00, 6.00, 12.00], texture: "entity/conduit/base" },
            ] },
        ] },
    ] }),
    ("ender_chest", BlockEntityModel { variants: &[
        BlockEntityVariant { when: &[], elements: &[
            ModelElement { from: [1.00, 0.00, 1.00], to: [15.00, 10.00, 15.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [3.50, 4.75, 7.00, 8.25], texture: "entity/chest/ender" },
                ModelFace { face: 1, uv: [7.00, 4.75, 10.50, 8.25], texture: "entity/chest/ender" },
                ModelFace { face: 2, uv: [7.00, 8.25, 10.50, 10.75], texture: "entity/chest/ender" },
                ModelFace { face: 3, uv: [0.00, 8.25, 3.50, 10.75], texture: "entity/chest/ender" },
                ModelFace { face: 4, uv: [10.50, 8.25, 14.00, 10.75], texture: "entity/chest/ender" },
                ModelFace { face: 5, uv: [3.50, 8.25, 7.00, 10.75], texture: "entity/chest/ender" },
            ] },
            ModelElement { from: [1.00, 10.00, 1.00], to: [15.00, 15.00, 15.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [3.50, 0.00, 7.00, 3.50], texture: "entity/chest/ender" },
                ModelFace { face: 1, uv: [7.00, 0.00, 10.50, 3.50], texture: "entity/chest/ender" },
                ModelFace { face: 2, uv: [7.00, 3.50, 10.50, 4.75], texture: "entity/chest/ender" },
                ModelFace { face: 3, uv: [0.00, 3.50, 3.50, 4.75], texture: "entity/chest/ender" },
                ModelFace { face: 4, uv: [10.50, 3.50, 14.00, 4.75], texture: "entity/chest/ender" },
                ModelFace { face: 5, uv: [3.50, 3.50, 7.00, 4.75], texture: "entity/chest/ender" },
            ] },
            ModelElement { from: [7.00, 8.00, 0.00], to: [9.00, 12.00, 1.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [0.25, 0.00, 0.75, 0.25], texture: "entity/chest/ender" },
                ModelFace { face: 1, uv: [0.75, 0.00, 1.25, 0.25], texture: "entity/chest/ender" },
                ModelFace { face: 2, uv: [0.75, 0.25, 1.00, 1.25], texture: "entity/chest/ender" },
                ModelFace { face: 3, uv: [0.00, 0.25, 0.25, 1.25], texture: "entity/chest/ender" },
                ModelFace { face: 4, uv: [1.00, 0.25, 1.50, 1.25], texture: "entity/chest/ender" },
                ModelFace { face: 5, uv: [0.25, 0.25, 0.75, 1.25], texture: "entity/chest/ender" },
            ] },
        ] },
    ] }),
    ("shulker_box", BlockEntityModel { variants: &[
        BlockEntityVariant { when: &[], elements: &[
            ModelElement { from: [0.00, 0.00, 0.00], to: [16.00, 8.00, 16.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [4.00, 7.00, 8.00, 11.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 1, uv: [8.00, 7.00, 12.00, 11.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 2, uv: [8.00, 11.00, 12.00, 13.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 3, uv: [0.00, 11.00, 4.00, 13.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 4, uv: [12.00, 11.00, 16.00, 13.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 5, uv: [4.00, 11.00, 8.00, 13.00], texture: "entity/shulker/shulker" },
            ] },
            ModelElement { from: [0.00, 4.00, 0.00], to: [16.00, 16.00, 16.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [4.00, 0.00, 8.00, 4.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 1, uv: [8.00, 0.00, 12.00, 4.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 2, uv: [8.00, 4.00, 12.00, 7.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 3, uv: [0.00, 4.00, 4.00, 7.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 4, uv: [12.00, 4.00, 16.00, 7.00], texture: "entity/shulker/shulker" },
                ModelFace { face: 5, uv: [4.00, 4.00, 8.00, 7.00], texture: "entity/shulker/shulker" },
            ] },
        ] },
    ] }),
    ("trapped_chest", BlockEntityModel { variants: &[
        BlockEntityVariant { when: &[], elements: &[
            ModelElement { from: [1.00, 0.00, 1.00], to: [15.00, 10.00, 15.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [3.50, 4.75, 7.00, 8.25], texture: "entity/chest/trapped" },
                ModelFace { face: 1, uv: [7.00, 4.75, 10.50, 8.25], texture: "entity/chest/trapped" },
                ModelFace { face: 2, uv: [7.00, 8.25, 10.50, 10.75], texture: "entity/chest/trapped" },
                ModelFace { face: 3, uv: [0.00, 8.25, 3.50, 10.75], texture: "entity/chest/trapped" },
                ModelFace { face: 4, uv: [10.50, 8.25, 14.00, 10.75], texture: "entity/chest/trapped" },
                ModelFace { face: 5, uv: [3.50, 8.25, 7.00, 10.75], texture: "entity/chest/trapped" },
            ] },
            ModelElement { from: [1.00, 10.00, 1.00], to: [15.00, 15.00, 15.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [3.50, 0.00, 7.00, 3.50], texture: "entity/chest/trapped" },
                ModelFace { face: 1, uv: [7.00, 0.00, 10.50, 3.50], texture: "entity/chest/trapped" },
                ModelFace { face: 2, uv: [7.00, 3.50, 10.50, 4.75], texture: "entity/chest/trapped" },
                ModelFace { face: 3, uv: [0.00, 3.50, 3.50, 4.75], texture: "entity/chest/trapped" },
                ModelFace { face: 4, uv: [10.50, 3.50, 14.00, 4.75], texture: "entity/chest/trapped" },
                ModelFace { face: 5, uv: [3.50, 3.50, 7.00, 4.75], texture: "entity/chest/trapped" },
            ] },
            ModelElement { from: [7.00, 8.00, 0.00], to: [9.00, 12.00, 1.00], rotation: None, faces: &[
                ModelFace { face: 0, uv: [0.25, 0.00, 0.75, 0.25], texture: "entity/chest/trapped" },
                ModelFace { face: 1, uv: [0.75, 0.00, 1.25, 0.25], texture: "entity/chest/trapped" },
                ModelFace { face: 2, uv: [0.75, 0.25, 1.00, 1.25], texture: "entity/chest/trapped" },
                ModelFace { face: 3, uv: [0.00, 0.25, 0.25, 1.25], texture: "entity/chest/trapped" },
                ModelFace { face: 4, uv: [1.00, 0.25, 1.50, 1.25], texture: "entity/chest/trapped" },
                ModelFace { face: 5, uv: [0.25, 0.25, 0.75, 1.25], texture: "entity/chest/trapped" },
            ] },
        ] },
    ] }),
];

/// The code-drawn geometry for a block, if it has any.
///
/// Colour-prefixed blocks share one shape: every shulker box is the same
/// box and every banner the same cloth, differing only in texture, so the
/// suffix is what identifies them.
pub fn block_entity_model(short_name: &str) -> Option<&'static BlockEntityModel> {
    let key = if short_name.ends_with("_shulker_box") {
        "shulker_box"
    } else if short_name.ends_with("_banner") {
        "banner"
    } else {
        short_name
    };
    BLOCK_ENTITY_MODELS
        .binary_search_by_key(&key, |(name, _)| name)
        .ok()
        .map(|i| &BLOCK_ENTITY_MODELS[i].1)
}

impl BlockEntityVariant {
    /// True when every condition holds for `props`.
    pub fn matches<'p>(&self, props: &dyn Fn(&str) -> Option<&'p str>) -> bool {
        self.when
            .iter()
            .all(|cond| props(cond.key).is_some_and(|got| cond.values.contains(&got)))
    }
}

