//! Generator for a Blender Python add-on that imports Project Bedrock OBJ
//! exports with proper materials, PBR setup, and collection organisation.
//!
//! The generated add-on:
//! - Registers an import operator under `File > Import > Project Bedrock Export`
//! - Imports the OBJ using Blender's built-in `import_scene.obj` operator
//! - Post-processes materials (applies PBR presets, sets up alpha modes)
//! - Organises objects into collections according to the configured scheme
//! - Handles the texture atlas lookup and assignment

use crate::collection::CollectionScheme;
use crate::material::{AlphaMode, PbrPreset};

/// Configuration for the generated Blender add-on.
#[derive(Debug, Clone)]
pub struct AddonOptions {
    /// Human-readable name of the add-on.
    pub name: String,
    /// Add-on version.
    pub version: (u32, u32, u32),
    /// Minimum Blender version required.
    pub blender_min: (u32, u32, u32),
    /// Collection scheme for organising imported objects.
    pub collection_scheme: CollectionScheme,
    /// Whether to enable PBR post-processing on import (requires textures).
    pub enable_pbr: bool,
    /// Whether to automatically detect and assign the texture atlas.
    pub auto_atlas: bool,
    /// Whether to invoke MCprep material prepper if available.
    pub enable_mcprep_materials: bool,
    /// Whether to invoke MCprep mesh swapping (3D blocks/plants) if available.
    pub enable_mcprep_meshswap: bool,
}

impl Default for AddonOptions {
    fn default() -> Self {
        Self {
            name: String::from("Project Bedrock Import Tools"),
            version: (0, 1, 0),
            blender_min: (3, 6, 0),
            collection_scheme: CollectionScheme::default(),
            enable_pbr: true,
            auto_atlas: true,
            enable_mcprep_materials: true,
            enable_mcprep_meshswap: true,
        }
    }
}

/// Generate the complete Blender Python add-on source code as a string.
///
/// The returned string is a valid `.py` file that can be installed directly
/// as a Blender add-on (via `Edit > Preferences > Add-ons > Install...`).
///
/// # Example
///
/// ```
/// use bedrock_blender::addon::{AddonOptions, generate_addon_py};
/// let py = generate_addon_py(&AddonOptions::default());
/// assert!(py.contains("bl_info"));
/// assert!(py.contains("Project Bedrock Import Tools"));
/// assert!(py.contains("class IMPORT_OT_project_bedrock"));
/// ```
pub fn generate_addon_py(options: &AddonOptions) -> String {
    let mut code = String::new();

    // ── Header ─────────────────────────────────────────────────────────────
    code.push_str(&format!(
        r#"# Project Bedrock Blender Import Tools — generated by bedrock-blender
#
# Install: Blender > Edit > Preferences > Add-ons > Install...
# Then enable "{}"

bl_info = {{
    "name": "{name}",
    "author": "Project Bedrock",
    "version": ({v0}, {v1}, {v2}),
    "blender": ({b0}, {b1}, {b2}),
    "location": "File > Import > Project Bedrock Export (.obj)",
    "description": "Import Project Bedrock OBJ exports with materials, PBR, and organised collections",
    "warning": "",
    "doc_url": "",
    "support": "COMMUNITY",
    "category": "Import-Export",
}}

import bpy
import os
from bpy_extras.io_utils import ImportHelper
from bpy.types import Operator
from bpy.props import StringProperty, BoolProperty, EnumProperty

# ---------------------------------------------------------------------------
# PBR Presets
# ---------------------------------------------------------------------------

PBR_PRESETS = {{
"#,
        options.name,
        name = options.name,
        v0 = options.version.0,
        v1 = options.version.1,
        v2 = options.version.2,
        b0 = options.blender_min.0,
        b1 = options.blender_min.1,
        b2 = options.blender_min.2,
    ));

    // ── PBR Preset table ───────────────────────────────────────────────────
    if options.enable_pbr {
        code.push_str(&generate_pbr_presets_python());
    }
    code.push_str(
        r#"}
# Format: { "block_name": (roughness, metallic, emissive_rgb, emissive_strength, alpha_mode, alpha_threshold) }
# alpha_mode: 0=opaque, 1=mask, 2=blend

# Swappable block types supported by MCprep 3D library
SWAPPABLE_BLOCKS = {
    "grass_block", "dandelion", "poppy", "blue_orchid", "allium", "azure_bluet",
    "red_tulip", "orange_tulip", "white_tulip", "pink_tulip", "oxeye_daisy",
    "cornflower", "lily_of_the_valley", "sunflower", "lilac", "rose_bush",
    "peony", "wheat", "carrots", "potatoes", "beetroots", "torch", "soul_torch",
    "redstone_torch", "lantern", "soul_lantern", "chest", "trapped_chest",
    "ender_chest", "crafting_table", "furnace", "blast_furnace", "smoker",
    "oak_leaves", "spruce_leaves", "birch_leaves", "jungle_leaves",
    "acacia_leaves", "dark_oak_leaves"
}

# ---------------------------------------------------------------------------
# Import Operator
# ---------------------------------------------------------------------------

class IMPORT_OT_project_bedrock(Operator, ImportHelper):
    """Import a Project Bedrock OBJ export with materials and organisation"""
    bl_idname = "import_scene.project_bedrock"
    bl_label = "Import Project Bedrock Export"
    bl_options = {'REGISTER', 'UNDO'}

    filename_ext = ".obj"

    filter_glob: StringProperty(
        default="*.obj",
        options={'HIDDEN'},
    )

    use_pbr: BoolProperty(
        name="Apply PBR Materials",
        description="Apply PBR material presets (roughness, metallic, emissive)",
        default=True,
    )

    use_mcprep_materials: BoolProperty(
        name="Use MCprep Prep Materials",
        description="Automatically run MCprep material prep on imported objects if MCprep addon is active",
        default=True,
    )

    use_mcprep_meshswap: BoolProperty(
        name="Use MCprep MeshSwap",
        description="Automatically swap vegetation, torches, and 3D blocks with MCprep models if MCprep addon is active",
        default=True,
    )

    organise_collections: BoolProperty(
        name="Organise into Collections",
        description="Organise imported objects into collections by chunk and block type",
        default=True,
    )

    collection_scheme: EnumProperty(
        name="Collection Scheme",
        description="How to organise objects into collections",
        items=[
            ('CHUNK_THEN_TYPE', 'Chunk > Block Type', 'Group by chunk, then block type'),
            ('BY_CHUNK', 'By Chunk', 'One collection per chunk'),
            ('BY_TYPE', 'By Block Type', 'One collection per block type'),
            ('FLAT', 'Flat', 'All objects in one collection'),
        ],
        default='CHUNK_THEN_TYPE',
    )

    auto_detect_atlas: BoolProperty(
        name="Auto-detect Atlas",
        description="Automatically find and assign the texture atlas PNG",
        default=True,
    )

    def execute(self, context):
        import time
        t_start = time.time()
        wm = context.window_manager
        wm.progress_begin(0, 100)

        wm.progress_update(10)
        t0 = time.time()
        result = self.import_obj(context)
        t_import = (time.time() - t0) * 1000.0
        if result != {{'FINISHED'}}:
            wm.progress_end()
            return result

        imported_objs = [obj for obj in context.selected_objects if obj.type == 'MESH']
        if not imported_objs:
            imported_objs = [obj for obj in bpy.data.objects if obj.type == 'MESH']

        # 1. Apply PBR & Atlas texturing FIRST so materials have texture nodes for MCprep
        wm.progress_update(30)
        t0 = time.time()
        if self.use_pbr:
            self.apply_pbr_materials(context)
        t_pbr = (time.time() - t0) * 1000.0

        # 2. Fast O(1) collection organization
        wm.progress_update(50)
        t0 = time.time()
        if self.organise_collections:
            self.organise_objects(context)
        t_collections = (time.time() - t0) * 1000.0

        # 3. Configure MCprep exporter setting & run MCprep operators non-interactively ('EXEC_DEFAULT')
        wm.progress_update(70)
        t_mcprep_materials = 0.0
        t_mcprep_meshswap = 0.0
        if hasattr(bpy.ops, 'mcprep'):
            try:
                if 'MCprep_addon' in bpy.context.preferences.addons:
                    bpy.context.preferences.addons['MCprep_addon'].preferences.MCprep_exporter_type = 'Mineways'
            except Exception:
                pass

            if self.use_mcprep_materials and hasattr(bpy.ops.mcprep, 'prep_materials'):
                t0 = time.time()
                try:
                    bpy.ops.mcprep.prep_materials('EXEC_DEFAULT')
                except Exception as e:
                    self.report({{'WARNING'}}, f"MCprep prep_materials warning: {{e}}")
                t_mcprep_materials = (time.time() - t0) * 1000.0

            wm.progress_update(90)
            if self.use_mcprep_meshswap and hasattr(bpy.ops.mcprep, 'meshswap'):
                t0 = time.time()
                swappable = []
                for obj in imported_objs:
                    if obj and obj.name in bpy.data.objects:
                        name_base = obj.name.split('.')[0].lower()
                        mat_base = (obj.active_material.name.split('.')[0].lower() if obj.active_material else "")
                        if name_base in SWAPPABLE_BLOCKS or mat_base in SWAPPABLE_BLOCKS:
                            swappable.append(obj)

                if swappable:
                    bpy.ops.object.select_all(action='DESELECT')
                    for o in swappable:
                        o.select_set(True)
                    context.view_layer.objects.active = swappable[0]

                    try:
                        bpy.ops.mcprep.meshswap('EXEC_DEFAULT')
                    except Exception as e:
                        self.report({{'WARNING'}}, f"MCprep meshswap warning: {{e}}")
                t_mcprep_meshswap = (time.time() - t0) * 1000.0

        wm.progress_update(100)
        wm.progress_end()

        t_total = time.time() - t_start
        summary_msg = (
            f"\n=======================================================\n"
            f" Project Bedrock Import Complete in {t_total:.2f}s\n"
            f" -------------------------------------------------------\n"
            f"  - OBJ Import:               {t_import:.1f} ms\n"
            f"  - PBR Setup:                {t_pbr:.1f} ms\n"
            f"  - Collection Organisation:  {t_collections:.1f} ms\n"
            f"  - MCprep Materials:         {t_mcprep_materials:.1f} ms\n"
            f"  - MCprep MeshSwap:          {t_mcprep_meshswap:.1f} ms\n"
            f"  - Objects Processed:        {len(imported_objs)}\n"
            f"=======================================================\n"
        )
        print(summary_msg)
        self.report({{'INFO'}}, f"Project Bedrock Import complete in {t_total:.2f}s ({len(imported_objs)} objects)")

        return {{'FINISHED'}}


    # ── Main import ──────────────────────────────────────────────────────

    def import_obj(self, context):
        """Import the OBJ using Blender's built-in importer with version fallback."""
        res = {{'CANCELLED'}}
        # Modern C++ importer (Blender 4.0+, 5.x)
        if hasattr(bpy.ops.wm, 'obj_import'):
            try:
                res = bpy.ops.wm.obj_import(
                    filepath=self.filepath,
                    forward_axis='NEGATIVE_Z',
                    up_axis='Y',
                    use_split_objects=True,
                    use_split_groups=True
                )
            except Exception:
                try:
                    res = bpy.ops.wm.obj_import(filepath=self.filepath)
                except Exception as e:
                    self.report({{'WARNING'}}, f"wm.obj_import failed: {{e}}")

        # Legacy importer (Blender 3.x)
        elif hasattr(bpy.ops, 'import_scene') and hasattr(bpy.ops.import_scene, 'obj'):
            try:
                res = bpy.ops.import_scene.obj(
                    filepath=self.filepath,
                    use_split_groups=True,
                    use_split_objects=True,
                    axis_forward='-Z',
                    axis_up='Y',
                )
            except Exception as e:
                self.report({{'ERROR'}}, f"import_scene.obj failed: {{e}}")
                return {{'CANCELLED'}}

        # Post-import: ensure each object is named by its active material so MCprep recognises all block types
        for obj in context.selected_objects:
            if obj.type == 'MESH' and obj.active_material:
                clean_name = obj.active_material.name.split('.')[0]
                obj.name = clean_name

        return res

    # ── Post-import: organise collections ────────────────────────────────

    def organise_objects(self, context):
        """Move imported objects into organised collections fast."""
        imported = [obj for obj in context.selected_objects if obj.type == 'MESH']
        if not imported:
            imported = [o for o in bpy.data.objects if o.type == 'MESH' and len(o.users_collection) <= 1]

        if not imported:
            return

        root_name = "Bedrock Export"
        root_col = (bpy.data.collections.get(root_name)
                    or bpy.data.collections.new(root_name))

        if root_col.name not in context.scene.collection.children:
            context.scene.collection.children.link(root_col)

        cols_cache = {{}}

        def get_child(parent, name):
            key = (parent.name, name)
            if key in cols_cache:
                return cols_cache[key]
            child = bpy.data.collections.get(name) or bpy.data.collections.new(name)
            if child.name not in parent.children:
                parent.children.link(child)
            cols_cache[key] = child
            return child

        scheme = self.collection_scheme
        if scheme == 'FLAT':
            for obj in imported:
                for col in list(obj.users_collection):
                    if col != root_col:
                        col.objects.unlink(obj)
                if root_col.name not in [c.name for c in obj.users_collection]:
                    root_col.objects.link(obj)
            return

        # Pre-group objects by target collection to batch dependency graph updates
        groups = {{}}
        for obj in imported:
            obj_name = obj.name.split('.')[0]
            if scheme == 'BY_CHUNK':
                chunk_name = self._guess_chunk_name(obj)
                target = get_child(root_col, chunk_name)
            elif scheme == 'BY_TYPE':
                type_name = self._sanitise_name(obj_name)
                target = get_child(root_col, f"BlockType_{{type_name}}")
            else:
                chunk_name = self._guess_chunk_name(obj)
                chunk_col = get_child(root_col, chunk_name)
                type_name = self._sanitise_name(obj_name)
                target = get_child(chunk_col, f"BlockType_{{type_name}}")

            if target not in groups:
                groups[target] = []
            groups[target].append(obj)

        for target, objs in groups.items():
            for obj in objs:
                for col in list(obj.users_collection):
                    if col != target:
                        col.objects.unlink(obj)
                target.objects.link(obj)

        self.report({{'INFO'}}, f"Organised {{len(imported)}} objects into collections")

    def _sanitise_name(self, name: str) -> str:
        """Make a name safe for Blender collection names."""
        return ''.join(c if c.isalnum() or c in '_-' else '_' for c in name)

    def _guess_chunk_name(self, obj) -> str:
        """Fast O(1) chunk coordinate estimation using bounding box center."""
        import math
        try:
            bbox = obj.bound_box
            cx = (bbox[0][0] + bbox[6][0]) * 0.5 + obj.location.x
            cz = (bbox[0][2] + bbox[6][2]) * 0.5 + obj.location.z
        except Exception:
            cx, cz = obj.location.x, obj.location.z

        chunk_x = int(math.floor(cx / 16.0))
        chunk_z = int(math.floor(cz / 16.0))
        return f"Chunk_{{chunk_x}}_{{chunk_z}}"

    def _ensure_child(self, parent, name):
        """Get or create a child collection under parent."""
        child = bpy.data.collections.get(name)
        if child is None:
            child = bpy.data.collections.new(name)
        if child.name not in parent.children:
            parent.children.link(child)
        return child

    # ── Post-import: PBR materials ────────────────────────────────────────

    def apply_pbr_materials(self, context):
        """Apply PBR presets to imported materials."""
        atlas_path = None
        if self.auto_detect_atlas:
            atlas_path = self._find_atlas()

        for mat in bpy.data.materials:
            self._apply_pbr_to_material(mat, atlas_path)

        if atlas_path:
            self.report({{'INFO'}}, f"Applied PBR with atlas: {{os.path.basename(atlas_path)}}")
        else:
            self.report({{'INFO'}}, "Applied PBR materials (no atlas found)")

    def _find_atlas(self):
        """Look for the texture atlas PNG next to the imported OBJ."""
        obj_dir = os.path.dirname(self.filepath)
        obj_base = os.path.splitext(os.path.basename(self.filepath))[0]

        # Try common atlas name patterns
        candidates = [
            os.path.join(obj_dir, f"{obj_base}.atlas.png"),
            os.path.join(obj_dir, f"{obj_base}_atlas.png"),
            os.path.join(obj_dir, "atlas.png"),
            os.path.join(obj_dir, "terrainExt.png"),
        ]
        for path in candidates:
            if os.path.isfile(path):
                return path
        return None

    def _apply_pbr_to_material(self, mat, atlas_path):
        """Apply PBR properties to a single material."""
        if not mat.use_nodes:
            mat.use_nodes = True
        nodes = mat.node_tree.nodes
        links = mat.node_tree.links

        # Clear existing nodes
        nodes.clear()

        # Get the block name from material name (sanitised)
        block_name = mat.name.split('.')[0].lower()

        # Look up PBR preset
        preset = PBR_PRESETS.get(block_name)
        roughness, metallic, emissive, emissive_strength, alpha_mode, alpha_threshold = \
            preset if preset else (0.8, 0.0, (0.0, 0.0, 0.0), 1.0, 0, 0.5)

        # Create Principled BSDF
        principled = nodes.new('ShaderNodeBsdfPrincipled')
        principled.location = (0, 0)
        principled.inputs['Roughness'].default_value = roughness
        principled.inputs['Metallic'].default_value = metallic
        if emissive != (0.0, 0.0, 0.0):
            principled.inputs['Emission Color'].default_value = (*emissive, 1.0)
            principled.inputs['Emission Strength'].default_value = emissive_strength

        # Create output node
        output = nodes.new('ShaderNodeOutputMaterial')
        output.location = (300, 0)
        links.new(principled.outputs['BSDF'], output.inputs['Surface'])

        # Handle alpha
        if alpha_mode == 1:  # mask
            mat.blend_method = 'CLIP'
            mat.alpha_threshold = alpha_threshold
        elif alpha_mode == 2:  # blend
            mat.blend_method = 'BLEND'
            principled.inputs['Alpha'].default_value = 0.95

        # Load and assign atlas texture
        if atlas_path and os.path.isfile(atlas_path):
            tex_image = nodes.new('ShaderNodeTexImage')
            tex_image.name = "MCPREP_diffuse"
            tex_image.interpolation = 'Closest'
            tex_image.location = (-400, 0)
            tex_image.image = bpy.data.images.load(atlas_path, check_existing=True)

            # Tag node for MCprep diffuse material recognition
            if hasattr(tex_image, 'mnp'):
                try:
                    tex_image.mnp.MCPREP_diffuse = True
                except Exception:
                    pass
            try:
                mat["MCPREP_diffuse"] = tex_image.image.name
            except Exception:
                pass

            # Connect atlas to Base Color
            links.new(tex_image.outputs['Color'], principled.inputs['Base Color'])

            # Connect alpha from atlas if material is transparent
            if alpha_mode in (1, 2):
                links.new(tex_image.outputs['Alpha'], principled.inputs['Alpha'])

    def invoke(self, context, event):
        context.window_manager.fileselect_add(self)
        return {{'RUNNING_MODAL'}}


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------

classes = [
    IMPORT_OT_project_bedrock,
]

def register():
    for cls in classes:
        bpy.utils.register_class(cls)
    # Add to the import menu
    bpy.types.TOPBAR_MT_file_import.append(menu_func)


def unregister():
    bpy.types.TOPBAR_MT_file_import.remove(menu_func)
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)


def menu_func(self, context):
    self.layout.operator(
        IMPORT_OT_project_bedrock.bl_idname,
        text="Project Bedrock Export (.obj)",
    )


if __name__ == "__main__":
    register()
"#,
    );

    code
}

/// Generate the Python dictionary literal for PBR presets.
fn generate_pbr_presets_python() -> String {
    use crate::material::pbr_preset;

    let mut py = String::from("    ");
    let names = crate::material::known_pbr_blocks();
    for (i, name) in names.iter().enumerate() {
        let default = PbrPreset::solid();
        let preset = pbr_preset(name).unwrap_or(default);
        let alpha = match preset.alpha_mode {
            AlphaMode::Opaque => 0,
            AlphaMode::Mask => 1,
            AlphaMode::Blend => 2,
        };
        let threshold = preset.alpha_threshold.unwrap_or(0.5);
        py.push_str(&format!(
            "\"{name}\": ({r}, {m}, ({e0}, {e1}, {e2}), {es}, {a}, {th})",
            name = name,
            r = preset.roughness,
            m = preset.metallic,
            e0 = preset.emissive[0],
            e1 = preset.emissive[1],
            e2 = preset.emissive[2],
            es = preset.emissive_strength,
            a = alpha,
            th = threshold,
        ));

        if i < names.len() - 1 {
            py.push_str(",\n    ");
        } else {
            py.push('\n');
        }
    }
    py
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn addon_contains_bl_info() {
        let py = generate_addon_py(&AddonOptions::default());
        assert!(py.contains("bl_info"));
        assert!(py.contains("Project Bedrock Import Tools"));
        assert!(py.contains("0, 1, 0"));
    }

    #[test]
    fn addon_contains_operator_class() {
        let py = generate_addon_py(&AddonOptions::default());
        assert!(py.contains("class IMPORT_OT_project_bedrock"));
        assert!(py.contains("bl_idname = \"import_scene.project_bedrock\""));
    }

    #[test]
    fn addon_contains_register_unregister() {
        let py = generate_addon_py(&AddonOptions::default());
        assert!(py.contains("def register()"));
        assert!(py.contains("def unregister()"));
        assert!(py.contains("bpy.utils.register_class"));
    }

    #[test]
    fn addon_with_pbr_has_preset_table() {
        let py = generate_addon_py(&AddonOptions::default());
        assert!(py.contains("PBR_PRESETS"));
        assert!(py.contains("\"glass\""));
        assert!(py.contains("\"iron_block\""));
    }

    #[test]
    fn addon_without_pbr_still_works() {
        let opts = AddonOptions {
            enable_pbr: false,
            ..AddonOptions::default()
        };
        let py = generate_addon_py(&opts);
        // Should still have the operator, just no PBR presets table
        assert!(py.contains("class IMPORT_OT_project_bedrock"));
    }

    #[test]
    fn addon_includes_collection_options() {
        let py = generate_addon_py(&AddonOptions::default());
        assert!(py.contains("organise_collections"));
        assert!(py.contains("collection_scheme"));
    }

    #[test]
    fn addon_includes_menu_function() {
        let py = generate_addon_py(&AddonOptions::default());
        assert!(py.contains("def menu_func"));
        assert!(py.contains("TOPBAR_MT_file_import"));
    }

    #[test]
    fn custom_version_appears() {
        let opts = AddonOptions {
            version: (1, 5, 2),
            ..AddonOptions::default()
        };
        let py = generate_addon_py(&opts);
        assert!(py.contains("1, 5, 2"));
    }

    #[test]
    fn custom_name_appears() {
        let opts = AddonOptions {
            name: "Custom Bedrock Tools".into(),
            ..AddonOptions::default()
        };
        let py = generate_addon_py(&opts);
        assert!(py.contains("Custom Bedrock Tools"));
    }

    #[test]
    fn addon_includes_mcprep_options() {
        let py = generate_addon_py(&AddonOptions::default());
        assert!(py.contains("use_mcprep_materials"));
        assert!(py.contains("use_mcprep_meshswap"));
        assert!(py.contains("bpy.ops.mcprep.prep_materials"));
        assert!(py.contains("bpy.ops.mcprep.meshswap"));
    }
}
