#!/usr/bin/env python3
"""Derive, from vanilla's own block models, which blocks are NOT full cubes.

Every hand-maintained "is this a full block?" list in this project has been
wrong in the same way: it covers the blocks someone thought of and silently
misclassifies the rest. `red_mushroom`, `bush`, `leaf_litter`, `tall_seagrass`,
`amethyst_cluster` and `firefly_bush` were all treated as solid cubes, which
kept them out of the export manifest entirely, so the importer never got a
chance to place a real asset for them.

The game already knows the answer. A blockstate names its models; a model
(after resolving its `parent` chain) has `elements` describing real geometry.
A block is a full cube exactly when every one of its models is a single
element spanning [0,0,0]..[16,16,16]. Everything else — stairs, slabs, fences,
plants, clusters, carpets — is not, and needs geometry or an asset of its own.

Usage:
    python tools/gen_block_shapes.py
"""

import io
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(REPO, "extracted_mc_assets")
BLOCKSTATES = os.path.join(ASSETS, "blockstates")
MODELS = os.path.join(ASSETS, "models")
OUT = os.path.join(REPO, "crates", "bedrock-parser", "src", "block_shapes.rs")

_model_cache = {}


def load_model(ref):
    """Load a model JSON by reference like 'minecraft:block/stone'."""
    ref = ref.split(":", 1)[-1]
    if ref in _model_cache:
        return _model_cache[ref]
    path = os.path.join(MODELS, *ref.split("/")) + ".json"
    data = None
    if os.path.isfile(path):
        try:
            data = json.load(io.open(path, encoding="utf-8"))
        except Exception:
            data = None
    _model_cache[ref] = data
    return data


def resolve_elements(ref, depth=0):
    """Follow the parent chain until a model defines `elements`."""
    if depth > 12:
        return None
    model = load_model(ref)
    if model is None:
        return None
    if "elements" in model:
        return model["elements"]
    parent = model.get("parent")
    if not parent:
        return None
    return resolve_elements(parent, depth + 1)


def is_full_cube_model(ref):
    elements = resolve_elements(ref)
    if not elements:
        # No geometry found (missing model, or a parent we can't resolve).
        # Treat as "not a full cube" so the block is *included* downstream —
        # a wrongly-included block costs a manifest entry, a wrongly-excluded
        # one silently never gets an asset.
        return False
    if len(elements) != 1:
        return False
    element = elements[0]
    frm, to = element.get("from"), element.get("to")
    if frm is None or to is None:
        return False
    return list(frm) == [0, 0, 0] and list(to) == [16, 16, 16]


def model_refs(blockstate):
    """Every model referenced by a blockstate file."""
    refs = []

    def collect(entry):
        if isinstance(entry, list):
            for item in entry:
                collect(item)
        elif isinstance(entry, dict):
            if "model" in entry:
                refs.append(entry["model"])

    for variant in (blockstate.get("variants") or {}).values():
        collect(variant)
    for part in blockstate.get("multipart") or []:
        collect(part.get("apply"))
    return refs


def main():
    if not os.path.isdir(BLOCKSTATES):
        print(f"missing {BLOCKSTATES} — extract the client jar assets first")
        return 1

    non_cube = []
    full_cube = 0
    for filename in sorted(os.listdir(BLOCKSTATES)):
        if not filename.endswith(".json"):
            continue
        block = filename[:-5]
        try:
            state = json.load(io.open(os.path.join(BLOCKSTATES, filename), encoding="utf-8"))
        except Exception:
            continue
        refs = model_refs(state)
        if not refs:
            non_cube.append(block)
            continue
        if all(is_full_cube_model(r) for r in refs):
            full_cube += 1
        else:
            non_cube.append(block)

    print(f"{full_cube} full-cube blocks, {len(non_cube)} non-cube blocks")

    out = io.StringIO()
    out.write(
        "// Auto-generated by tools/gen_block_shapes.py from vanilla block models.\n"
        "//\n"
        "// Do not hand-edit. Regenerate after updating extracted_mc_assets/.\n"
        "//\n"
        "// A block is a \"full cube\" when every model its blockstate references\n"
        "// resolves to a single element spanning [0,0,0]..[16,16,16]. Blocks that\n"
        "// are not are the ones a plain cube misrepresents -- stairs, slabs,\n"
        "// fences, plants, clusters, carpets -- and are the ones an importer needs\n"
        "// real geometry or a swapped asset for.\n"
        "\n"
        f"/// Blocks whose shape is not a full 16x16x16 cube ({len(non_cube)} entries, sorted).\n"
        "#[rustfmt::skip]\n"
        "static NON_CUBE_BLOCKS: &[&str] = &[\n"
    )
    for block in non_cube:
        out.write(f'    "{block}",\n')
    out.write(
        "];\n"
        "\n"
        "/// True when `short_name` (no namespace) is a full 16x16x16 cube.\n"
        "///\n"
        "/// Unknown blocks are reported as full cubes: an unrecognised id is more\n"
        "/// likely modded terrain than a plant, and over-reporting non-cubes would\n"
        "/// bloat the export manifest.\n"
        "pub fn is_full_cube(short_name: &str) -> bool {\n"
        "    NON_CUBE_BLOCKS.binary_search(&short_name).is_err()\n"
        "}\n"
        "\n"
        "#[cfg(test)]\n"
        "mod tests {\n"
        "    use super::*;\n"
        "\n"
        "    #[test]\n"
        "    fn table_is_sorted_for_binary_search() {\n"
        "        assert!(NON_CUBE_BLOCKS.windows(2).all(|w| w[0] < w[1]));\n"
        "    }\n"
        "\n"
        "    #[test]\n"
        "    fn classifies_the_blocks_hand_lists_kept_missing() {\n"
        "        // Every one of these was previously treated as a solid cube and\n"
        "        // therefore never reached the export manifest.\n"
        "        for block in [\n"
        "            \"red_mushroom\", \"bush\", \"leaf_litter\", \"tall_seagrass\",\n"
        "            \"amethyst_cluster\", \"firefly_bush\", \"oak_stairs\",\n"
        "            \"stone_slab\", \"oak_fence\", \"torch\", \"sugar_cane\",\n"
        "        ] {\n"
        "            assert!(!is_full_cube(block), \"{block} should not be a full cube\");\n"
        "        }\n"
        "        for block in [\"stone\", \"dirt\", \"deepslate\", \"oak_planks\"] {\n"
        "            assert!(is_full_cube(block), \"{block} should be a full cube\");\n"
        "        }\n"
        "    }\n"
        "}\n"
    )
    io.open(OUT, "w", encoding="utf-8").write(out.getvalue())
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
